/** Poradniki problemowe — Sprzęt, Bezpieczeństwo i reszta systemu. */
export default [
  {
    kat: 'sprzet',
    title: 'Dysk zniknął z systemu w trakcie pracy',
    excerpt: 'Rozróżnienie awarii nośnika od problemu z kablem lub kontrolerem — bez pogarszania sytuacji.',
    body: `<p>Urządzenie przestało być widoczne przy działającym systemie. Pierwsza zasada: nie restartuj od razu, dopóki nie przeczytasz dziennika. Po restarcie zniknie najważniejszy ślad.</p><h2>1. Co widzi jądro</h2><pre><code>dmesg -T | tail -60
journalctl -k -p err --since "30 min ago"</code></pre><p>Rozstrzygające wpisy:</p><ul><li><code>link is slow to respond</code>, <code>hard resetting link</code> — kabel, zasilanie albo kontroler.</li><li><code>Medium Error</code>, <code>Unrecovered read error</code> — powierzchnia nośnika.</li><li><code>I/O error, dev sdb, sector ...</code> — konkretne sektory.</li><li><code>nvme nvme0: controller is down</code> — kontroler dysku NVMe, często termiczny.</li></ul><h2>2. Czy urządzenie w ogóle istnieje</h2><pre><code>lsblk
ls -l /dev/disk/by-id/
smartctl --scan</code></pre><h2>3. Kolejność, która ratuje dane</h2><ol><li>Jeśli na dysku są dane, których nie masz nigdzie indziej — <strong>zrób obraz, zanim zaczniesz naprawiać</strong>.</li><li>Nie uruchamiaj sprawdzania systemu plików na podejrzanym nośniku.</li><li>Nie restartuj w kółko — każde rozkręcenie padającego dysku może być ostatnim.</li></ol><pre><code>ddrescue -d -r3 /dev/sdb obraz.img mapa.log</code></pre><h2>4. Kiedy to nie dysk</h2><p>Objawy identyczne daje luźny kabel danych, słaby zasilacz przy kilku dyskach naraz i przegrzany kontroler w obudowie zewnętrznej. Test polega na podłączeniu innym kablem i do innego portu.</p><h2>5. Dyski NVMe i temperatura</h2><pre><code>nvme smart-log /dev/nvme0 | grep -i temp</code></pre><p>Znikanie pod obciążeniem, powrót po ostygnięciu, to zabezpieczenie termiczne kontrolera — nie awaria nośnika.</p><h2>6. Po odzyskaniu</h2><pre><code>smartctl -a /dev/sdb
smartctl -t long /dev/sdb</code></pre><h2>Czego ten materiał nie rozwiązuje</h2><p>Stukanie, mielenie albo cykliczne rozkręcanie to awaria mechaniczna. Przy ważnych danych każda kolejna próba pogarsza sytuację i właściwym krokiem jest odłączenie dysku oraz firma specjalistyczna.</p>`,
  },
  {
    kat: 'sprzet',
    title: 'Komputer wyłącza się pod obciążeniem',
    excerpt: 'Zasilanie, temperatura czy pamięć — jak je rozdzielić metodą eliminacji.',
    body: `<p>Nagłe wyłączenie bez komunikatu ma trzy typowe przyczyny. Ślad w dziennikach zwykle nie istnieje, bo system nie zdążył nic zapisać — i to samo w sobie jest wskazówką.</p><h2>1. Co zostało w dziennikach</h2><pre><code>journalctl -k -b -1 -p err --no-pager | tail -30
dmesg -T | grep -iE "thermal|mce|hardware error"</code></pre><p>Zupełna cisza tuż przed wyłączeniem przemawia za zasilaniem. Wpisy o temperaturze — za chłodzeniem. Wpisy o błędach zgłoszonych przez procesor — za pamięcią lub płytą.</p><h2>2. Temperatura — sprawdzana w trakcie, nie po</h2><pre><code>watch -n1 sensors
stress-ng --cpu 0 --timeout 15m</code></pre><p>Wyłączenie przy temperaturze poniżej progu krytycznego wyklucza przegrzanie procesora — ale nie wyklucza przegrzania sekcji zasilania płyty, której czujników zwykle nie widać.</p><h2>3. Zasilacz</h2><p>Objaw charakterystyczny: wyłączenie przy obciążeniu karty graficznej, nie przy samym procesorze.</p><pre><code>glmark2
# albo dowolne obciążenie karty, przy jednoczesnym obciążeniu procesora</code></pre><p>Zasilacz degraduje się z wiekiem i przy zestawie starszym niż kilka lat jest pierwszym podejrzanym. Rozstrzyga wyłącznie podmiana na sprawny — testery bez obciążenia nie wykrywają tej usterki.</p><h2>4. Pamięć</h2><p>Test przez noc. Wcześniej wyłączamy profil podkręcania — to najczęstsza pojedyncza przyczyna niestabilności pod obciążeniem.</p><h2>5. Eliminacja</h2><p>Odłączamy wszystko, co niepotrzebne: dodatkowe dyski, karty, urządzenia USB. Jeden moduł pamięci. Jeśli stabilne — dokładamy po jednym elemencie.</p><h2>6. Prąd z gniazdka</h2><p>Spadki napięcia w instalacji dają identyczny objaw, często skorelowany z włączeniem innego urządzenia w mieszkaniu. UPS z funkcją korekcji napięcia rozstrzyga i przy okazji rozwiązuje.</p><h2>Czego ten materiał nie rozwiązuje</h2><p>Bez zapasowych podzespołów do podmiany diagnostyka bywa niekonkluzywna — objawy zasilacza, płyty i procesora potrafią być identyczne. To główny argument, żeby nie kupować części na podstawie samego domysłu.</p>`,
  },
  {
    kat: 'sprzet',
    title: 'Nowy dysk NVMe niewidoczny w systemie',
    excerpt: 'Od gniazda i współdzielonych linii po tryb kontrolera i tablicę partycji.',
    body: `<p>Dysk zamontowany, system go nie widzi. Sprawdzamy od najniższej warstwy.</p><h2>1. Czy widzi go magistrala</h2><pre><code>lspci | grep -i nvme
nvme list
lsblk</code></pre><p>Brak w pierwszym poleceniu oznacza, że problem jest sprzętowy albo w ustawieniach płyty — system operacyjny nie ma tu nic do rzeczy.</p><h2>2. Współdzielone linie PCIe</h2><p>Najczęstsza przyczyna przy drugim dysku. Płyty rozdzielają ograniczoną liczbę linii: zajęcie drugiego gniazda M.2 często wyłącza część portów SATA albo przełącza gniazdo karty graficznej na mniejszą liczbę linii. Bywa też odwrotnie — podłączony dysk SATA wyłącza gniazdo M.2.</p><p>Rozstrzyga wyłącznie instrukcja płyty głównej, w tabeli współdzielenia zasobów.</p><h2>3. Ustawienia płyty</h2><ul><li>Tryb kontrolera przestawiony na zgodność ze starszym standardem zamiast NVMe.</li><li>Gniazdo M.2 wyłączone albo ustawione tylko na tryb SATA.</li><li>Stare oprogramowanie układowe bez obsługi nowszych dysków.</li></ul><h2>4. Dysk widoczny, ale bez partycji</h2><p>Nowy dysk nie ma tablicy partycji i dlatego nie pojawia się w menedżerze plików. To normalne:</p><pre><code>nvme list
parted /dev/nvme0n1 mklabel gpt
parted -a opt /dev/nvme0n1 mkpart dane ext4 0% 100%
mkfs.ext4 /dev/nvme0n1p1</code></pre><h2>5. Dysk z poprzedniego systemu</h2><p>Dysk z systemem Windows w trybie szybkiego uruchamiania bywa zablokowany do zapisu. Podobnie dysk wyjęty z macierzy nadal ma na sobie jej metadane:</p><pre><code>wipefs /dev/nvme0n1        # pokazuje, co jest na dysku
wipefs -a /dev/nvme0n1     # KASUJE — bez odwrotu</code></pre><h2>6. Format 4K</h2><p>Część dysków korporacyjnych jest sformatowana z sektorem 4096 bajtów i nie działa ze starszymi płytami:</p><pre><code>nvme id-ns /dev/nvme0n1 -H | grep -i lba</code></pre><h2>Czego ten materiał nie rozwiązuje</h2><p>Dysku niewidocznego w żadnej maszynie i w żadnym gnieździe — to zwykle usterka fabryczna i sprawa dla reklamacji, a nie dla konfiguracji.</p>`,
  },
  {
    kat: 'sprzet',
    title: 'Urządzenie USB rozłącza się i podłącza w kółko',
    excerpt: 'Zasilanie, kabel, oszczędzanie energii — trzy przyczyny cyklicznego odłączania.',
    body: `<p>W dzienniku pojawiają się na przemian komunikaty o podłączeniu i odłączeniu tego samego urządzenia. To niemal zawsze warstwa fizyczna albo zasilanie.</p><h2>1. Potwierdzenie w dzienniku</h2><pre><code>dmesg -Tw</code></pre><p>Uruchomione przed podłączeniem pokazuje cały przebieg. Komunikaty o resecie urządzenia i ponownej numeracji potwierdzają rozpoznanie.</p><h2>2. Zasilanie</h2><p>Dysk zewnętrzny bez własnego zasilacza potrafi pobierać w szczycie więcej, niż port jest w stanie dać — zwłaszcza przez koncentrator bez zasilania albo w przednim panelu obudowy. Test: podłączenie wprost do portu z tyłu płyty i, jeśli to możliwe, z zasilaczem.</p><h2>3. Kabel</h2><p>Kabel przeznaczony do ładowania często nie ma pełnego zestawu żył. Kabel zbyt długi albo uszkodzony daje dokładnie ten objaw. To najtańsza rzecz do sprawdzenia i warto zacząć od niej.</p><h2>4. Oszczędzanie energii</h2><p>System usypia porty, a niektóre urządzenia nie budzą się poprawnie:</p><pre><code>cat /sys/bus/usb/devices/*/power/control
for f in /sys/bus/usb/devices/*/power/control; do echo on &gt; "$f"; done</code></pre><p>Trwale przez parametr jądra <code>usbcore.autosuspend=-1</code> albo regułę udev dla konkretnego urządzenia.</p><h2>5. Port USB 3 i zakłócenia</h2><p>Porty w tym standardzie zakłócają pasmo 2,4 GHz. Objaw pozornie niezwiązany: mysz bezprzewodowa zaczyna gubić ruchy po podłączeniu dysku obok. Rozwiązaniem jest przeniesienie odbiornika dalej albo do portu USB 2.</p><h2>6. Identyfikacja urządzenia</h2><pre><code>lsusb
lsusb -t
udevadm monitor --udev</code></pre><h2>Czego ten materiał nie rozwiązuje</h2><p>Uszkodzonego kontrolera w obudowie dysku zewnętrznego — objaw jest identyczny, a jedynym rozstrzygnięciem jest wyjęcie dysku i podłączenie go wprost.</p>`,
  },
  {
    kat: 'sprzet',
    title: 'Interfejs sieciowy w stanie DOWN po starcie systemu',
    excerpt: 'Oszczędzanie energii na magistrali, sterownik i kolejność startu.',
    body: `<p>Po restarcie sieć nie działa, po ręcznym podniesieniu interfejsu wszystko wraca. To wzorzec wskazujący na kilka konkretnych przyczyn.</p><h2>1. Stan i sterownik</h2><pre><code>ip -br link show
ethtool -i enp3s0
dmesg -T | grep -iE "enp|eth|link"</code></pre><h2>2. Oszczędzanie energii na magistrali</h2><p>Część kontrolerów — zwłaszcza obsługiwanych przez sterownik <code>r8169</code> — nieprawidłowo wychodzi z uśpienia łącza PCIe. Objaw: interfejs w stanie DOWN po starcie, losowe zrywanie albo dramatyczny spadek przepustowości, zwykle bez żadnego wpisu w dzienniku.</p><pre><code>ethtool --show-priv-flags enp3s0
ethtool --set-priv-flags enp3s0 aspm off</code></pre><p>Globalnie, przez parametr jądra:</p><pre><code>pcie_aspm=off</code></pre><h2>3. Wake-on-LAN i tryb zasilania</h2><pre><code>ethtool enp3s0 | grep -i wake
ethtool -s enp3s0 wol d</code></pre><h2>4. Kolejność startu</h2><p>Usługa sieciowa wystartowała, zanim sterownik zdążył zainicjować kartę. Widać to po znacznikach czasu w dzienniku:</p><pre><code>journalctl -b -u NetworkManager -u systemd-networkd --no-pager | head -40</code></pre><h2>5. Nazwa interfejsu się zmieniła</h2><p>Po przełożeniu karty do innego gniazda albo po aktualizacji jądra nazwa bywa inna, a konfiguracja odwołuje się do starej:</p><pre><code>ip -br link show
nmcli con show</code></pre><p>Trwałym rozwiązaniem jest reguła udev wiążąca nazwę z adresem sprzętowym.</p><h2>6. Negocjacja prędkości</h2><pre><code>ethtool enp3s0 | grep -E "Speed|Duplex|Link detected"</code></pre><p>Brak wykrytego łącza przy podłączonym kablu to kabel, gniazdo w przełączniku albo sama karta.</p><h2>Czego ten materiał nie rozwiązuje</h2><p>Wyłączenie oszczędzania energii podnosi pobór mocy — na laptopie odbije się to na czasie pracy na baterii. Na maszynie zasilanej z gniazdka koszt jest pomijalny.</p>`,
  },
  {
    kat: 'sprzet',
    title: 'Wentylatory chodzą cały czas na maksymalnych obrotach',
    excerpt: 'Czujnik, krzywa sterowania i przypadki, w których to zabezpieczenie, a nie usterka.',
    body: `<p>Wentylatory na pełnych obrotach mimo bezczynności mają kilka rozłącznych przyczyn — od banalnych po celowe zachowanie płyty.</p><h2>1. Czy naprawdę jest gorąco</h2><pre><code>sensors
smartctl -A /dev/sda | grep -i temp
nvme smart-log /dev/nvme0 | grep -i temp</code></pre><p>Wysoka temperatura oznacza, że wentylatory robią to, co powinny — problem jest w chłodzeniu, nie w sterowaniu.</p><h2>2. Płyta nie wie, jak sterować</h2><p>Wentylator trzypinowy w gnieździe oczekującym sterowania szerokością impulsu potrafi chodzić stale na maksimum. To ograniczenie sprzętowe — rozwiązaniem jest inne gniazdo albo przestawienie trybu w ustawieniach płyty na sterowanie napięciem.</p><h2>3. Brak konfiguracji sterowania w systemie</h2><pre><code>sensors-detect
pwmconfig
systemctl enable --now fancontrol</code></pre><p>Narzędzie po kolei zatrzymuje wentylatory i sprawdza, który obrót odpowiada któremu czujnikowi. Na czas konfiguracji nie obciążamy maszyny.</p><h2>4. Odłączony albo uszkodzony czujnik</h2><p>Płyta, która nie dostaje odczytu temperatury, przechodzi na pełne obroty z ostrożności. Odczyt zerowy albo absurdalnie wysoki w <code>sensors</code> wskazuje właśnie na to.</p><h2>5. Zabrudzenie</h2><p>Zapchane żeberka radiatora podnoszą temperaturę przy tym samym obciążeniu, więc krzywa sterowania działa poprawnie — tylko warunki się zmieniły. Czyszczenie i wymiana pasty przywracają ciszę bez żadnych zmian w konfiguracji.</p><h2>6. Po aktualizacji oprogramowania układowego</h2><p>Aktualizacja czyści ustawienia, w tym profile wentylatorów. Jeśli hałas zaczął się dokładnie po niej — trzeba je ustawić od nowa.</p><h2>Czego ten materiał nie rozwiązuje</h2><p>W wielu laptopach sterowanie wentylatorem jest zamknięte w oprogramowaniu układowym i niedostępne dla systemu. Tam pozostaje czyszczenie, wymiana pasty i ograniczenie taktowania procesora.</p>`,
  },
  {
    kat: 'sprzet',
    title: 'Brak obrazu po zmianie kabla lub rozdzielczości',
    excerpt: 'Klasa kabla, wersja standardu i wyjście awaryjne, gdy nic nie widać.',
    body: `<p>Monitor pokazuje brak sygnału, choć wcześniej działał. Najczęściej odpowiada za to kabel albo tryb wykraczający poza możliwości połączenia.</p><h2>1. Wyjście awaryjne — najpierw</h2><p>Jeśli nie widzisz nic, przełącz się na konsolę tekstową skrótem Ctrl+Alt+F3 i pracuj stamtąd. Przy zdalnym dostępie przez SSH problem obrazu w ogóle nie blokuje naprawy.</p><h2>2. Co widzi system</h2><pre><code>xrandr --verbose | head -40
drm_info 2&gt;/dev/null | head -40
dmesg -T | grep -iE "drm|edid|link training"</code></pre><p>Wpisy o nieudanym uczeniu łącza w DisplayPort albo o odczycie danych identyfikacyjnych monitora wskazują na kabel lub przejściówkę.</p><h2>3. Kabel jest częścią układu</h2><p>Kabel bez odpowiedniej klasy przepuści niższe tryby, a przy wyższych da migotanie, czarne przebłyski albo brak obrazu. Przy wysokich rozdzielczościach i odświeżaniach to najczęstsza przyczyna i najtańsza do sprawdzenia — wystarczy inny kabel.</p><h2>4. Przejściówki</h2><p>Przejście z DisplayPort na HDMI zwykle działa; w drugą stronę wymaga aktywnego układu i często zawodzi. Tanie przejściówki ograniczają odświeżanie w sposób nieudokumentowany.</p><h2>5. Powrót do bezpiecznego trybu</h2><pre><code>xrandr --output HDMI-1 --mode 1920x1080 --rate 60</code></pre><p>Przy braku obrazu robimy to z konsoli tekstowej albo przez SSH, po ustawieniu zmiennej wskazującej ekran.</p><h2>6. Monitor nie budzi się ze snu</h2><p>Osobny, częsty przypadek. Bywa rozwiązywany wyłączeniem trybu głębokiego DisplayPort w menu monitora albo aktualizacją jego oprogramowania.</p><h2>7. Dwie karty graficzne</h2><p>Wyjście na płycie działa tylko przy włączonym układzie zintegrowanym w ustawieniach — po zamontowaniu karty bywa on wyłączany automatycznie.</p><h2>Czego ten materiał nie rozwiązuje</h2><p>Ustawienia rozdzielczości powyżej możliwości kabla i tak nie zadziała, choćby system je oferował. Lista trybów pochodzi od monitora i nie uwzględnia tego, co przenosi połączenie.</p>`,
  },
  {
    kat: 'bezpieczenstwo',
    title: 'Serwer rozsyła spam — pierwsze kroki',
    excerpt: 'Zatrzymanie wysyłki, ustalenie źródła i decyzja, czy maszyna nadaje się do dalszej pracy.',
    body: `<p>Adres trafił na listy blokad albo dostawca przysłał ostrzeżenie. Kolejność ma znaczenie: najpierw zatrzymać, potem ustalać.</p><h2>1. Zatrzymanie wysyłki</h2><pre><code>systemctl stop postfix exim4 2&gt;/dev/null
mailq | tail -5
postsuper -d ALL     # kasuje kolejkę — nieodwracalne</code></pre><p>Zanim skasujesz kolejkę, obejrzyj kilka wiadomości. To najlepszy materiał dowodowy.</p><h2>2. Skąd wychodzą</h2><pre><code>grep "from=" /var/log/mail.log | awk '{print $7}' | sort | uniq -c | sort -rn | head
ss -tnp | grep :25</code></pre><p>Nazwa procesu wysyłającego rozstrzyga najszybciej: skrypt PHP, konto użytkownika czy sam serwer poczty.</p><h2>3. Trzy typowe źródła</h2><ul><li><strong>Otwarty przekaźnik</strong> — serwer przyjmuje pocztę od każdego. Konfiguracja, nie włamanie.</li><li><strong>Podatna aplikacja</strong> — formularz kontaktowy bez zabezpieczeń albo wgrany skrypt.</li><li><strong>Przejęte konto</strong> — ktoś zdobył hasło do skrzynki i wysyła uwierzytelniony.</li></ul><h2>4. Sprawdzenie przekaźnika</h2><pre><code>postconf mynetworks smtpd_relay_restrictions</code></pre><h2>5. Szukanie wgranego skryptu</h2><pre><code>find /var/www -type f -newermt "-14 days" -name "*.php" | head -50
grep -rlE "eval *\\(|base64_decode|shell_exec" /var/www --include=*.php | head</code></pre><h2>6. Decyzja, której nie da się uniknąć</h2><p>Jeśli źródłem był wgrany skrypt, ktoś miał możliwość zapisu na serwerze — a to znaczy, że mógł zostawić także inne rzeczy. Rzetelną drogą jest odtworzenie systemu od zera i wymiana wszystkich haseł oraz kluczy, które na nim były. Usunięcie znalezionego pliku zostawia te, których się nie znalazło.</p><h2>7. Zejście z list blokad</h2><p>Dopiero po usunięciu przyczyny. Wniosek złożony przy nadal działającej wysyłce kończy się ponownym wpisem i pogarsza reputację adresu.</p><h2>Czego ten materiał nie rozwiązuje</h2><p>Reputacja adresu odbudowuje się tygodniami. Przy poczcie istotnej dla działania firmy rozsądniej jest przejść na wysyłkę przez zewnętrznego dostawcę.</p>`,
  },
  {
    kat: 'bezpieczenstwo',
    title: 'Nieznany proces zużywa cały procesor',
    excerpt: 'Rozpoznanie koparki kryptowalut i uporządkowana reakcja.',
    body: `<p>Obciążenie na maksimum, proces o nieznanej nazwie. Zanim go zabijesz, zbierz informacje — po restarcie zniknie większość śladów.</p><h2>1. Co to jest i skąd się wzięło</h2><pre><code>ps -eo pid,ppid,user,etime,%cpu,cmd --sort=-%cpu | head
ls -l /proc/&lt;pid&gt;/exe
ls -l /proc/&lt;pid&gt;/cwd
cat /proc/&lt;pid&gt;/environ | tr '\\0' '\\n'</code></pre><p>Ścieżka do pliku wykonywalnego jest kluczowa. Katalog tymczasowy, katalog domowy albo skasowany plik (widoczny jako usunięty) to bardzo silny sygnał.</p><h2>2. Z czym się łączy</h2><pre><code>ss -tnp | grep &lt;pid&gt;
lsof -p &lt;pid&gt; -i</code></pre><p>Połączenie na nietypowym porcie do nieznanego adresu potwierdza rozpoznanie.</p><h2>3. Sygnały typowe dla koparki</h2><ul><li>Nazwa udająca proces systemowy, ale w złym katalogu.</li><li>Stałe stuprocentowe obciążenie wszystkich rdzeni.</li><li>Zadanie w harmonogramie uruchamiające proces ponownie po zabiciu.</li><li>Wpis w plikach startowych powłoki albo własna jednostka systemd.</li></ul><h2>4. Utrwalenie — sprawdź, zanim zabijesz</h2><pre><code>crontab -l; for u in $(cut -d: -f1 /etc/passwd); do crontab -u $u -l 2&gt;/dev/null; done
ls -la /etc/cron.*
systemctl list-units --type=service --state=running
systemctl list-timers
cat ~/.ssh/authorized_keys</code></pre><h2>5. Jak wszedł</h2><pre><code>last -30
journalctl -u ssh --since "7 days ago" | grep -i accepted
find /var/www -type f -newermt "-14 days" | head -50</code></pre><p>Najczęstsze drogi: słabe hasło do SSH, podatna aplikacja z możliwością wgrania pliku, wystawiony na świat panel bez uwierzytelniania, znana luka w niezałatanej usłudze.</p><h2>6. Jedyna rzetelna reakcja</h2><p>Odtworzenie systemu od zera. Ktoś wykonał kod na tej maszynie — nie da się z niej samej stwierdzić, co jeszcze zostawił, bo narzędzia, którymi to sprawdzasz, też mogły zostać podmienione. Wszystkie hasła i klucze, które tam były, traktujemy jako ujawnione.</p><h2>Czego ten materiał nie rozwiązuje</h2><p>Sprzątanie znalezionych plików jest kuszące i tanie, ale zostawia to, czego się nie znalazło. Jeśli maszyna obsługuje cokolwiek istotnego, skrót ten kończy się zwykle powrotem problemu.</p>`,
  },
  {
    kat: 'bezpieczenstwo',
    title: 'Tysiące nieudanych logowań w dziennikach — czy to problem',
    excerpt: 'Odróżnienie tła internetu od ataku wymierzonego w konkretny serwer.',
    body: `<p>Każdy serwer z otwartym portem SSH zbiera tysiące prób dziennie. Samo w sobie nie jest to zdarzenie — pytanie brzmi, czy któraś się udała i czy wzorzec jest inny niż zwykle.</p><h2>1. Skala i źródła</h2><pre><code>journalctl -u ssh --since "24 hours ago" | grep -c "Failed password"
journalctl -u ssh --since "24 hours ago" | grep "Failed password" \\
  | awk '{print $(NF-3)}' | sort | uniq -c | sort -rn | head</code></pre><h2>2. Pytanie najważniejsze: czy któraś się udała</h2><pre><code>journalctl -u ssh --since "7 days ago" | grep -i "Accepted"
last -30</code></pre><p>To jedyna rzecz, która naprawdę zmienia sytuację.</p><h2>3. Tło czy atak wymierzony</h2><ul><li><strong>Tło</strong> — nazwy typu <code>admin</code>, <code>test</code>, <code>ubuntu</code>, tysiące różnych adresów, po jednej próbie z każdego.</li><li><strong>Wymierzony</strong> — prawdziwe nazwy kont z twojego serwera, próby rozłożone w czasie, uporczywe wracanie z tych samych adresów.</li></ul><p>To rozróżnienie jest istotne: pierwszy przypadek to szum, drugi oznacza, że ktoś zna twoją infrastrukturę.</p><h2>4. Rozwiązanie, które usuwa problem</h2><pre><code>PasswordAuthentication no
PubkeyAuthentication yes</code></pre><pre><code>sshd -t &amp;&amp; systemctl reload ssh</code></pre><p>Przy wyłączonym logowaniu hasłem liczba prób przestaje mieć znaczenie — nie ma czego zgadywać.</p><h2>5. Ograniczenie hałasu</h2><pre><code>apt install fail2ban
systemctl enable --now fail2ban
fail2ban-client status sshd</code></pre><p>To porządkuje dzienniki, ale nie jest linią obrony — przy tysiącu adresów próbujących po razie nie pomoże.</p><h2>6. Najskuteczniejsze</h2><p>Ograniczenie dostępu do SSH do znanych adresów albo wyłącznie przez VPN. Port niedostępny jest odporny na wszystkie te próby.</p><h2>Czego ten materiał nie rozwiązuje</h2><p>Zmiana portu SSH zmniejsza hałas w dziennikach o rzędy wielkości, ale nie jest zabezpieczeniem — skanowanie całego zakresu portów zajmuje minuty.</p>`,
  },
  {
    kat: 'bezpieczenstwo',
    title: 'Podejrzenie wycieku bazy danych — pierwsze godziny',
    excerpt: 'Kolejność działań, która ogranicza szkody i nie niszczy śladów.',
    body: `<p>Kolejność ma tu większe znaczenie niż tempo. Pierwszy odruch — „posprzątać i nie mówić" — jest zwykle najgorszą możliwą decyzją.</p><h2>1. Zabezpiecz ślady, zanim cokolwiek zmienisz</h2><p>Migawka maszyny albo kopia dzienników w inne miejsce. Restart i sprzątanie niszczą materiał potrzebny do ustalenia zakresu.</p><pre><code>journalctl --since "30 days ago" &gt; /bezpieczne/dziennik.txt
cp -a /var/log /bezpieczne/log-kopia</code></pre><h2>2. Odetnij drogę wejścia</h2><p>Jeśli wiadomo, którędy — zamknij. Jeśli nie — ogranicz dostęp do bazy do niezbędnego minimum i zmień poświadczenia.</p><h2>3. Ustal zakres</h2><pre><code>SELECT usename, client_addr, backend_start, state
FROM pg_stat_activity ORDER BY backend_start DESC;</code></pre><p>Dzienniki dostępu, ruch wychodzący, nietypowe zapytania masowe. Pytanie brzmi: jakie dane i czyje mogły zostać pobrane.</p><h2>4. Wymień wszystko, co mogło wyciec</h2><ul><li>Hasła do bazy i kont usługowych.</li><li>Klucze API i tokeny w konfiguracji.</li><li>Klucze SSH z tej maszyny.</li><li>Sekrety sesji — ich zmiana wylogowuje wszystkich, co jest tu zaletą.</li></ul><h2>5. Hasła użytkowników</h2><p>Jeśli w bazie były skróty haseł, wymuś zmianę. Nawet dobrze zahaszowane hasła są zagrożone, bo ludzie używają ich w wielu serwisach.</p><h2>6. Obowiązki prawne</h2><p>Przy danych osobowych obowiązują terminy zgłoszenia do organu nadzorczego, a przy wysokim ryzyku także zawiadomienie osób, których dane dotyczą. Terminy liczą się od stwierdzenia naruszenia, nie od zakończenia analizy — <strong>i biegną niezależnie od tego, czy zdążyłeś ustalić szczegóły</strong>. To jest moment na kontakt z prawnikiem, nie na czekanie.</p><h2>7. Odtworzenie systemu</h2><p>Jeśli napastnik wykonywał kod na maszynie, sprzątanie nie wystarczy. System stawia się od nowa, a dane przenosi po sprawdzeniu.</p><h2>Czego ten materiał nie rozwiązuje</h2><p>Nie da się z pewnością stwierdzić, czego nie pobrano. Brak śladów w dziennikach nie jest dowodem — zwłaszcza gdy napastnik miał uprawnienia pozwalające je zmienić.</p>`,
  },
  {
    kat: 'bezpieczenstwo',
    title: 'Utrata dostępu do zaszyfrowanego dysku LUKS',
    excerpt: 'Co da się uratować, czego nie, i jak nie doprowadzić do tego drugi raz.',
    body: `<p>Zacznijmy od uczciwej odpowiedzi: przy poprawnie ustawionym szyfrowaniu i utraconym haśle danych nie da się odzyskać. Poniżej to, co warto sprawdzić, zanim uznasz je za stracone.</p><h2>1. Czy na pewno wszystkie gniazda kluczy przepadły</h2><pre><code>cryptsetup luksDump /dev/sda2</code></pre><p>LUKS ma kilka gniazd. Bywa, że w jednym siedzi zapomniany plik klucza albo drugie hasło ustawione przy instalacji.</p><h2>2. Klucz powiązany z TPM</h2><pre><code>systemd-cryptenroll --tpm2-device=list
cryptsetup luksDump /dev/sda2 | grep -i tpm</code></pre><p>Jeśli klucz był zapieczętowany w module TPM, a przestał być wydawany po aktualizacji oprogramowania układowego — to nie utrata hasła, tylko zmienione pomiary rozruchu. Hasło awaryjne, jeśli istnieje, nadal działa.</p><h2>3. Kopia nagłówka</h2><pre><code>cryptsetup luksHeaderRestore /dev/sda2 --header-backup-file naglowek.img</code></pre><p>Uszkodzony nagłówek przy znanym haśle to jedyny przypadek, który naprawdę da się uratować — o ile kopia nagłówka istnieje.</p><h2>4. Klucz główny w pamięci</h2><p>Jeśli wolumen jest <strong>nadal odblokowany</strong>, klucz da się wyeksportować i zapisać:</p><pre><code>dmsetup table --showkeys /dev/mapper/root</code></pre><p>To działa wyłącznie przed wyłączeniem maszyny. Po restarcie klucz przepada.</p><h2>5. Odzyskiwanie hasła</h2><p>Jeśli pamiętasz część hasła, istnieją narzędzia próbujące warianty. Przy współczesnych ustawieniach LUKS jedna próba trwa ułamek sekundy z premedytacją — to celowe i sprawia, że przeszukanie ma sens tylko przy bardzo małej liczbie wariantów.</p><h2>6. Wniosek na przyszłość</h2><ul><li>Drugie hasło albo plik klucza w osobnym gnieździe, założone od razu.</li><li>Kopia nagłówka przechowywana osobno.</li><li>Hasło w menedżerze haseł, do którego masz dostęp awaryjny.</li><li>Kopia zapasowa danych niezależna od tego nośnika.</li></ul><h2>Czego ten materiał nie rozwiązuje</h2><p>Nie ma tylnej furtki i nie ma usługi, która „odzyska hasło do LUKS". Oferty takich usług przy poprawnie ustawionym szyfrowaniu są oszustwem. To jest cena, którą płaci się za to, że szyfrowanie działa.</p>`,
  },
  {
    kat: 'bezpieczenstwo',
    title: 'Konto u dostawcy zostało przejęte — co robić',
    excerpt: 'Kolejność odzyskiwania kontroli i miejsca, o których napastnicy pamiętają, a właściciele nie.',
    body: `<p>Przy przejętym koncie sama zmiana hasła nie wystarcza — napastnik zwykle zostawia sobie inne drogi powrotu.</p><h2>1. Odzyskanie kontroli</h2><ol><li>Zmień hasło.</li><li><strong>Unieważnij wszystkie aktywne sesje</strong> — bez tego napastnik pozostaje zalogowany mimo nowego hasła.</li><li>Włącz drugi składnik, jeśli go nie było.</li></ol><h2>2. Miejsca, o których się zapomina</h2><ul><li><strong>Reguły przekazywania poczty</strong> — kopia całej korespondencji na obcy adres. Najczęstszy i najtrudniejszy do zauważenia ślad.</li><li><strong>Adres zapasowy i numer telefonu</strong> do odzyskiwania konta — podmieniony oznacza, że napastnik odzyska konto po tobie.</li><li><strong>Klucze SSH i tokeny dostępu</strong> w serwisach z kodem.</li><li><strong>Autoryzowane aplikacje</strong> mające dostęp przez OAuth.</li><li><strong>Hasła aplikacji</strong> — działają z pominięciem drugiego składnika.</li><li><strong>Filtry i reguły</strong> ukrywające wiadomości, na przykład powiadomienia o zmianach.</li></ul><h2>3. Ustal zakres</h2><p>Historia logowań pokazuje, kiedy i skąd. Odpowiedz na pytanie, do czego to konto dawało dostęp: do repozytoriów z kodem, do serwerów, do panelu domeny, do płatności.</p><h2>4. Efekt domina</h2><p>Skrzynka pocztowa jest korzeniem — przez nią odzyskuje się wszystkie inne konta. Jeśli przejęto pocztę, każde konto powiązane z tym adresem trzeba traktować jako zagrożone.</p><h2>5. Sekrety, które tam były</h2><p>Klucze API, tokeny i hasła przesyłane albo przechowywane w tym koncie należy unieważnić. Kolejność: najpierw unieważnienie, potem cała reszta.</p><h2>6. Domena</h2><p>Jeśli przejęto konto u rejestratora, sprawdź serwery nazw i dane kontaktowe. Przejęta domena oznacza możliwość wystawienia certyfikatu na twoją nazwę i przejęcia poczty.</p><h2>Czego ten materiał nie rozwiązuje</h2><p>Klucze sprzętowe są jedynym mechanizmem odpornym na wyłudzenie hasła i kodu jednorazowego. Jeśli przejęcie nastąpiło przez podstawioną stronę logowania, to jest właściwy moment, żeby je wprowadzić — samo hasło i kod z aplikacji nie zapobiegną powtórce.</p>`,
  },
  {
    kat: 'system',
    title: 'Zapełniona partycja /boot blokuje aktualizacje',
    excerpt: 'Bezpieczne usuwanie starych jąder — i sprawdzenie, którego używasz.',
    body: `<p>Aktualizacja przerywa się z komunikatem o braku miejsca. Partycja rozruchowa bywa mała, a każde jądro zajmuje na niej kilkadziesiąt megabajtów.</p><h2>1. Stan i bieżące jądro</h2><pre><code>df -h /boot
uname -r
dpkg --list | grep -E "^ii\\s+linux-(image|headers)" | awk '{print $2}'</code></pre><p>Wynik <code>uname -r</code> to jądro, którego <strong>używasz teraz</strong> — tego nie wolno usunąć.</p><h2>2. Sprzątanie automatyczne</h2><pre><code>apt autoremove --purge</code></pre><p>To bezpieczna droga: menedżer pakietów sam zostawia bieżące i jedno poprzednie jądro. Warto zacząć od niej.</p><h2>3. Gdy brakuje miejsca nawet na to</h2><p>Sytuacja bez wyjścia: <code>apt</code> nie może dokończyć konfiguracji, bo nie ma miejsca, a miejsca nie zwolni bez dokończenia. Wtedy usuwamy jedno stare jądro ręcznie:</p><pre><code>ls /boot/vmlinuz-*
apt remove --purge linux-image-6.1.0-13-generic
apt -f install
apt autoremove --purge</code></pre><p>Wybieramy wersję najstarszą i <strong>różną</strong> od tej z <code>uname -r</code>.</p><h2>4. Czego nie robić</h2><p>Nie kasuj plików z <code>/boot</code> poleceniem <code>rm</code>. Menedżer pakietów nadal będzie uważał, że jądro jest zainstalowane, a konfiguracja programu rozruchowego rozjedzie się z rzeczywistością.</p><h2>5. Zapobieganie</h2><p>W konfiguracji nienadzorowanych aktualizacji:</p><pre><code>Unattended-Upgrade::Remove-Unused-Kernel-Packages "true";</code></pre><p>Bez tego partycja zapełni się ponownie za kilka miesięcy.</p><h2>6. Po sprzątaniu</h2><pre><code>update-grub
df -h /boot</code></pre><h2>Czego ten materiał nie rozwiązuje</h2><p>Partycji rozruchowej wielkości kilkudziesięciu megabajtów, utworzonej przy instalacji lata temu. Jej powiększenie wymaga operacji na układzie partycji i jest znacznie trudniejsze niż regularne sprzątanie.</p>`,
  },
  {
    kat: 'system',
    title: 'cannot set LC_ALL to default locale',
    excerpt: 'Ostrzeżenie o ustawieniach regionalnych, jego skutki i naprawa po obu stronach połączenia.',
    body: `<p>Ostrzeżenie sypie się przy każdym poleceniu. Wygląda niegroźnie, ale potrafi zmienić sortowanie, format liczb i obsługę polskich znaków w skryptach.</p><h2>1. Stan bieżący</h2><pre><code>locale
locale -a | head -20</code></pre><p>Komunikat oznacza zwykle, że zmienne wskazują na ustawienie, którego w systemie nie wygenerowano.</p><h2>2. Wygenerowanie</h2><pre><code>sed -i 's/# *pl_PL.UTF-8/pl_PL.UTF-8/; s/# *en_US.UTF-8/en_US.UTF-8/' /etc/locale.gen
locale-gen
update-locale LANG=pl_PL.UTF-8 LC_ALL=pl_PL.UTF-8</code></pre><p>Na systemach z rodziny RHEL:</p><pre><code>dnf install glibc-langpack-pl</code></pre><h2>3. Prawdziwa przyczyna przy połączeniu SSH</h2><p>Klient przesyła swoje ustawienia regionalne na serwer. Jeśli serwer ich nie ma, wita cię ostrzeżenie — mimo że lokalnie wszystko jest w porządku. Widać to po tym, że problem znika przy logowaniu z konsoli.</p><p>Rozwiązanie po stronie klienta, w <code>~/.ssh/config</code>:</p><pre><code>Host *
    SendEnv -LC_* -LANG</code></pre><p>Albo po stronie serwera — wygenerowanie brakujących ustawień.</p><h2>4. W kontenerach</h2><p>Obrazy minimalne nie mają ustawień regionalnych w ogóle. Jeśli aplikacja ich potrzebuje:</p><pre><code>ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8</code></pre><p>Ustawienie <code>C.UTF-8</code> jest tu zwykle lepszym wyborem niż język narodowy: obsługuje pełny zestaw znaków, a jednocześnie daje przewidywalne sortowanie, niezależne od reguł językowych.</p><h2>5. Skutki, o których warto wiedzieć</h2><ul><li>Sortowanie tekstu zależy od ustawień — te same dane ułożą się inaczej.</li><li>Format liczb zmiennoprzecinkowych: przecinek zamiast kropki potrafi zepsuć skrypty.</li><li>Format dat w wynikach poleceń.</li></ul><h2>Czego ten materiał nie rozwiązuje</h2><p>W skryptach i procesach automatycznych ustawienie <code>LC_ALL=C</code> jest bezpieczniejsze niż jakiekolwiek narodowe — wyniki poleceń przestają wtedy zależeć od konfiguracji maszyny, na której akurat działają.</p>`,
  },
  {
    kat: 'system',
    title: 'Wysokie iowait — co naprawdę je powoduje',
    excerpt: 'Odczytanie prawidłowego wskaźnika i znalezienie procesu obciążającego nośnik.',
    body: `<p>Obciążenie wysokie, procesor bezczynny. Kolumna oczekiwania na wejście-wyjście wskazuje, że zadania czekają na nośnik — ale nie mówi, na który ani przez kogo.</p><h2>1. Potwierdzenie</h2><pre><code>vmstat 1 10</code></pre><p>Kolumna <code>wa</code> wysoka przy niskim <code>us</code> potwierdza rozpoznanie. Warto pamiętać, że wartość ta jest liczona jako część czasu procesora — na maszynie z jednym rdzeniem wygląda dramatycznie, na maszynie z szesnastoma ta sama sytuacja daje niską liczbę.</p><h2>2. Które urządzenie</h2><pre><code>iostat -x 2 5</code></pre><p>Interesują nas kolumny z czasem obsługi żądań i wykorzystaniem urządzenia. Wysycenie bliskie stu procentom wskazuje wąskie gardło.</p><h2>3. Który proces</h2><pre><code>pidstat -d 2 5
iotop -oa</code></pre><h2>4. Presja na zasoby</h2><pre><code>cat /proc/pressure/io</code></pre><p>Ten wskaźnik mówi wprost, ile czasu zadania traciły na czekanie — bywa czytelniejszy niż wszystko powyżej.</p><h2>5. Częste przyczyny</h2><ul><li><strong>Brak pamięci</strong> — system wypycha strony na dysk. Objawia się jako obciążenie nośnika, choć przyczyną jest RAM.</li><li>Kopia zapasowa albo indeksowanie w tle.</li><li>Baza danych bez indeksu, czytająca całe tabele.</li><li>Odbudowa macierzy po wymianie dysku.</li><li>Padający dysk ponawiający odczyty — sprawdź S.M.A.R.T.</li><li>Dysk SSD po wyczerpaniu bufora szybkiego zapisu.</li></ul><h2>6. Rozróżnienie pamięci od nośnika</h2><pre><code>free -h
vmstat 1 | awk '{print $7, $8}'</code></pre><p>Ruch w kolumnach wymiany oznacza, że prawdziwym problemem jest pamięć, a nośnik tylko ponosi konsekwencje.</p><h2>Czego ten materiał nie rozwiązuje</h2><p>Nie mówi, czy obciążenie jest uzasadnione. Kopia zapasowa obciążająca dysk w nocy to normalna praca — problemem jest dopiero wtedy, gdy trwa do południa.</p>`,
  },
  {
    kat: 'system',
    title: 'Zegar systemu ucieka i psuje certyfikaty',
    excerpt: 'Synchronizacja czasu, sprzeczne usługi i maszyny bez baterii.',
    body: `<p>Rozjechany zegar psuje weryfikację certyfikatów, kody jednorazowe, harmonogramy zadań i korelację dzienników. Objawy bywają mylące i rzadko kojarzone z czasem.</p><h2>1. Stan</h2><pre><code>timedatectl status</code></pre><p>Interesują nas trzy wiersze: czy synchronizacja jest włączona, czy usługa działa i jaka jest strefa.</p><h2>2. Włączenie synchronizacji</h2><pre><code>timedatectl set-ntp true
systemctl status systemd-timesyncd</code></pre><h2>3. Dwie usługi naraz</h2><p>Częsta i trudna do zauważenia przyczyna: <code>systemd-timesyncd</code> działa równolegle z <code>chrony</code> albo <code>ntpd</code>. Obie przestawiają zegar i wchodzą sobie w drogę.</p><pre><code>systemctl is-active systemd-timesyncd chronyd ntpd</code></pre><p>Zostawiamy jedną, resztę wyłączamy.</p><h2>4. Weryfikacja z chrony</h2><pre><code>chronyc tracking
chronyc sources -v</code></pre><p>Wartość odchylenia rzędu sekund oznacza, że synchronizacja nie działa poprawnie.</p><h2>5. Maszyny bez baterii</h2><p>Komputery jednopłytkowe nie mają zegara podtrzymywanego bateryjnie — po odłączeniu zasilania startują z datą sprzed lat. Wszystkie połączenia HTTPS zawodzą wtedy z błędem certyfikatu „jeszcze nieważnego". Rozwiązaniem jest synchronizacja przy starcie, przed uruchomieniem usług sieciowych, albo dołożenie modułu zegara.</p><h2>6. Maszyny wirtualne</h2><p>Po wstrzymaniu i wznowieniu zegar potrafi przeskoczyć. Narzędzia gościa hipernadzorcy zwykle to naprawiają — jeśli są zainstalowane.</p><h2>7. Ustawienie ręczne w awarii</h2><pre><code>timedatectl set-ntp false
timedatectl set-time "2026-09-05 12:00:00"
timedatectl set-ntp true</code></pre><h2>Czego ten materiał nie rozwiązuje</h2><p>Zapory blokującej port 123 UDP — synchronizacja nie zadziała, choć wszystko jest poprawnie ustawione. W sieciach firmowych bywa wymagany wewnętrzny serwer czasu.</p>`,
  },
  {
    kat: 'system',
    title: 'dpkg przerwany w połowie — system pakietów zablokowany',
    excerpt: 'Wyjście z sytuacji, w której żadna operacja na pakietach się nie udaje.',
    body: `<p>Każde polecenie kończy się prośbą o dokończenie poprzedniej operacji albo błędem blokady. Przyczyną jest zwykle przerwana aktualizacja — brak miejsca, zamknięty terminal, restart w trakcie.</p><h2>1. Czy coś nadal działa</h2><pre><code>ps aux | grep -E "apt|dpkg" | grep -v grep
fuser -v /var/lib/dpkg/lock-frontend</code></pre><p><strong>Jeśli proces działa — poczekaj.</strong> Zabicie menedżera pakietów w trakcie pogłębia problem. To najczęstszy błąd w tej sytuacji: nagła aktualizacja w tle wygląda jak zawieszenie.</p><h2>2. Dokończenie</h2><pre><code>dpkg --configure -a</code></pre><p>To pierwsze polecenie do wypróbowania i zwykle wystarcza.</p><h2>3. Naprawa zależności</h2><pre><code>apt --fix-broken install</code></pre><h2>4. Gdy przyczyną był brak miejsca</h2><pre><code>df -h / /boot /var
apt clean
apt autoremove --purge</code></pre><p>Bez zwolnienia miejsca żadna z powyższych operacji się nie uda.</p><h2>5. Usunięcie blokad — ostatecznie</h2><pre><code>rm /var/lib/dpkg/lock-frontend /var/lib/dpkg/lock /var/cache/apt/archives/lock
dpkg --configure -a</code></pre><p>Wyłącznie po upewnieniu się, że żaden proces nie działa. Usunięcie blokady przy działającym procesie prowadzi do uszkodzenia bazy pakietów.</p><h2>6. Uszkodzona baza pakietów</h2><pre><code>ls -l /var/lib/dpkg/status /var/lib/dpkg/status-old
cp /var/lib/dpkg/status-old /var/lib/dpkg/status</code></pre><p>System trzyma kopię poprzedniego stanu. To ostatnia deska ratunku i warto przedtem zrobić kopię bieżącego pliku.</p><h2>7. Konkretny pakiet blokujący resztę</h2><pre><code>dpkg --remove --force-remove-reinstreq nazwa-pakietu</code></pre><h2>Czego ten materiał nie rozwiązuje</h2><p>Systemu, w którym przerwano aktualizację całej dystrybucji do nowej wersji. Tam stan pośredni bywa niespójny w sposób trudny do naprawienia, a rzetelną drogą jest odtworzenie z kopii zapasowej.</p>`,
  },
  {
    kat: 'kod',
    title: 'Aplikacja zwalnia z każdą godziną pracy',
    excerpt: 'Odróżnienie wycieku pamięci od wycieku zasobów i od problemu w bazie.',
    body: `<p>Po restarcie działa szybko, po kilku godzinach ledwo. Przyczyna jest w czymś, co narasta — trzeba ustalić w czym.</p><h2>1. Zmierz, zanim zaczniesz zgadywać</h2><pre><code>while :; do
  echo -n "$(date +%H:%M) "
  ps -o rss=,nlwp= -p &lt;pid&gt;
  ls /proc/&lt;pid&gt;/fd | wc -l
  sleep 300
done | tee narastanie.log</code></pre><p>Trzy liczby: pamięć, liczba wątków, liczba deskryptorów. Która rośnie, ta wskazuje kierunek.</p><h2>2. Rośnie pamięć</h2><p>Wyciek. Zrzut sterty po rozgrzaniu i po kilku godzinach, potem porównanie przyrostu. Typowe przyczyny to nasłuchiwacze zdarzeń dodawane bez usuwania, pamięć podręczna bez limitu i zegary, których nikt nie czyści.</p><h2>3. Rosną deskryptory</h2><pre><code>ls -l /proc/&lt;pid&gt;/fd | awk '{print $NF}' | sort | uniq -c | sort -rn | head</code></pre><p>Gniazda do bazy oznaczają nieoddawane połączenia, powtarzające się pliki — niezamykane uchwyty.</p><h2>4. Rośnie liczba wątków</h2><p>Zadania w tle, które nigdy się nie kończą, albo pula wątków bez górnego limitu.</p><h2>5. Nic nie rośnie, a jest wolniej</h2><p>Wtedy problem jest poza procesem — najczęściej w bazie:</p><pre><code>SELECT relname, n_live_tup, n_dead_tup,
       last_autovacuum, last_autoanalyze
FROM pg_stat_user_tables
ORDER BY n_dead_tup DESC LIMIT 10;</code></pre><p>Duża liczba martwych krotek przy dawnym czasie ostatniego sprzątania oznacza, że tabele puchną, a plany zapytań opierają się na nieaktualnych statystykach. To bardzo częsty powód aplikacji zwalniającej z dnia na dzień.</p><h2>6. Fragmentacja pamięci podręcznej</h2><p>Rosnący czas odpowiedzi przy stałej pamięci bywa też skutkiem rosnącego zbioru danych — zapytanie bez indeksu przy tysiącu wierszy jest szybkie, przy milionie nie.</p><h2>Czego ten materiał nie rozwiązuje</h2><p>Restart co noc ukrywa problem i bywa kuszący. Działa do dnia, w którym narastanie przyspieszy na tyle, że doba przestanie wystarczać — zwykle w najgorszym momencie.</p>`,
  },
  {
    kat: 'kod',
    title: 'Zapytanie działało szybko, nagle zwolniło stukrotnie',
    excerpt: 'Zmiana planu wykonania, nieaktualne statystyki i puchnące tabele.',
    body: `<p>Nic się nie zmieniło w kodzie, a to samo zapytanie trwa teraz sekundy zamiast milisekund. Przyczyna jest po stronie bazy.</p><h2>1. Zobacz plan</h2><pre><code>EXPLAIN (ANALYZE, BUFFERS) SELECT ...;</code></pre><p>Kluczowa jest rozbieżność między liczbą wierszy szacowaną a rzeczywistą. Różnica o rzędy wielkości oznacza, że planista podejmuje decyzje na podstawie nieprawdziwego obrazu danych.</p><h2>2. Statystyki</h2><pre><code>SELECT relname, last_analyze, last_autoanalyze, n_mod_since_analyze
FROM pg_stat_user_tables WHERE relname = 'tabela';</code></pre><pre><code>ANALYZE tabela;</code></pre><p>Po masowym imporcie albo dużej aktualizacji statystyki są nieaktualne, a mechanizm automatyczny nie zdążył. To najczęstsza przyczyna nagłej zmiany planu.</p><h2>3. Puchnięcie tabeli</h2><pre><code>SELECT relname, n_live_tup, n_dead_tup, last_autovacuum
FROM pg_stat_user_tables ORDER BY n_dead_tup DESC LIMIT 10;</code></pre><p>Martwe krotki zajmują miejsce i spowalniają przeglądanie. Długo otwarta transakcja blokuje ich sprzątanie — jedna zapomniana sesja potrafi zatrzymać ten mechanizm w całej bazie.</p><pre><code>SELECT pid, now() - xact_start AS trwa, state
FROM pg_stat_activity WHERE state != 'idle' ORDER BY trwa DESC;</code></pre><h2>4. Indeks przestał być używany</h2><pre><code>SELECT indexrelname, idx_scan FROM pg_stat_user_indexes WHERE relname = 'tabela';</code></pre><p>Zerowa liczba użyć przy istniejącym indeksie oznacza, że planista go pomija — zwykle przez nieaktualne statystyki albo dlatego, że warunek pasuje do zbyt dużej części tabeli.</p><h2>5. Zmiana rozkładu danych</h2><p>Zapytanie po statusie jest szybkie, dopóki wartości są rozłożone równomiernie. Gdy dziewięćdziesiąt procent wierszy dostaje jedną wartość, indeks przestaje mieć sens i baza słusznie wybiera pełne przejrzenie.</p><h2>6. Pamięć robocza</h2><p>Sortowanie zapisywane na dysk zamiast w pamięci potrafi zmienić czas o rząd wielkości. Widać to w planie jako operację zewnętrzną.</p><h2>Czego ten materiał nie rozwiązuje</h2><p>Nie da się „zamrozić" planu wykonania w typowej konfiguracji. Planista wybiera go od nowa przy każdym zapytaniu, opierając się na statystykach — dlatego to o nie trzeba dbać, a nie o sam plan.</p>`,
  },
];
