/** Poradniki problemowe — Kod. Tytuł niesie komunikat błędu, bo tak się szuka. */
export default [
  {
    kat: 'kod',
    title: 'Cannot connect to the Docker daemon — co to znaczy',
    excerpt: 'Trzy rozłączne przyczyny tego samego komunikatu i sposób odróżnienia ich w jednym poleceniu.',
    body: `<p>Komunikat brzmi tak samo w trzech zupełnie różnych sytuacjach. Kolejność sprawdzania rozstrzyga w kilkanaście sekund.</p><h2>1. Czy demon w ogóle działa</h2><pre><code>systemctl status docker
systemctl start docker</code></pre><p>Jeśli usługa nie wstaje, dalsze kroki nie mają sensu — przyczyna jest w jej dzienniku:</p><pre><code>journalctl -u docker -n 50 --no-pager</code></pre><h2>2. Czy masz prawo do gniazda</h2><p>Najczęstszy przypadek: demon działa, ale gniazdo należy do grupy <code>docker</code>, do której nie należysz.</p><pre><code>ls -l /var/run/docker.sock
id -nG</code></pre><pre><code>sudo usermod -aG docker $USER</code></pre><p><strong>Zmiana grup nie działa w bieżącej sesji.</strong> Trzeba się wylogować i zalogować ponownie albo otworzyć nową sesję — to źródło większości „dodałem się do grupy i nadal nie działa".</p><h2>3. Czy klient nie patrzy w złe miejsce</h2><pre><code>echo $DOCKER_HOST
docker context ls</code></pre><p>Ustawiony kontekst albo zmienna środowiskowa kieruje klienta na inny adres. Zdarza się po eksperymentach ze zdalnym demonem albo po instalacji Docker Desktop obok pakietu systemowego.</p><h2>4. Rozstrzygnięcie jednym poleceniem</h2><pre><code>sudo docker info</code></pre><p>Działa z <code>sudo</code>, nie działa bez — to uprawnienia. Nie działa w obu przypadkach — to demon albo adres.</p><h2>Uwaga o bezpieczeństwie</h2><p>Dodanie do grupy <code>docker</code> jest równoważne nadaniu praw roota: mając dostęp do gniazda, można podmontować cały system plików hosta w kontenerze. To nie jest „mniejsze uprawnienie" niż sudo, tylko takie samo, bez zapisu w dzienniku.</p><h2>Czego ten materiał nie rozwiązuje</h2><p>W trybie bezrootowym gniazdo leży w katalogu użytkownika i wymaga innej zmiennej środowiskowej. Jeśli instalowałeś Dockera w tym trybie, sprawdź <code>DOCKER_HOST</code> ustawiany przez skrypt instalacyjny.</p>`,
  },
  {
    kat: 'kod',
    title: 'Kontener działa lokalnie, nie działa na serwerze',
    excerpt: 'Najczęstsze przyczyny rozjazdu między maszyną deweloperską a produkcją, z architekturą procesora na czele.',
    body: `<p>Ten sam obraz, inne zachowanie. Przyczyn jest kilka i każda ma inny objaw.</p><h2>1. Architektura procesora</h2><p>Obraz zbudowany na komputerze z procesorem ARM nie uruchomi się na serwerze x86 i odwrotnie. Objaw: <code>exec format error</code>.</p><pre><code>docker image inspect obraz --format '{{.Architecture}}'
uname -m</code></pre><p>Rozwiązanie to budowanie wieloplatformowe:</p><pre><code>docker buildx build --platform linux/amd64,linux/arm64 -t obraz --push .</code></pre><h2>2. Plik .dockerignore albo jego brak</h2><p>Lokalnie działa, bo w katalogu leżą pliki, których nie ma w repozytorium — najczęściej <code>.env</code> i <code>node_modules</code>. Sprawdzenie, co naprawdę trafiło do obrazu:</p><pre><code>docker run --rm -it obraz ls -la /app</code></pre><h2>3. Zmienne środowiskowe</h2><pre><code>docker inspect kontener --format '{{json .Config.Env}}'
docker compose config</code></pre><h2>4. Pamięć</h2><p>Kontener zabity z kodem 137 to przekroczony limit pamięci, nie błąd aplikacji:</p><pre><code>docker inspect kontener --format '{{.State.OOMKilled}}'</code></pre><h2>5. Uprawnienia do zamontowanych katalogów</h2><p>Lokalnie katalog należy do ciebie, na serwerze do kogoś innego. Proces w kontenerze działający jako inny użytkownik nie zapisze niczego.</p><pre><code>docker run --rm -v /dane:/dane obraz id
ls -ln /dane</code></pre><h2>6. Wersja obrazu bazowego</h2><p>Etykieta <code>latest</code> na maszynie deweloperskiej i na serwerze potrafi wskazywać dwie różne wersje. To argument za przypinaniem konkretnych wersji.</p><h2>Czego ten materiał nie rozwiązuje</h2><p>Różnic w wydajności — serwer z wolniejszym dyskiem albo mniejszą liczbą rdzeni zachowa się inaczej pod obciążeniem, choć obraz jest identyczny.</p>`,
  },
  {
    kat: 'kod',
    title: 'EADDRINUSE — port zajęty przy starcie aplikacji',
    excerpt: 'Kiedy to druga kopia procesu, kiedy pozostałość po zamknięciu, a kiedy błąd w kodzie.',
    body: `<p>Komunikat mówi, że adres jest zajęty. Sprawdzamy przez kogo — i czy w ogóle przez kogokolwiek.</p><h2>1. Kto słucha</h2><pre><code>ss -tulpn | grep :3000</code></pre><p>Jest proces — sprawa jest prosta: zatrzymujemy go albo zmieniamy port.</p><h2>2. Nikt nie słucha, a port zajęty</h2><pre><code>ss -tan | grep :3000</code></pre><p>Połączenia w stanie <code>TIME_WAIT</code> to normalna pozostałość po zamkniętych połączeniach, trwająca zwykle około dwóch minut. Nie blokują one nasłuchu, o ile gniazdo ma ustawioną opcję ponownego użycia adresu — a większość bibliotek ustawia ją domyślnie.</p><h2>3. Prawdziwa przyczyna: dwa nasłuchy w kodzie</h2><p>Najczęstszy przypadek w praktyce: aplikacja woła nasłuch dwa razy — raz w module, raz w teście albo w podwójnie zaimportowanym pliku. Objawia się to natychmiastowym błędem przy starcie, bez żadnego innego procesu w systemie.</p><h2>4. Przeładowanie na gorąco</h2><p>Narzędzie obserwujące pliki potrafi wystartować nową kopię, zanim stara zwolni port. Wtedy pomaga opóźnienie restartu w konfiguracji narzędzia albo poprawna obsługa sygnału zakończenia w aplikacji.</p><h2>5. Zajęte przez systemd</h2><pre><code>systemctl status nazwa
systemctl list-sockets</code></pre><p>Aktywacja przez gniazdo sprawia, że port trzyma systemd, a nie sama usługa.</p><h2>6. Ostateczność</h2><pre><code>fuser -k 3000/tcp</code></pre><p>Zabija proces bez sprzątania po nim. To narzędzie na chwilę, nie sposób pracy.</p><h2>Czego ten materiał nie rozwiązuje</h2><p>Jeśli błąd wraca po każdym restarcie mimo braku innego procesu, przyczyna jest w kodzie i żadne polecenie systemowe jej nie usunie — trzeba znaleźć drugie wywołanie nasłuchu.</p>`,
  },
  {
    kat: 'kod',
    title: 'Too many open files — wyczerpane deskryptory',
    excerpt: 'Limit systemowy, limit usługi i wyciek w kodzie — trzy różne przyczyny tego samego błędu.',
    body: `<p>Błąd pojawia się zwykle po godzinach albo dniach pracy, pod obciążeniem. To rozróżnia wyciek od zbyt niskiego limitu.</p><h2>1. Ile deskryptorów trzyma proces</h2><pre><code>ls /proc/&lt;pid&gt;/fd | wc -l
cat /proc/&lt;pid&gt;/limits | grep 'open files'</code></pre><h2>2. Czy to wyciek</h2><pre><code>watch -n5 "ls /proc/&lt;pid&gt;/fd | wc -l"</code></pre><p>Liczba rosnąca bez opadania przy stałym obciążeniu to wyciek. Liczba stabilna, ale wysoka — to za niski limit.</p><h2>3. Co konkretnie jest otwarte</h2><pre><code>ls -l /proc/&lt;pid&gt;/fd | awk '{print $NF}' | sort | uniq -c | sort -rn | head</code></pre><p>To rozstrzyga najszybciej: tysiąc gniazd do bazy oznacza nieoddawane połączenia, tysiąc tych samych plików — niezamykane uchwyty w kodzie.</p><h2>4. Podniesienie limitu dla usługi</h2><p>Dla usług systemd wpisy w <code>limits.conf</code> <strong>nie obowiązują</strong>. Liczy się wyłącznie jednostka:</p><pre><code>[Service]
LimitNOFILE=65535</code></pre><pre><code>systemctl daemon-reload
systemctl restart nazwa</code></pre><h2>5. Limit dla powłoki</h2><pre><code>ulimit -n
ulimit -n 65535</code></pre><h2>6. Limit całego systemu</h2><pre><code>sysctl fs.file-nr
sysctl fs.file-max</code></pre><p>Pierwsza liczba to użyte, ostatnia to maksimum. Wyczerpanie limitu systemowego jest rzadkie i zwykle oznacza, że coś poszło bardzo źle.</p><h2>Czego ten materiał nie rozwiązuje</h2><p>Podniesienie limitu przy wycieku tylko przesuwa awarię w czasie — z godziny na dobę. Warto podnieść limit, żeby przetrwać do poprawki, ale nie zamiast niej.</p>`,
  },
  {
    kat: 'kod',
    title: 'Aplikacja zawiesza się pod obciążeniem, baza jest bezczynna',
    excerpt: 'Klasyczny objaw wyczerpanej puli połączeń i sposób potwierdzenia w minutę.',
    body: `<p>Objaw jest charakterystyczny: żądania przestają wracać, procesor bezczynny, baza obciążona w kilku procentach. To niemal zawsze pula połączeń.</p><h2>1. Potwierdzenie po stronie bazy</h2><pre><code>SELECT count(*), state FROM pg_stat_activity GROUP BY state;</code></pre><p>Duża liczba połączeń w stanie <code>idle in transaction</code> to rozstrzygnięcie: aplikacja otworzyła transakcje i ich nie zamknęła.</p><h2>2. Które to zapytania</h2><pre><code>SELECT pid, now() - xact_start AS trwa, state, query
FROM pg_stat_activity
WHERE state = 'idle in transaction'
ORDER BY trwa DESC;</code></pre><h2>3. Najczęstsze przyczyny w kodzie</h2><ul><li>Wyjątek wewnątrz transakcji bez wycofania w bloku obsługi.</li><li>Wywołanie zewnętrznej usługi z otwartą transakcją — jedno przekroczenie czasu blokuje połączenie na minuty.</li><li>Połączenie wypożyczone na czas obsługi żądania zamiast na czas zapytania.</li><li>Zapomniane zwolnienie połączenia w ścieżce błędu.</li></ul><h2>4. Zabezpieczenie po stronie bazy</h2><pre><code>ALTER SYSTEM SET idle_in_transaction_session_timeout = '30s';
SELECT pg_reload_conf();</code></pre><p>To nie naprawia kodu, ale sprawia, że jedno zapomniane połączenie nie zatrzymuje całej aplikacji.</p><h2>5. Rozmiar puli</h2><p>Więcej połączeń zwykle pogarsza sprawę: baza obsługuje zapytania ograniczoną liczbą rdzeni, a nadmiar zwiększa rywalizację. Jeśli podniesienie puli „pomogło", problem prawdopodobnie tylko się przesunął.</p><h2>6. Doraźne odblokowanie</h2><pre><code>SELECT pg_terminate_backend(pid) FROM pg_stat_activity
WHERE state = 'idle in transaction' AND now() - xact_start &gt; interval '5 min';</code></pre><h2>Czego ten materiał nie rozwiązuje</h2><p>Zabicie połączeń przywraca działanie na chwilę. Bez znalezienia ścieżki w kodzie, która nie oddaje połączenia, problem wróci przy najbliższym szczycie.</p>`,
  },
  {
    kat: 'kod',
    title: '413 Request Entity Too Large przy przesyłaniu pliku',
    excerpt: 'Limit bywa w trzech miejscach naraz — podniesienie jednego nic nie daje.',
    body: `<p>Błąd zwraca zwykle pośrednik, zanim żądanie w ogóle dotrze do aplikacji. Dlatego zmiana ustawień samej aplikacji nie pomaga.</p><h2>1. Kto zwraca błąd</h2><pre><code>curl -v -F "plik=@duzy.zip" https://example.com/upload 2&gt;&amp;1 | grep -i "server:\\|413"</code></pre><p>Nagłówek serwera w odpowiedzi wskazuje warstwę, która odrzuciła żądanie.</p><h2>2. nginx</h2><pre><code>client_max_body_size 50M;</code></pre><p>Domyślnie 1 MB. Dyrektywa musi znaleźć się w kontekście obejmującym daną trasę — wpisana w <code>http</code> obejmie wszystko, w <code>location</code> tylko tę ścieżkę.</p><pre><code>nginx -t &amp;&amp; systemctl reload nginx</code></pre><h2>3. Aplikacja</h2><p>Warstwy przetwarzające treść żądania mają własne limity, zwykle rzędu jednego do kilku megabajtów. W bibliotekach obsługujących formularze wieloczęściowe to osobne ustawienie niż limit treści JSON.</p><h2>4. Cloudflare i podobni pośrednicy</h2><p>Sieci dostarczania treści mają własny limit rozmiaru żądania, zależny od planu — i nie da się go podnieść po stronie serwera. To najczęstsza przyczyna sytuacji „podniosłem wszystko, nadal 413".</p><h2>5. Kontrola całej ścieżki</h2><p>Sprawdzamy z pominięciem pośredników, wprost na serwer:</p><pre><code>curl -v -F "plik=@duzy.zip" http://127.0.0.1:3000/upload</code></pre><p>Działa lokalnie, nie działa przez domenę — limit jest w pośredniku.</p><h2>Właściwe rozwiązanie przy dużych plikach</h2><p>Przesyłanie kilkusetmegabajtowych plików przez zwykłe żądanie jest kruche: jedno zerwanie połączenia zaczyna wszystko od nowa. Rozsądniejsze jest przesyłanie w kawałkach albo bezpośrednio do magazynu obiektów przez podpisany adres, z pominięciem własnego serwera.</p><h2>Czego ten materiał nie rozwiązuje</h2><p>Limitu czasu żądania. Plik może się zmieścić w limicie rozmiaru i mimo to przekroczyć czas — to osobne ustawienie i osobny komunikat.</p>`,
  },
  {
    kat: 'kod',
    title: 'Zmienna z pliku .env nie działa po zbudowaniu aplikacji',
    excerpt: 'Różnica między zmienną czytaną w czasie działania a wstawianą przy budowaniu.',
    body: `<p>To nie jest błąd konfiguracji, tylko nieporozumienie co do momentu, w którym zmienna jest odczytywana.</p><h2>1. Dwa różne momenty</h2><ul><li><strong>Czas działania</strong> — kod serwera czyta zmienną przy każdym uruchomieniu. Zmiana w pliku i restart wystarczą.</li><li><strong>Czas budowania</strong> — narzędzie wstawia wartość <em>do kodu</em>. Po zbudowaniu jest tam napis, nie odwołanie do zmiennej.</li></ul><h2>2. Jak rozpoznać</h2><p>Zmienne trafiające do przeglądarki mają w większości narzędzi przedrostek — <code>NEXT_PUBLIC_</code>, <code>VITE_</code>, <code>REACT_APP_</code>. Każda z nich jest wstawiana przy budowaniu. Zmiana po zbudowaniu nie daje nic.</p><pre><code>grep -r "wartosc-ktorej-szukam" .next/ dist/ build/ 2&gt;/dev/null | head</code></pre><p>Znaleziona w plikach wynikowych potwierdza, że została wstawiona na stałe.</p><h2>3. Wniosek dla obrazów kontenerów</h2><p>Obraz zbudowany z jednym adresem API nie da się przestawić zmienną przy uruchomieniu. Ten sam obraz nie pojedzie więc na środowisko testowe i produkcyjne — trzeba albo budować osobno, albo pobierać konfigurację w czasie działania.</p><h2>4. Kolejność źródeł</h2><p>Zmienna ustawiona w powłoce zwykle przesłania plik, bo biblioteki wczytujące <code>.env</code> domyślnie nie nadpisują istniejących wartości. Rozstrzyga:</p><pre><code>docker compose config
printenv | grep NAZWA</code></pre><h2>5. Konfiguracja w czasie działania</h2><p>Jeśli ten sam obraz ma działać w kilku środowiskach, adres API pobiera się z własnego punktu końcowego przy starcie aplikacji w przeglądarce, zamiast wstawiać go przy budowaniu.</p><h2>Czego ten materiał nie rozwiązuje</h2><p>Sekret wstawiony przy budowaniu zostaje w plikach wynikowych i w warstwach obrazu na zawsze. Jeśli tak trafił tam klucz, samo przebudowanie nic nie da — trzeba go unieważnić.</p>`,
  },
  {
    kat: 'kod',
    title: 'Blocked by CORS policy mimo poprawnych nagłówków',
    excerpt: 'Przypadki, w których nagłówki są dobre, a przeglądarka i tak odmawia.',
    body: `<p>Gdy nagłówki wyglądają poprawnie, przyczyna jest zwykle w jednym z poniższych miejsc.</p><h2>1. Zapytanie wstępne zwraca błąd</h2><pre><code>curl -i -X OPTIONS https://api.example.com/zasob \\
  -H "Origin: https://app.example.com" \\
  -H "Access-Control-Request-Method: POST" \\
  -H "Access-Control-Request-Headers: content-type"</code></pre><p>Musi wrócić 200 lub 204 <strong>z nagłówkami CORS</strong>. Bardzo częsty błąd: trasa obsługuje tylko POST, a metoda OPTIONS trafia w 404 albo w warstwę uwierzytelniania i dostaje 401.</p><h2>2. Uwierzytelnianie przed CORS</h2><p>Jeśli warstwa sprawdzająca token stoi przed obsługą CORS, zapytanie wstępne — wysyłane <em>bez</em> danych uwierzytelniających — zostanie odrzucone. Obsługa CORS musi być pierwsza.</p><h2>3. Ciasteczka i gwiazdka</h2><p>Przy żądaniach z danymi uwierzytelniającymi <code>Access-Control-Allow-Origin</code> nie może być gwiazdką — wymagane jest konkretne pochodzenie, plus <code>Access-Control-Allow-Credentials: true</code>. To ograniczenie jest zamierzone i nie da się go obejść.</p><h2>4. Błąd 500 wygląda jak CORS</h2><p>Odpowiedź z błędem serwera zwykle nie przechodzi przez warstwę dodającą nagłówki. Przeglądarka pokazuje wtedy komunikat o CORS, choć prawdziwym problemem jest awaria po stronie serwera. Rozstrzyga zakładka sieci: kod odpowiedzi 500 przy komunikacie o CORS oznacza, że szukamy w złym miejscu.</p><h2>5. Podwójne nagłówki</h2><pre><code>curl -sI https://api.example.com/zasob -H "Origin: https://app.example.com" | grep -i access-control</code></pre><p>Dwa nagłówki <code>Access-Control-Allow-Origin</code> — dodane przez aplikację i przez nginx — są dla przeglądarki błędem. Dodaje je tylko jedna warstwa.</p><h2>6. Przekierowanie</h2><p>Przekierowanie w trakcie żądania z innego pochodzenia bywa blokowane. Sprawdź, czy adres nie kończy się przekierowaniem z braku ukośnika na końcu.</p><h2>Czego ten materiał nie rozwiązuje</h2><p>CORS nie chroni serwera — klient inny niż przeglądarka ignoruje te nagłówki. Wyłączenie CORS „żeby działało" niczego nie otwiera atakującemu, ale też niczego nie naprawia po stronie bezpieczeństwa.</p>`,
  },
  {
    kat: 'kod',
    title: 'Sesja gubi się po wdrożeniu za odwrotnym proxy',
    excerpt: 'Ciasteczka, protokół i domena — trzy rzeczy, które zmienia postawienie proxy przed aplikacją.',
    body: `<p>Aplikacja działała bezpośrednio, po dołożeniu proxy użytkownicy wylatują po każdym żądaniu. Przyczyna jest zwykle w jednej z trzech rzeczy.</p><h2>1. Aplikacja nie wie, że jest za proxy</h2><p>Widzi połączenie po HTTP i adres lokalny. Wystawia więc ciasteczko bez atrybutu bezpiecznego albo przekierowuje na adres z <code>http://</code>. Większość frameworków ma na to jedno ustawienie zaufania do pośrednika — bez niego reszta konfiguracji nie zadziała.</p><h2>2. Brak przekazania protokołu</h2><pre><code>proxy_set_header X-Forwarded-Proto $scheme;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header Host $host;</code></pre><p>Bez pierwszej linii aplikacja generuje odnośniki po HTTP, przeglądarka je blokuje albo wpada w pętlę przekierowań.</p><h2>3. Ciasteczko z atrybutem Secure po HTTP</h2><p>Ciasteczko oznaczone jako bezpieczne nie zostanie zapisane na połączeniu nieszyfrowanym. Jeśli między proxy a aplikacją jest HTTP, a aplikacja nie wie o zewnętrznym HTTPS, ciasteczko ginie po drodze.</p><h2>4. SameSite przy logowaniu przez zewnętrznego dostawcę</h2><p>Powrót z zewnętrznego dostawcy tożsamości to żądanie z innej witryny. Ciasteczko z domyślną wartością <code>Lax</code> nie zostanie odesłane, jeśli powrót następuje metodą POST. Wtedy potrzebne jest <code>SameSite=None; Secure</code>.</p><h2>5. Domena ciasteczka</h2><p>Ciasteczko wystawione na <code>app.example.com</code> nie pojedzie na <code>example.com</code> i odwrotnie. Przekierowanie między wersją z <code>www</code> i bez potrafi zgubić sesję w jednym kroku.</p><h2>6. Kilka instancji aplikacji</h2><p>Sesja trzymana w pamięci procesu działa, dopóki instancja jest jedna. Za proxy rozdzielającym ruch użytkownik trafia raz na jedną, raz na drugą. Sesja musi być we wspólnym magazynie.</p><h2>Diagnostyka</h2><pre><code>curl -i https://app.example.com/login | grep -i set-cookie</code></pre><h2>Czego ten materiał nie rozwiązuje</h2><p>Sesji gubionych z powodu wygasania po stronie magazynu — to osobna sprawa i widać ją po tym, że problem dotyczy wszystkich naraz o tej samej porze.</p>`,
  },
  {
    kat: 'kod',
    title: 'unable to get local issuer certificate',
    excerpt: 'Błąd weryfikacji certyfikatu w curl, Node i Pythonie — i dlaczego wyłączenie sprawdzania jest złą odpowiedzią.',
    body: `<p>Komunikat znaczy: nie udało się zbudować łańcucha zaufania do certyfikatu serwera. Przyczyna leży po jednej z trzech stron.</p><h2>1. Serwer nie wysyła certyfikatów pośrednich</h2><pre><code>openssl s_client -connect example.com:443 -servername example.com -showcerts &lt; /dev/null</code></pre><p>Jeden certyfikat w odpowiedzi zamiast łańcucha to najczęstsza przyczyna. Przeglądarki bywają wyrozumiałe, bo mają pośrednie w pamięci z wcześniejszych wizyt — narzędzia wiersza poleceń nie. Naprawa jest po stronie serwera: wskazać plik z pełnym łańcuchem.</p><h2>2. Brak certyfikatów głównych w systemie</h2><p>Typowe w minimalnych obrazach kontenerów:</p><pre><code>apt install ca-certificates &amp;&amp; update-ca-certificates
apk add ca-certificates</code></pre><h2>3. Podmiana ruchu przez pośrednika</h2><p>W sieci firmowej ruch bywa rozszywany przez urządzenie brzegowe, które podstawia własny certyfikat. Trzeba dodać jego certyfikat główny do zaufanych:</p><pre><code>cp firmowy.crt /usr/local/share/ca-certificates/
update-ca-certificates</code></pre><h2>4. Środowiska z własnym magazynem</h2><p>Node i Python nie zawsze korzystają z magazynu systemowego:</p><pre><code>NODE_EXTRA_CA_CERTS=/sciezka/do/glownego.pem node app.js
export REQUESTS_CA_BUNDLE=/sciezka/do/glownego.pem
export SSL_CERT_FILE=/sciezka/do/glownego.pem</code></pre><h2>5. Zegar</h2><p>Certyfikat ważny „od" daty w przyszłości jest nieważny. Maszyna z rozjechanym zegarem — częste na komputerach jednopłytkowych bez baterii — daje ten sam objaw.</p><pre><code>timedatectl status</code></pre><h2>Czego robić nie należy</h2><p>Wyłączenie weryfikacji (<code>curl -k</code>, <code>rejectUnauthorized: false</code>, <code>verify=False</code>) usuwa komunikat i całą ochronę — połączenie staje się podatne na podstawienie. To akceptowalne wyłącznie w doraźnej diagnostyce, żeby potwierdzić, że problem jest właśnie w certyfikacie.</p><h2>Czego ten materiał nie rozwiązuje</h2><p>Certyfikatu naprawdę nieważnego — wygasłego albo wystawionego na inną nazwę. Wtedy komunikat jest inny i trzeba naprawić certyfikat, a nie zaufanie.</p>`,
  },
  {
    kat: 'kod',
    title: 'Proces zabity z kodem 137 — nie jest to błąd aplikacji',
    excerpt: 'Skąd się bierze ten kod, jak potwierdzić przyczynę i co z nią zrobić.',
    body: `<p>Kod 137 to 128 plus 9, czyli zakończenie sygnałem numer dziewięć. Prawie zawsze oznacza przekroczenie limitu pamięci, a nie awarię programu.</p><h2>1. Potwierdzenie w kontenerze</h2><pre><code>docker inspect kontener --format '{{.State.OOMKilled}} {{.State.ExitCode}}'</code></pre><p>Wartość <code>true</code> rozstrzyga sprawę.</p><h2>2. Potwierdzenie na maszynie</h2><pre><code>journalctl -k | grep -i "killed process"
dmesg -T | grep -i "out of memory"</code></pre><h2>3. Jaki jest limit</h2><pre><code>docker inspect kontener --format '{{.HostConfig.Memory}}'
systemctl show nazwa -p MemoryMax</code></pre><p>Wartość zero oznacza brak limitu kontenera — wtedy zadziałał mechanizm całego systemu i ofiarą padł największy proces, niekoniecznie winny.</p><h2>4. Co robić</h2><ul><li>Podnieść limit, jeśli aplikacja realnie tyle potrzebuje.</li><li>Znaleźć wyciek, jeśli zużycie rośnie bez opadania.</li><li>Ograniczyć równoległość — najczęstsza przyczyna nagłych skoków to przetwarzanie zbyt wielu rzeczy naraz.</li></ul><h2>5. Uwaga o maszynach wirtualnych języków</h2><p>Środowisko uruchomieniowe nie zawsze widzi limit kontenera i dobiera rozmiar sterty na podstawie pamięci całego hosta. Skutek: sprząta pamięć za późno i zostaje zabite, zanim uzna, że ma za mało miejsca. Rozwiązaniem jest jawne ustawienie limitu sterty poniżej limitu kontenera.</p><pre><code>node --max-old-space-size=768 app.js   # przy limicie 1 GB</code></pre><h2>6. Kod 143</h2><p>Dla porządku: 143 to sygnał zakończenia, czyli zwykłe zatrzymanie usługi. To nie jest awaria.</p><h2>Czego ten materiał nie rozwiązuje</h2><p>Podniesienie limitu przy wycieku przesuwa awarię, nie usuwa jej. Rosnące zużycie przy stałym obciążeniu wymaga zrzutu sterty i analizy, a nie większego limitu.</p>`,
  },
  {
    kat: 'kod',
    title: 'Data w bazie różni się od daty w aplikacji',
    excerpt: 'Strefy czasowe na czterech poziomach naraz i sposób, żeby przestały się rozjeżdżać.',
    body: `<p>Przesunięcie o godzinę lub dwie, zmienne w zależności od pory roku, to niemal zawsze strefy czasowe — nie błąd zapisu.</p><h2>1. Cztery miejsca, w których strefa ma znaczenie</h2><ol><li>Zegar systemu, na którym działa baza.</li><li>Ustawienie strefy w samej bazie.</li><li>Strefa w połączeniu z aplikacji.</li><li>Strefa przeglądarki użytkownika.</li></ol><h2>2. Sprawdzenie</h2><pre><code>timedatectl status
psql -c "SHOW timezone; SELECT now(), now() AT TIME ZONE 'UTC';"
node -e "console.log(Intl.DateTimeFormat().resolvedOptions().timeZone, new Date().toISOString())"</code></pre><h2>3. Typ kolumny rozstrzyga</h2><p>W PostgreSQL <code>timestamptz</code> zapisuje chwilę w czasie i przelicza ją na strefę odbiorcy. <code>timestamp</code> bez strefy zapisuje ścianę zegara i nie wie, w jakiej strefie ją odczytano. Do znaczników zdarzeń używa się pierwszego — drugi jest źródłem tej klasy błędów.</p><pre><code>ALTER TABLE zdarzenia ALTER COLUMN utworzono TYPE timestamptz USING utworzono AT TIME ZONE 'Europe/Warsaw';</code></pre><p>Konwersja wymaga podania strefy, w której zapisano dotychczasowe wartości — jeśli była niespójna, część danych będzie przesunięta i nie da się tego odróżnić po fakcie.</p><h2>4. Zasada, która usuwa problem</h2><p>Wszystko po stronie serwera w czasie uniwersalnym: zegar maszyny, strefa bazy, znaczniki w aplikacji. Przeliczenie na czas lokalny wykonuje się <strong>wyłącznie przy wyświetlaniu</strong>, w przeglądarce, znając strefę użytkownika.</p><h2>5. Czas letni</h2><p>Przesunięcie stałe o godzinę wskazuje na strefę. Przesunięcie zmieniające się dwa razy w roku to czas letni — i dowód, że gdzieś zapisujemy czas lokalny zamiast uniwersalnego.</p><h2>Czego ten materiał nie rozwiązuje</h2><p>Dat, które mają być czasem lokalnym z definicji — godziny otwarcia sklepu czy data urodzenia nie są chwilą w czasie i przeliczanie ich na strefę użytkownika jest błędem. Te zostają bez strefy, świadomie.</p>`,
  },
  {
    kat: 'kod',
    title: 'duplicate key value violates unique constraint po imporcie danych',
    excerpt: 'Sekwencja rozjechana z zawartością tabeli — typowy skutek wgrania danych z jawnymi identyfikatorami.',
    body: `<p>Objaw: aplikacja działała, po imporcie danych każde dodanie nowego wiersza kończy się błędem unikalności klucza głównego.</p><h2>1. Przyczyna</h2><p>Kolumna z automatycznym numerowaniem bierze wartości z sekwencji. Import wstawiający jawne identyfikatory <strong>nie przesuwa</strong> sekwencji — ta nadal wskazuje na wartość sprzed importu. Pierwsze kolejne wstawienie próbuje użyć numeru, który już istnieje.</p><h2>2. Potwierdzenie</h2><pre><code>SELECT last_value FROM uzytkownicy_id_seq;
SELECT max(id) FROM uzytkownicy;</code></pre><p>Wartość sekwencji niższa od największego identyfikatora potwierdza rozpoznanie.</p><h2>3. Naprawa</h2><pre><code>SELECT setval(
  pg_get_serial_sequence('uzytkownicy', 'id'),
  COALESCE((SELECT max(id) FROM uzytkownicy), 0) + 1,
  false
);</code></pre><p>Funkcja <code>pg_get_serial_sequence</code> jest tu lepsza niż wpisana z ręki nazwa — ta bywa inna, niż się wydaje, zwłaszcza po zmianach nazw tabel.</p><h2>4. Wszystkie tabele naraz</h2><pre><code>SELECT 'SELECT setval(pg_get_serial_sequence(''' || table_name || ''', ''id''), COALESCE((SELECT max(id) FROM ' || table_name || '), 0) + 1, false);'
FROM information_schema.columns
WHERE column_default LIKE 'nextval%' AND table_schema = 'public';</code></pre><p>Zapytanie generuje polecenia, które następnie wykonujemy — po przejrzeniu.</p><h2>5. Jak tego uniknąć</h2><p>Zrzut wykonany narzędziem bazy (<code>pg_dump</code>) zawiera ustawienie sekwencji i problem nie występuje. Pojawia się przy imporcie z pliku CSV, z innej bazy albo z ręcznie pisanych poleceń wstawiania.</p><h2>6. Inna możliwa przyczyna</h2><p>Ten sam komunikat pojawia się przy prawdziwym duplikacie w danych — wtedy sekwencja jest w porządku, a konflikt dotyczy innej kolumny z ograniczeniem unikalności. Nazwa ograniczenia w treści błędu rozstrzyga, o które chodzi.</p><h2>Czego ten materiał nie rozwiązuje</h2><p>Wyścigu przy równoległym wstawianiu z jawnym identyfikatorem — tam rozwiązaniem jest oddanie numeracji bazie, a nie poprawianie sekwencji po fakcie.</p>`,
  },
  {
    kat: 'kod',
    title: 'Migracja bazy stoi i blokuje wszystkie zapytania',
    excerpt: 'Kolejka blokad, jej rozpoznanie i wyjście z sytuacji bez utraty danych.',
    body: `<p>Migracja czeka na blokadę, a za nią ustawiają się wszystkie inne zapytania. Aplikacja staje, choć baza nie robi nic.</p><h2>1. Kto na kogo czeka</h2><pre><code>SELECT blocked.pid AS czeka, blocking.pid AS blokuje,
       blocked.query AS zapytanie_czekajace,
       blocking.query AS zapytanie_blokujace
FROM pg_stat_activity blocked
JOIN pg_stat_activity blocking ON blocking.pid = ANY(pg_blocking_pids(blocked.pid));</code></pre><p>To pokazuje realny łańcuch oczekiwania, a nie tylko listę aktywnych zapytań.</p><h2>2. Typowy sprawca</h2><p>Bardzo często blokuje długo otwarta transakcja w stanie bezczynności — na przykład sesja narzędzia graficznego, w której ktoś zaczął transakcję i poszedł na obiad.</p><h2>3. Odblokowanie</h2><pre><code>SELECT pg_cancel_backend(&lt;pid&gt;);
SELECT pg_terminate_backend(&lt;pid&gt;);</code></pre><p>Pierwsze przerywa zapytanie, drugie zrywa całe połączenie. Zaczynamy od pierwszego.</p><h2>4. Zabezpieczenie na przyszłość</h2><pre><code>SET lock_timeout = '3s';
SET statement_timeout = '30s';</code></pre><p>Migracja, która poddaje się po trzech sekundach, jest lepsza od migracji ustawiającej za sobą kolejkę. Powtórzenie jej jest tanie; odblokowywanie produkcji nie.</p><h2>5. Operacje, które biorą ciężką blokadę</h2><ul><li>Dodanie kolumny z wartością domyślną w starszych wersjach silnika.</li><li>Zmiana typu kolumny.</li><li>Dodanie ograniczenia bez klauzuli odraczającej sprawdzenie.</li><li>Zwykłe <code>CREATE INDEX</code> — dlatego na produkcji używa się wariantu współbieżnego.</li></ul><h2>6. Zasada</h2><p>Migrację uruchamiamy najpierw na kopii bazy produkcyjnej i mierzymy czas. Wynik z bazy deweloperskiej z tysiącem wierszy nie mówi nic o tabeli z dziesięcioma milionami.</p><h2>Czego ten materiał nie rozwiązuje</h2><p>Migracji przerwanej w połowie. Część silników wykonuje zmiany schematu transakcyjnie i wycofa je same; przy narzędziach, które tego nie robią, trzeba ręcznie ustalić, co zdążyło się wykonać.</p>`,
  },
  {
    kat: 'kod',
    title: 'Testy przechodzą lokalnie, wywalają się w procesie CI',
    excerpt: 'Cztery przyczyny rozjazdu, od kolejności testów po strefę czasową maszyny budującej.',
    body: `<p>Rozjazd między maszyną deweloperską a procesem ciągłej integracji ma zwykle jedną z poniższych przyczyn.</p><h2>1. Kolejność i stan współdzielony</h2><p>Lokalnie testy uruchamiane pojedynczo, w CI wszystkie naraz i często równolegle. Test zależny od danych zostawionych przez inny albo od kolejności wykonania wywali się dopiero tam.</p><pre><code>npm test -- --runInBand      # bez równoległości
npm test -- --randomize      # losowa kolejność, jeśli narzędzie umie</code></pre><p>Uruchomienie lokalnie w losowej kolejności odtwarza problem najszybciej.</p><h2>2. Zależności z innych wersji</h2><pre><code>npm ci</code></pre><p>Lokalnie masz zainstalowane to, co narosło przez miesiące. CI instaluje z pliku blokady. Rozjazd między deklaracją a plikiem blokady daje różne wersje bibliotek.</p><h2>3. Strefa czasowa i język</h2><p>Maszyna budująca pracuje zwykle w czasie uniwersalnym i z angielskim ustawieniem regionalnym. Testy porównujące sformatowaną datę albo posortowany tekst rozjadą się natychmiast. Ustawienie tego jawnie w konfiguracji usuwa całą klasę problemów:</p><pre><code>env:
  TZ: UTC
  LANG: C.UTF-8</code></pre><h2>4. Czas i zasoby</h2><p>Maszyna budująca jest zwykle wolniejsza. Testy z zaszytym czekaniem na stałą liczbę milisekund zaczynają migotać. Rozwiązaniem jest czekanie na warunek, nie na czas.</p><h2>5. Wielkość liter w nazwach plików</h2><p>System plików na macOS domyślnie ich nie rozróżnia, na maszynie budującej z Linuksem — rozróżnia. Import z inną wielkością liter działa lokalnie i wywala się w CI.</p><h2>6. Odtworzenie warunków u siebie</h2><pre><code>docker run --rm -it -v "$PWD":/app -w /app -e TZ=UTC node:22 sh -lc "npm ci &amp;&amp; npm test"</code></pre><h2>Czego ten materiał nie rozwiązuje</h2><p>Testów migoczących z powodu prawdziwego wyścigu w kodzie. Te wywalają się także lokalnie, tylko rzadziej — i to nie CI jest wtedy problemem.</p>`,
  },
];
