/** Poradniki problemowe — System i Sieć. */
export default [
  {
    kat: 'system',
    title: 'No space left on device mimo wolnego miejsca na dysku',
    excerpt: 'Trzy przyczyny tego samego komunikatu, gdy df pokazuje zapas.',
    body: `<p>Komunikat jest jednoznaczny, a <code>df -h</code> pokazuje wolne gigabajty. Przyczyna jest wtedy jedna z trzech.</p><h2>1. Wyczerpane i-węzły</h2><pre><code>df -i</code></pre><p>Sto procent w kolumnie użycia oznacza brak wolnych i-węzłów. Miejsce jest, ale nie ma gdzie zapisać metadanych kolejnego pliku. Typowe przy milionach malutkich plików — cache, kolejka poczty, katalog sesji.</p><pre><code>for d in /var/*; do echo -n "$d "; find "$d" -xdev -type f 2&gt;/dev/null | wc -l; done | sort -k2 -n | tail</code></pre><h2>2. Skasowany plik trzymany otwarty</h2><pre><code>lsof +L1</code></pre><p>Proces pisze do pliku, który ktoś usunął. Miejsce wróci dopiero po zamknięciu deskryptora — czyli po restarcie tej usługi. Klasyczny przypadek: skasowany dziennik, do którego demon nadal pisze.</p><pre><code>systemctl restart nazwa_uslugi</code></pre><h2>3. Miejsce zarezerwowane dla roota</h2><p>Systemy plików z rodziny ext rezerwują domyślnie pięć procent pojemności dla roota. Zwykły użytkownik zobaczy brak miejsca, gdy <code>df</code> pokazuje jeszcze kilka procent wolnych.</p><pre><code>tune2fs -l /dev/sda1 | grep -i "reserved block count"
tune2fs -m 1 /dev/sda1</code></pre><p>Na partycji z danymi rezerwa rzędu jednego procenta wystarczy; na partycji systemowej warto ją zostawić.</p><h2>4. Zły system plików</h2><p>Prosty, ale częsty błąd: sprawdzamy <code>/</code>, a zapis idzie na osobną partycję albo do zamontowanego zasobu.</p><pre><code>df -h /sciezka/gdzie/zapisujemy</code></pre><h2>5. Przy systemach z kopiowaniem przy zapisie</h2><p>Na Btrfs i ZFS miejsce potrafi zajmować migawka, o której nikt nie pamięta. <code>df</code> pokazuje wtedy stan, którego nie da się wytłumaczyć zawartością katalogów.</p><pre><code>btrfs filesystem usage /
zfs list -t snapshot</code></pre><h2>Czego ten materiał nie rozwiązuje</h2><p>Nie mówi, co wolno skasować. Zanim usuniesz cokolwiek z <code>/var/lib</code>, ustal, która usługa z tego korzysta — odzyskanie miejsca kosztem bazy danych jest gorszym problemem niż pełny dysk.</p>`,
  },
  {
    kat: 'system',
    title: 'System nie wstaje po aktualizacji jądra',
    excerpt: 'Uruchomienie ze starszego jądra, ustalenie przyczyny i trwała naprawa.',
    body: `<p>Aktualizacja przeszła, restart zakończył się powłoką awaryjną albo czarnym ekranem. Poprzednie jądro zwykle nadal jest zainstalowane.</p><h2>1. Uruchomienie ze starszego jądra</h2><p>W menu programu rozruchowego wybieramy „Advanced options" i poprzednią wersję. Jeśli menu się nie pokazuje, przytrzymujemy klawisz Shift przy starcie albo naciskamy Esc.</p><h2>2. Co się stało</h2><pre><code>journalctl -k -b -1 -p err --no-pager | tail -40</code></pre><p>Dziennik z poprzedniego, nieudanego rozruchu jest tu najważniejszym źródłem.</p><h2>3. Najczęstsze przyczyny</h2><ul><li><strong>Moduł spoza jądra</strong> — sterownik karty graficznej albo systemu plików nie skompilował się dla nowej wersji.</li><li><strong>Niepełny initramfs</strong> — zabrakło miejsca na partycji rozruchowej w trakcie aktualizacji.</li><li><strong>Zmieniony UUID</strong> wolumenu po operacjach na dyskach.</li><li><strong>Bezpieczny rozruch</strong> odrzucający niepodpisany moduł.</li></ul><h2>4. Partycja rozruchowa</h2><pre><code>df -h /boot</code></pre><p>Pełna partycja to najczęstsza pojedyncza przyczyna. Aktualizacja kończy się wtedy pozornie pomyślnie, ale obraz initramfs jest obcięty.</p><pre><code>apt autoremove --purge
update-initramfs -u -k all
update-grub</code></pre><h2>5. Moduły spoza jądra</h2><pre><code>dkms status</code></pre><p>Status inny niż „installed" dla nowej wersji jądra wskazuje winowajcę.</p><h2>6. Zatrzymanie na stałe przy działającym jądrze</h2><pre><code>apt-mark hold linux-image-generic</code></pre><p>To rozwiązanie na chwilę, nie na zawsze — jądro bez aktualizacji przestaje dostawać poprawki bezpieczeństwa.</p><h2>Czego ten materiał nie rozwiązuje</h2><p>Sytuacji, w której stare jądro też zniknęło — przy skonfigurowanym automatycznym usuwaniu poprzednich wersji. Wtedy pozostaje nośnik ratunkowy i chroot.</p>`,
  },
  {
    kat: 'system',
    title: 'Read-only file system — system plików przełączony w tryb awaryjny',
    excerpt: 'Co to znaczy, dlaczego jądro tak robi i czego nie wolno zrobić w pierwszym odruchu.',
    body: `<p>System działa, ale nic nie da się zapisać. To nie jest przypadek — jądro świadomie przełączyło system plików w tryb tylko do odczytu po wykryciu błędu.</p><h2>1. Dlaczego tak</h2><p>Domyślne zachowanie przy błędzie to <code>errors=remount-ro</code>. Dalszy zapis na uszkodzonym systemie plików pogłębiałby zniszczenia — lepiej zatrzymać się od razu.</p><h2>2. Ustalenie przyczyny</h2><pre><code>dmesg -T | grep -iE "error|remount|ext4|I/O"
journalctl -k -p err -b</code></pre><p>Wpisy o błędach wejścia-wyjścia wskazują na sprzęt. Wpisy o błędach struktury — na uszkodzenie systemu plików.</p><h2>3. Kolejność, która ratuje dane</h2><ol><li><strong>Najpierw sprawdź dysk.</strong> Jeśli to awaria nośnika, ponowne montowanie do zapisu dokończy dzieła.</li><li>Przy podejrzeniu awarii sprzętowej — wykonaj obraz dysku, zanim cokolwiek naprawisz.</li><li>Dopiero potem sprawdzaj system plików.</li></ol><pre><code>smartctl -a /dev/sda | grep -iE "reallocated|pending|error"</code></pre><h2>4. Sprawdzenie systemu plików</h2><p>Wykonuje się je na <strong>odmontowanym</strong> wolumenie — z nośnika ratunkowego albo w trybie awaryjnym:</p><pre><code>fsck -n /dev/sda1     # tylko sprawdzenie
fsck -y /dev/sda1     # z naprawą</code></pre><p>Naprawa na zamontowanym systemie plików niszczy dane. Narzędzie zwykle odmawia, ale nie zawsze.</p><h2>5. Wymuszenie sprawdzenia przy rozruchu</h2><pre><code>touch /forcefsck
reboot</code></pre><h2>6. Gdy to karta pamięci albo pendrive</h2><p>Tanie nośniki przechodzą w tryb tylko do odczytu na stałe po wyczerpaniu bloków zapasowych. To nie awaria systemu plików, tylko koniec życia nośnika — danych nie da się już na nim zapisać żadnym sposobem.</p><h2>Czego ten materiał nie rozwiązuje</h2><p>Przywrócenie zapisu przez <code>mount -o remount,rw</code> bez ustalenia przyczyny jest najgorszym możliwym krokiem: usuwa objaw, zostawia uszkodzenie i pozwala mu się rozrastać.</p>`,
  },
  {
    kat: 'system',
    title: 'Usługa nie wstaje po restarcie mimo systemctl enable',
    excerpt: 'Zależności, kolejność startu i typowe przyczyny działania „tylko po ręcznym uruchomieniu".',
    body: `<p>Ręcznie działa, po restarcie maszyny nie. Przyczyna jest w kolejności albo w środowisku, nie w samej usłudze.</p><h2>1. Czy w ogóle jest włączona</h2><pre><code>systemctl is-enabled nazwa
systemctl status nazwa</code></pre><p>Brak sekcji <code>[Install]</code> w pliku jednostki sprawia, że <code>enable</code> nic nie robi — a polecenie nie zawsze krzyczy o tym wyraźnie.</p><h2>2. Co mówi dziennik z rozruchu</h2><pre><code>journalctl -u nazwa -b --no-pager</code></pre><h2>3. Sieć jeszcze nie działa</h2><p>Najczęstsza przyczyna. <code>After=network.target</code> znaczy tylko „stos sieciowy wystartował", a nie „interfejs ma adres". Usługa wiążąca się z konkretnym adresem zawiedzie.</p><pre><code>[Unit]
After=network-online.target
Wants=network-online.target</code></pre><p>Wymaga to włączonej usługi oczekiwania na sieć:</p><pre><code>systemctl enable systemd-networkd-wait-online</code></pre><h2>4. Zasób sieciowy albo dysk jeszcze niezamontowany</h2><pre><code>[Unit]
RequiresMountsFor=/mnt/dane</code></pre><h2>5. Baza jeszcze nie przyjmuje połączeń</h2><p><code>After=postgresql.service</code> znaczy „proces wystartował", nie „baza jest gotowa". Rozwiązaniem nie jest opóźnienie na sztywno, tylko ponawianie połączenia w aplikacji — i tak jest potrzebne, bo baza bywa restartowana także w trakcie pracy.</p><h2>6. Inne środowisko</h2><p>Ręcznie uruchamiasz w swojej powłoce, ze swoim <code>PATH</code> i zmiennymi. Usługa systemd ma środowisko niemal puste. Stąd wymóg pełnych ścieżek w <code>ExecStart</code> i jawnego podania zmiennych.</p><pre><code>systemctl show nazwa -p Environment
systemd-run --uid=uzytkownik --pty /usr/bin/mojprogram</code></pre><h2>Czego ten materiał nie rozwiązuje</h2><p>Usługi zależnej od zalogowanej sesji graficznej — ta nie działa jako usługa systemowa i wymaga jednostki użytkownika.</p>`,
  },
  {
    kat: 'system',
    title: 'Procesu nie da się zabić — stan D',
    excerpt: 'Dlaczego kill -9 nie działa i co realnie można zrobić.',
    body: `<p>Proces nie reaguje na żaden sygnał, także na dziewiątkę. To nie jest błąd — to stan nieprzerywalnego oczekiwania.</p><h2>1. Potwierdzenie</h2><pre><code>ps -eo pid,stat,wchan:24,comm | awk '$2 ~ /D/'</code></pre><p>Stan <code>D</code> oznacza oczekiwanie na operację wejścia-wyjścia, którego nie da się przerwać. Sygnał zostanie doręczony dopiero, gdy operacja się zakończy.</p><h2>2. Na co czeka</h2><pre><code>cat /proc/&lt;pid&gt;/stack
cat /proc/&lt;pid&gt;/wchan; echo</code></pre><h2>3. Trzy typowe przyczyny</h2><ul><li><strong>Zasób sieciowy</strong> zamontowany na twardo, którego serwer zniknął. Operacje czekają w nieskończoność — takie jest zamierzone działanie tego trybu montowania.</li><li><strong>Padający dysk</strong> — kontroler ponawia odczyt przez dziesiątki sekund na każdy sektor.</li><li><strong>Przeciążone wejście-wyjście</strong> — proces po prostu czeka w kolejce i wyjdzie ze stanu D sam.</li></ul><h2>4. Co realnie pomaga</h2><p>Przy zasobie sieciowym — przywrócenie serwera albo wymuszone odmontowanie:</p><pre><code>umount -f -l /mnt/zasob</code></pre><p>Przy padającym dysku — odłączenie go, o ile nie jest to dysk systemowy. Przy przeciążeniu — cierpliwość.</p><h2>5. Diagnoza obciążenia</h2><pre><code>vmstat 1 10
iostat -x 1 5</code></pre><p>Wysoka wartość w kolumnie oczekiwania na wejście-wyjście przy niskim zużyciu procesora potwierdza, że wąskim gardłem jest nośnik.</p><h2>6. Kiedy zostaje restart</h2><p>Jeśli przyczyna zniknęła, a proces nadal wisi, oznacza to zwykle błąd w sterowniku. Wtedy pozostaje restart maszyny — proces w stanie D nie zniknie inaczej.</p><h2>Czego ten materiał nie rozwiązuje</h2><p>Stan D nie jest chorobą samą w sobie, tylko objawem. Zabicie procesu, gdyby było możliwe, nie naprawiłoby zasobu, na który czeka.</p>`,
  },
  {
    kat: 'system',
    title: 'sudo: unable to resolve host',
    excerpt: 'Drobiazg opóźniający każde polecenie o kilkanaście sekund — i jego naprawa.',
    body: `<p>Ostrzeżenie samo w sobie nic nie psuje, ale <code>sudo</code> czeka wtedy na odpowiedź serwera nazw i każde polecenie startuje z opóźnieniem.</p><h2>1. Przyczyna</h2><p>Nazwa hosta z <code>/etc/hostname</code> nie ma odpowiednika w <code>/etc/hosts</code>, więc próba jej rozwiązania idzie do DNS i kończy się przekroczeniem czasu.</p><h2>2. Sprawdzenie</h2><pre><code>hostname
cat /etc/hostname
grep "$(hostname)" /etc/hosts</code></pre><h2>3. Naprawa</h2><p>Do <code>/etc/hosts</code> dopisujemy nazwę przy adresie pętli zwrotnej:</p><pre><code>127.0.0.1   localhost
127.0.1.1   nazwa-maszyny</code></pre><p>Adres <code>127.0.1.1</code> to konwencja z Debiana dla nazwy własnej maszyny — pozwala odróżnić ją od <code>localhost</code>.</p><h2>4. Po zmianie nazwy</h2><pre><code>hostnamectl set-hostname nowa-nazwa</code></pre><p>Polecenie zmienia <code>/etc/hostname</code>, ale <strong>nie dopisuje wpisu</strong> do <code>/etc/hosts</code>. To najczęstszy moment powstania problemu.</p><h2>5. Weryfikacja</h2><pre><code>getent hosts $(hostname)
time sudo true</code></pre><p>Drugie polecenie pokazuje, czy opóźnienie zniknęło — przed naprawą trwa zwykle kilkanaście sekund, po naprawie jest natychmiastowe.</p><h2>6. W kontenerach</h2><p>Ten sam objaw pojawia się w kontenerach po ustawieniu własnej nazwy bez wpisu w pliku hosts. Docker dodaje go sam przy uruchomieniu, ale zmiana nazwy w trakcie pracy już nie.</p><h2>Czego ten materiał nie rozwiązuje</h2><p>Opóźnień powodowanych przez nieosiągalny serwer nazw w konfiguracji sieci — te dotyczą wszystkich poleceń rozwiązujących nazwy, nie tylko <code>sudo</code>, i widać je w <code>resolvectl status</code>.</p>`,
  },
  {
    kat: 'siec',
    title: 'SSH: Permission denied (publickey)',
    excerpt: 'Uporządkowana diagnoza od strony klienta i serwera — z uprawnieniami plików na czele.',
    body: `<p>Komunikat mówi tylko tyle, że serwer nie przyjął żadnej z zaproponowanych metod. Przyczyn jest kilka i wszystkie da się sprawdzić po kolei.</p><h2>1. Co proponuje klient</h2><pre><code>ssh -vvv uzytkownik@serwer 2&gt;&amp;1 | grep -iE "offering|authentications that can continue|no such identity"</code></pre><p>Ten jeden wiersz rozstrzyga najwięcej: widać, który klucz został zaoferowany i czy serwer w ogóle dopuszcza uwierzytelnianie kluczem.</p><h2>2. Uprawnienia po stronie klienta</h2><pre><code>chmod 700 ~/.ssh
chmod 600 ~/.ssh/id_ed25519
chmod 644 ~/.ssh/id_ed25519.pub</code></pre><p>Klient odmawia użycia klucza dostępnego do odczytu dla innych — i mówi o tym wyraźnie w trybie szczegółowym.</p><h2>3. Uprawnienia po stronie serwera</h2><p>To najczęstsza przyczyna i najmniej oczywista, bo serwer <strong>nie powie</strong>, o co chodzi:</p><pre><code>chmod 700 ~/.ssh
chmod 600 ~/.ssh/authorized_keys
chown -R uzytkownik:uzytkownik ~/.ssh
chmod 755 ~   # katalog domowy nie może być zapisywalny dla grupy</code></pre><p>Zapisywalny dla grupy katalog domowy cicho unieważnia logowanie kluczem. Przyczynę widać wyłącznie w dzienniku serwera.</p><h2>4. Dziennik serwera</h2><pre><code>journalctl -u ssh -n 50 --no-pager | grep -i "authentication refused\\|bad ownership"</code></pre><h2>5. Ten sam klucz, właściwy użytkownik</h2><pre><code>ssh-keygen -lf ~/.ssh/id_ed25519.pub
ssh-keygen -lf ~/.ssh/authorized_keys</code></pre><p>Porównanie odcisków rozstrzyga, czy na serwerze leży ten klucz, o którym myślisz.</p><h2>6. Zbyt wiele kluczy w agencie</h2><p>Serwer zrywa połączenie po kilku nieudanych próbach. Przy dziesięciu kluczach w agencie właściwy może nie zdążyć:</p><pre><code>ssh -o IdentitiesOnly=yes -i ~/.ssh/wlasciwy_klucz uzytkownik@serwer</code></pre><h2>7. Konfiguracja serwera</h2><pre><code>sshd -T | grep -iE "pubkeyauthentication|authorizedkeysfile|permitrootlogin|allowusers"</code></pre><h2>Czego ten materiał nie rozwiązuje</h2><p>Sytuacji, w której straciłeś jedyny klucz do maszyny bez konsoli awaryjnej. Wtedy pozostaje konsola u dostawcy albo tryb ratunkowy — dlatego drugi klucz warto dodać, zanim będzie potrzebny.</p>`,
  },
  {
    kat: 'siec',
    title: 'Połączenie SSH zrywa się po kilku minutach bezczynności',
    excerpt: 'Wygasające wpisy NAT, ustawienia po obu stronach i wznawianie sesji.',
    body: `<p>Sesja zamiera w połowie pracy: znaki nie pojawiają się, po chwili komunikat o zerwaniu połączenia. Przyczyna zwykle nie leży w SSH.</p><h2>1. Skąd to się bierze</h2><p>Router z NAT po drodze usuwa wpis o połączeniu, przez które nic nie płynie. Pakiet wysłany po kilku minutach ciszy nie ma już dokąd wrócić.</p><h2>2. Rozwiązanie po stronie klienta</h2><p>W <code>~/.ssh/config</code>:</p><pre><code>Host *
    ServerAliveInterval 30
    ServerAliveCountMax 6
    TCPKeepAlive no</code></pre><p>Klient wysyła zapytanie co trzydzieści sekund i zrywa dopiero po sześciu bez odpowiedzi. Wyłączenie mechanizmu warstwy TCP jest celowe — działa on na poziomie, który pośrednicy potrafią ignorować.</p><h2>3. Rozwiązanie po stronie serwera</h2><p>W <code>/etc/ssh/sshd_config</code>:</p><pre><code>ClientAliveInterval 30
ClientAliveCountMax 6</code></pre><pre><code>sshd -t &amp;&amp; systemctl reload ssh</code></pre><h2>4. Gdy zrywa mimo to</h2><p>Zerwania w regularnych odstępach, także przy aktywnym ruchu, wskazują na coś innego: niestabilne łącze, przegrzewającą się kartę sieciową albo urządzenie zrywające długie połączenia z zasady. Wtedy pomaga obserwacja:</p><pre><code>mtr -rw serwer</code></pre><h2>5. Praca odporna na zerwania</h2><p>Najlepsze rozwiązanie to nie walczyć z zerwaniami, tylko przestać na nich tracić:</p><pre><code>tmux new -s praca
tmux attach -t praca</code></pre><p>Sesja żyje na serwerze niezależnie od połączenia. Zerwanie przestaje cokolwiek kosztować.</p><h2>6. Alternatywa</h2><p>Klient <code>mosh</code> przeżywa zmianę sieci i długie przerwy, bo działa na UDP i utrzymuje stan sesji. Wymaga otwarcia zakresu portów UDP na serwerze.</p><h2>Czego ten materiał nie rozwiązuje</h2><p>Rozłączeń wymuszanych świadomie przez politykę serwera — limit czasu bezczynności ustawiony przez administratora zadziała mimo pakietów podtrzymujących.</p>`,
  },
  {
    kat: 'siec',
    title: 'Host key verification failed',
    excerpt: 'Kiedy to zmiana serwera, a kiedy sygnał, którego nie wolno zignorować.',
    body: `<p>Klient odmawia połączenia, bo klucz serwera różni się od zapamiętanego. Ostrzeżenie jest poważne i ma dwie możliwe przyczyny.</p><h2>1. Przyczyna niewinna</h2><ul><li>Serwer został postawiony od nowa i wygenerował nowe klucze.</li><li>Ten sam adres IP przydzielono innej maszynie.</li><li>Łączysz się przez pośrednika albo przekierowanie portu do innej maszyny niż wcześniej.</li></ul><h2>2. Przyczyna groźna</h2><p>Ktoś wstawił się pomiędzy i podstawia własny serwer. Właśnie po to ten mechanizm istnieje — i właśnie dlatego nie wolno usuwać wpisu odruchowo.</p><h2>3. Weryfikacja przed usunięciem wpisu</h2><p>Odcisk klucza sprawdzamy <strong>inną drogą</strong> — z konsoli u dostawcy, z panelu maszyny wirtualnej albo pytając administratora:</p><pre><code>ssh-keygen -lf /etc/ssh/ssh_host_ed25519_key.pub</code></pre><p>Porównujemy z odciskiem pokazanym przez klienta. Zgodność oznacza, że zmiana była prawdziwa.</p><h2>4. Usunięcie starego wpisu</h2><pre><code>ssh-keygen -R serwer.example.com
ssh-keygen -R 203.0.113.10</code></pre><p>Adres i nazwa to osobne wpisy — trzeba usunąć oba.</p><h2>5. Czego nie robić</h2><pre><code>ssh -o StrictHostKeyChecking=no</code></pre><p>Wyłącza całą ochronę przed podstawieniem serwera. W skryptach automatyzujących spotyka się to nagminnie i jest to realne osłabienie bezpieczeństwa — lepszym rozwiązaniem jest wgranie znanych kluczy z wyprzedzeniem.</p><h2>6. Dla wielu maszyn</h2><p>Przy dużej liczbie serwerów rozwiązaniem jest urząd certyfikacji dla SSH: klienci ufają jednemu kluczowi podpisującemu, a nie każdemu serwerowi z osobna. Wymiana serwera przestaje wtedy generować ostrzeżenia.</p><h2>Czego ten materiał nie rozwiązuje</h2><p>Jeśli nie masz jak zweryfikować odcisku niezależnym kanałem, nie masz też podstawy, żeby stwierdzić, że zmiana jest niewinna. W sieci, której nie ufasz, warto wtedy poczekać.</p>`,
  },
  {
    kat: 'siec',
    title: '502 Bad Gateway — diagnoza po stronie nginx',
    excerpt: 'Co ten kod znaczy naprawdę i jak w trzech krokach wskazać winowajcę.',
    body: `<p>Kod 502 znaczy: pośrednik nie dostał sensownej odpowiedzi od aplikacji. Problem jest prawie zawsze za nginx, nie w nim.</p><h2>1. Dziennik błędów — pierwszy krok</h2><pre><code>tail -50 /var/log/nginx/error.log</code></pre><p>Treść wpisu rozstrzyga niemal zawsze:</p><ul><li><code>connect() failed (111: Connection refused)</code> — aplikacja nie działa albo słucha na innym porcie.</li><li><code>no live upstreams</code> — wszystkie kopie aplikacji uznane za martwe.</li><li><code>upstream prematurely closed connection</code> — aplikacja padła w trakcie obsługi żądania.</li><li><code>connect() failed (13: Permission denied)</code> — SELinux albo prawa do gniazda.</li></ul><h2>2. Czy aplikacja żyje</h2><pre><code>systemctl status mojaapp
ss -tulpn | grep 3000
curl -v http://127.0.0.1:3000/</code></pre><p>Działa lokalnie, nie działa przez nginx — problem jest w konfiguracji pośrednika. Nie działa lokalnie — problem jest w aplikacji.</p><h2>3. Adres w konfiguracji</h2><p>Aplikacja słuchająca na <code>127.0.0.1</code> jest osiągalna dla nginx na tej samej maszynie, ale nie z kontenera. Aplikacja w kontenerze musi słuchać na <code>0.0.0.0</code>, a nginx kierować na nazwę usługi, nie na <code>localhost</code>.</p><h2>4. SELinux</h2><pre><code>getenforce
setsebool -P httpd_can_network_connect 1</code></pre><p>Na systemach z rodziny RHEL to bardzo częsta przyczyna 502 przy poprawnej pozostałej konfiguracji — i nie zostawia śladu w dzienniku nginx poza odmową dostępu.</p><h2>5. Aplikacja padająca pod obciążeniem</h2><pre><code>journalctl -u mojaapp --since "10 min ago"
dmesg -T | grep -i "killed process"</code></pre><p>Przerywane 502, tylko w szczytach, to zwykle restartowana albo zabijana aplikacja — patrz kod wyjścia 137.</p><h2>6. Limity czasu</h2><p>Żądanie trwające dłużej niż limit pośrednika kończy się zwykle kodem 504, ale przy zerwaniu połączenia przez aplikację bywa 502:</p><pre><code>proxy_read_timeout 60s;</code></pre><h2>Czego ten materiał nie rozwiązuje</h2><p>Podniesienie limitów ukrywa objaw, gdy prawdziwym problemem jest aplikacja odpowiadająca zbyt wolno. Warto najpierw sprawdzić, dlaczego trwa to tak długo.</p>`,
  },
  {
    kat: 'siec',
    title: 'Strona działa po adresie IP, nie działa po domenie',
    excerpt: 'Rozdzielenie problemu na DNS, wirtualne hosty i certyfikat.',
    body: `<p>To dobra wiadomość: warstwa sieciowa i aplikacja działają. Problem jest w jednym z trzech miejsc.</p><h2>1. Czy domena w ogóle wskazuje na ten serwer</h2><pre><code>dig +short example.com A
dig +short example.com AAAA
curl -4 ifconfig.me</code></pre><p>Brak odpowiedzi albo inny adres to koniec diagnozy — reszta nie ma znaczenia.</p><p>Uwaga na rekord AAAA: domena z adresem IPv6 wskazującym gdzie indziej sprawi, że część użytkowników trafi w złe miejsce, a część nie. Objaw „działa u mnie, nie działa u kolegi" ma tu jedno z najczęstszych źródeł.</p><h2>2. Pamięć podręczna i TTL</h2><pre><code>dig @1.1.1.1 example.com
dig @8.8.8.8 example.com
resolvectl flush-caches</code></pre><p>Pytanie do kilku serwerów pokazuje, czy zmiana zdążyła się rozejść. Przy wysokim TTL trwa to tyle, ile wynosił poprzedni TTL.</p><h2>3. Wirtualny host</h2><p>Serwer po adresie IP zwraca konfigurację domyślną, po nazwie — dopasowaną. Jeśli żaden blok nie pasuje do nazwy, dostajemy stronę domyślną albo błąd:</p><pre><code>nginx -T | grep -A3 server_name</code></pre><p>Sprawdzenie z wymuszoną nazwą, z pominięciem DNS:</p><pre><code>curl -H "Host: example.com" http://203.0.113.10/</code></pre><p>To rozstrzyga natychmiast, czy problem jest w DNS, czy w konfiguracji serwera.</p><h2>4. Certyfikat</h2><p>Po adresie IP używamy HTTP, po nazwie — HTTPS. Błąd może więc dotyczyć wyłącznie certyfikatu:</p><pre><code>openssl s_client -connect example.com:443 -servername example.com &lt; /dev/null 2&gt;&amp;1 | grep -E "subject=|verify"</code></pre><h2>5. Rekord CNAME na domenie głównej</h2><p>Alias nie może stać na domenie głównej obok innych rekordów. To częsta przyczyna działającej poddomeny i niedziałającej domeny bez przedrostka.</p><h2>Czego ten materiał nie rozwiązuje</h2><p>Domeny wskazującej poprawnie, ale zablokowanej po stronie dostawcy albo wygasłej — wtedy zapytania w ogóle nie wracają, a stan domeny sprawdza się u rejestratora.</p>`,
  },
  {
    kat: 'siec',
    title: 'Certyfikat wygasł mimo automatycznego odnawiania',
    excerpt: 'Dlaczego automat przestał działać po cichu i jak to wykryć, zanim wygaśnie.',
    body: `<p>Odnawianie działało miesiącami i przestało. Przyczyn jest kilka i wszystkie są ciche — nikt nie dostaje powiadomienia.</p><h2>1. Czy zegar w ogóle chodzi</h2><pre><code>systemctl list-timers | grep -i certbot
systemctl status certbot.timer</code></pre><h2>2. Próba na sucho</h2><pre><code>certbot renew --dry-run</code></pre><p>To najszybszy sposób zobaczenia prawdziwego błędu. Wykonuje pełną procedurę bez wydawania certyfikatu.</p><h2>3. Najczęstsze przyczyny</h2><ul><li><strong>Port 80 zamknięty</strong> — ktoś „posprzątał" zaporę. Weryfikacja metodą HTTP tego wymaga.</li><li><strong>Przekierowanie na HTTPS</strong> obejmujące ścieżkę weryfikacji — żądanie urzędu nie dociera do pliku.</li><li><strong>Zmiana DNS</strong> — domena wskazuje już gdzie indziej.</li><li><strong>Poddomena usunięta</strong> z konfiguracji, ale nadal w certyfikacie — odnowienie całego certyfikatu zawodzi przez jedną nazwę.</li><li><strong>Wyczerpany limit</strong> po serii nieudanych prób.</li></ul><h2>4. Sprawdzenie ścieżki weryfikacji</h2><pre><code>mkdir -p /var/www/html/.well-known/acme-challenge
echo test &gt; /var/www/html/.well-known/acme-challenge/proba
curl -v http://example.com/.well-known/acme-challenge/proba</code></pre><p>Musi wrócić <code>test</code> po zwykłym HTTP, bez przekierowania.</p><h2>5. Wyjątek w przekierowaniu</h2><pre><code>location /.well-known/acme-challenge/ {
    root /var/www/html;
}
location / {
    return 301 https://$host$request_uri;
}</code></pre><h2>6. Powiadomienie, zanim będzie za późno</h2><p>Zegar sprawdzający pozostały czas ważności i wysyłający wiadomość na dwa tygodnie przed terminem jest tańszy niż awaria w weekend:</p><pre><code>echo | openssl s_client -connect example.com:443 -servername example.com 2&gt;/dev/null \\
  | openssl x509 -noout -checkend 1209600 || echo "Certyfikat wygasa w ciągu 14 dni"</code></pre><h2>Czego ten materiał nie rozwiązuje</h2><p>Certyfikat odnowiony, a serwer nadal podaje stary — to znaczy, że zabrakło przeładowania usługi po odnowieniu. Zaczep wykonywany po odnowieniu musi przeładować nginx.</p>`,
  },
  {
    kat: 'siec',
    title: 'WebSocket rozłącza się co minutę za pośrednikiem',
    excerpt: 'Limity czasu w proxy, brak nagłówków przełączenia protokołu i pakiety podtrzymujące.',
    body: `<p>Połączenie wstaje i zrywa się w regularnych odstępach — najczęściej co sześćdziesiąt sekund. Regularność wskazuje na limit czasu, nie na awarię sieci.</p><h2>1. Czy w ogóle dochodzi do przełączenia protokołu</h2><pre><code>curl -i -N -H "Connection: Upgrade" -H "Upgrade: websocket" \\
  -H "Sec-WebSocket-Version: 13" -H "Sec-WebSocket-Key: dGhlIHNhbXBsZSBub25jZQ==" \\
  https://example.com/ws</code></pre><p>Oczekiwana odpowiedź to <code>101 Switching Protocols</code>. Kod 200 albo 400 oznacza, że pośrednik nie przepuścił przełączenia.</p><h2>2. Nagłówki w nginx</h2><pre><code>location /ws {
    proxy_pass http://127.0.0.1:3000;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $host;
    proxy_read_timeout 3600s;
    proxy_send_timeout 3600s;
}</code></pre><p>Bez wersji 1.1 i dwóch nagłówków przełączenia połączenie nie wstanie wcale. Bez podniesionych limitów czasu wstanie i zerwie się po minucie ciszy — to dokładnie ten objaw.</p><h2>3. Pakiety podtrzymujące po stronie aplikacji</h2><p>Podniesienie limitu to połowa rozwiązania. Druga to regularne pakiety kontrolne z serwera, zwykle co dwadzieścia do trzydziestu sekund. Bez nich każdy pośrednik po drodze — także taki, nad którym nie masz kontroli — zerwie bezczynne połączenie.</p><h2>4. Sieci dostarczania treści</h2><p>Część usług ma własny, nieusuwalny limit dla połączeń WebSocket. Wtedy pakiety podtrzymujące są jedynym wyjściem, a klient musi umieć wznowić połączenie po zerwaniu.</p><h2>5. Wiele instancji aplikacji</h2><p>Połączenie trwa, więc musi trafiać zawsze do tej samej kopii aplikacji, chyba że stan sesji jest wspólny. Rozdzielanie ruchu bez powinowactwa sesji objawia się zrywaniem przy każdym ponownym połączeniu.</p><h2>6. Diagnostyka</h2><pre><code>tail -f /var/log/nginx/error.log
journalctl -u mojaapp -f</code></pre><h2>Czego ten materiał nie rozwiązuje</h2><p>Klient i tak musi umieć wznowić połączenie — sieć komórkowa, uśpienie laptopa i zmiana Wi-Fi zerwą je niezależnie od konfiguracji serwera. Ponawianie z wykładniczym wycofywaniem to element aplikacji, nie infrastruktury.</p>`,
  },
  {
    kat: 'siec',
    title: 'Zmiana rekordu DNS nie działa mimo upływu czasu',
    excerpt: 'Gdzie naprawdę siedzi stara wartość i jak sprawdzić, na którym poziomie.',
    body: `<p>Rekord zmieniony, a część świata widzi stary adres. Trzeba ustalić, na którym poziomie utknęła stara wartość.</p><h2>1. Co mówi serwer autorytatywny</h2><pre><code>dig +short NS example.com
dig @ns1.dostawca.com example.com A</code></pre><p>Pytanie wprost do serwera obsługującego strefę pomija wszystkie pamięci podręczne. Stara wartość <em>tam</em> oznacza, że zmiana w ogóle się nie zapisała.</p><h2>2. Co widzą serwery publiczne</h2><pre><code>dig @1.1.1.1 example.com A
dig @8.8.8.8 example.com A</code></pre><h2>3. Pamięć lokalna</h2><pre><code>resolvectl flush-caches
resolvectl query example.com</code></pre><p>Przeglądarki mają własną pamięć podręczną, niezależną od systemowej — dlatego strona potrafi działać w jednej przeglądarce, a nie działać w drugiej.</p><h2>4. Czas życia rekordu</h2><pre><code>dig example.com A | grep -A1 "ANSWER SECTION"</code></pre><p>Liczba przed typem rekordu to pozostały czas ważności w pamięciach podręcznych. Dopóki nie spadnie do zera, część świata będzie widziała starą wartość — i nic tego nie przyspieszy.</p><p>Stąd zasada: TTL obniża się <strong>z wyprzedzeniem</strong>, dzień lub dwa przed planowaną zmianą, a podnosi po jej rozejściu się.</p><h2>5. Częste pomyłki</h2><ul><li>Zmieniony rekord w strefie, która nie jest już używana — po zmianie serwerów nazw stara strefa nadal istnieje i kusi.</li><li>Rekord AAAA zostawiony ze starym adresem.</li><li>Serwis pośredniczący z własną pamięcią podręczną między światem a serwerem.</li><li>Wpis w <code>/etc/hosts</code> zapomniany z czasów testów — sprawdź go, zanim zaczniesz obwiniać DNS.</li></ul><h2>6. Rozejście się na świecie</h2><p>Ostateczną odpowiedź daje sprawdzenie z kilku miejsc na świecie. Do tego służą publiczne narzędzia odpytujące wiele serwerów naraz.</p><h2>Czego ten materiał nie rozwiązuje</h2><p>Serwerów operatorów ignorujących TTL i trzymających wpisy dłużej, niż powinny. Zdarza się to i nie da się z tym zrobić nic poza czekaniem.</p>`,
  },
  {
    kat: 'siec',
    title: 'Poczta z własnego serwera trafia do spamu',
    excerpt: 'Kolejność sprawdzania: uwierzytelnianie, reputacja adresu, treść.',
    body: `<p>Wiadomości wychodzą, ale lądują w spamie albo znikają. Sprawdzamy od rzeczy najłatwiejszych do zweryfikowania.</p><h2>1. Uwierzytelnianie domeny</h2><pre><code>dig +short TXT example.com | grep spf
dig +short TXT selektor._domainkey.example.com
dig +short TXT _dmarc.example.com</code></pre><p>Brak któregokolwiek z trzech to najczęstsza przyczyna. Sama obecność nie wystarczy — musi się zgadzać domena w polu nadawcy z domeną potwierdzoną przez SPF lub DKIM, inaczej DMARC nie przejdzie.</p><h2>2. Sprawdzenie na żywo</h2><p>Najprostszy test: wysłać wiadomość na własną skrzynkę u dużego dostawcy i obejrzeć nagłówki. Wyniki <code>spf=pass</code>, <code>dkim=pass</code> i <code>dmarc=pass</code> muszą być wszystkie trzy.</p><h2>3. Rekord odwrotny</h2><pre><code>dig +short -x 203.0.113.10</code></pre><p>Adres bez rekordu odwrotnego albo z rekordem niezgodnym z nazwą serwera poczty jest traktowany podejrzliwie. Ustawia się go u dostawcy adresacji, nie we własnej strefie.</p><h2>4. Reputacja adresu</h2><p>Adresy z pul dostawców VPS bywają z góry na listach ograniczonego zaufania. Sprawdzenie na publicznych listach blokad jest szybkie; zejście z nich trwa i wymaga wniosku.</p><h2>5. Treść i forma</h2><ul><li>Brak wersji tekstowej obok HTML.</li><li>Odnośnik do domeny innej niż nadawca — typowe przy skracaczach adresów.</li><li>Jeden wielki obrazek zamiast tekstu.</li><li>Brak nagłówka pozwalającego się wypisać w wiadomościach masowych.</li></ul><h2>6. Rozstrzygnięcie</h2><p>Ta sama wiadomość wysłana przez zewnętrznego dostawcę dociera, a z własnego serwera nie — to reputacja adresu, nie treść. Wtedy najtańszym rozwiązaniem jest wysyłka przez dostawcę z gotową reputacją.</p><h2>Czego ten materiał nie rozwiązuje</h2><p>Utrzymanie własnego serwera wysyłkowego z dobrą reputacją to praca ciągła: monitorowanie odrzuceń, reagowanie na skargi i pilnowanie, żeby nikt nie wykorzystał serwera do rozsyłania spamu. Przy kilkuset wiadomościach miesięcznie rzadko się to opłaca.</p>`,
  },
];
