/** Poradniki — Sprzęt. */
export default [
  {
    kat: 'sprzet',
    title: 'Jak sprawdzić stan dysku i ocenić, czy nadaje się do wymiany',
    excerpt: 'Odczyt S.M.A.R.T., test powierzchni i atrybuty, które naprawdę coś zapowiadają.',
    body: `<p>Dysk rzadko pada bez śladu — ale ślady trzeba umieć odczytać.</p><h2>1. Podstawowy odczyt</h2><pre><code>smartctl -a /dev/sda
smartctl -a /dev/nvme0</code></pre><p>Na kontrolerze RAID albo w obudowie USB może być potrzebne wskazanie typu urządzenia przełącznikiem <code>-d</code>.</p><h2>2. Atrybuty dysków talerzowych</h2><ul><li><strong>Reallocated_Sector_Ct</strong> — powyżej zera to sygnał, rosnące to wyrok.</li><li><strong>Current_Pending_Sector</strong> — najsilniejszy zwiastun awarii.</li><li><strong>Offline_Uncorrectable</strong> — błędy nie do naprawienia.</li><li><strong>Power_On_Hours</strong> — sam wiek nic nie przesądza, ale daje kontekst.</li></ul><h2>3. Dyski SSD</h2><pre><code>nvme smart-log /dev/nvme0</code></pre><p>Patrzymy na procent zużycia, liczbę zapisanych bloków i liczbę zapasowych bloków. Zapisane dane porównujemy z wytrzymałością deklarowaną przez producenta.</p><h2>4. Test powierzchni</h2><pre><code>smartctl -t short /dev/sda   # kilka minut
smartctl -t long /dev/sda    # kilka godzin
smartctl -l selftest /dev/sda</code></pre><p>Test działa w tle i nie przeszkadza w pracy.</p><h2>5. Automatyczne pilnowanie</h2><pre><code>systemctl enable --now smartd</code></pre><p>Po ustawieniu adresu w konfiguracji przyśle wiadomość, gdy atrybut przekroczy próg.</p><h2>6. Kiedy wymieniać</h2><p>Rosnąca liczba sektorów oczekujących albo przeniesionych, błędy wejścia-wyjścia w dzienniku jądra, nietypowe dźwięki, gwałtowny spadek prędkości. Przy dysku w macierzy — nie czekamy na potwierdzenie.</p><h2>Czego ten materiał nie rozwiązuje</h2><p>Znaczna część dysków pada bez wcześniejszego ostrzeżenia. Czysty odczyt to nie gwarancja, tylko brak złych wiadomości — kopia zapasowa pozostaje jedynym realnym zabezpieczeniem.</p>`,
  },
  {
    kat: 'sprzet',
    title: 'Jak sprawdzić pamięć RAM pod kątem błędów',
    excerpt: 'Test pamięci przy podejrzeniu losowych zawieszeń i uszkodzeń plików.',
    body: `<p>Błędy pamięci objawiają się losowo: zawieszeniami bez wzoru, uszkodzonymi plikami, awariami kompilacji w różnych miejscach. Podejrzenie warto rozstrzygnąć pomiarem.</p><h2>1. Memtest86+</h2><p>Dostępny w menu rozruchowym większości dystrybucji albo z osobnego nośnika. Działa poza systemem, więc testuje całą pamięć.</p><p>Jeden przebieg to za mało — błędy bywają rzadkie. Rozsądne minimum to kilka godzin, a przy podejrzeniu bez potwierdzenia — całą noc.</p><h2>2. Test z poziomu systemu</h2><pre><code>memtester 2G 3</code></pre><p>Testuje tylko wolną pamięć i nie sprawdzi obszaru zajętego przez jądro, ale bywa wystarczający i nie wymaga restartu.</p><h2>3. Obciążenie całości</h2><pre><code>stress-ng --vm 4 --vm-bytes 80% --timeout 30m --metrics</code></pre><h2>4. Sprawdzenie w dzienniku</h2><pre><code>dmesg -T | grep -iE "machine check|mce|edac|hardware error"
journalctl -k -b -1 -p err</code></pre><p>Na maszynie z pamięcią ECC podsystem raportuje błędy naprawione — to zapowiedź degradującego się modułu.</p><h2>5. Gdy błędy są</h2><ol><li>Wyłącz profil podkręcania pamięci i powtórz test — bardzo często to wystarczy.</li><li>Testuj po jednym module, żeby wskazać wadliwy.</li><li>Sprawdź inne gniazda — problem bywa w gnieździe albo w kontrolerze, nie w kości.</li></ol><h2>6. Po wymianie</h2><p>Powtórz pełny test. Wymiana bez potwierdzenia zostawia niepewność, czy przyczyna faktycznie zniknęła.</p><h2>Czego ten materiał nie rozwiązuje</h2><p>Czysty wynik nie wyklucza błędu pojawiającego się raz na tydzień. Przy uporczywych objawach bez potwierdzenia warto rozważyć zasilacz i temperaturę — dają podobny obraz.</p>`,
  },
  {
    kat: 'sprzet',
    title: 'Jak przekazać kartę graficzną do maszyny wirtualnej',
    excerpt: 'Przekazywanie urządzeń PCI: IOMMU, grupy i podmiana sterownika.',
    body: `<p>Przekazanie karty daje maszynie wirtualnej pełną wydajność graficzną. Wymaga wsparcia sprzętu i kilku kroków, których nie da się pominąć.</p><h2>1. Włączenie IOMMU</h2><p>W ustawieniach płyty włączamy wirtualizację i odpowiednik VT-d lub AMD-Vi, po czym dokładamy parametr jądra:</p><pre><code>intel_iommu=on iommu=pt
# albo
amd_iommu=on iommu=pt</code></pre><pre><code>dmesg | grep -i -e DMAR -e IOMMU</code></pre><h2>2. Sprawdzenie grup</h2><pre><code>for g in /sys/kernel/iommu_groups/*; do
  echo "Grupa \${g##*/}"
  for d in $g/devices/*; do lspci -nns "\${d##*/}"; done
done</code></pre><p>Karta musi być w grupie sama albo z urządzeniami, które również możemy oddać. To ograniczenie wynika z układu płyty i nie da się go obejść konfiguracją.</p><h2>3. Identyfikatory urządzenia</h2><pre><code>lspci -nn | grep -i vga</code></pre><p>Notujemy identyfikatory w nawiasach — karty graficznej i jej układu dźwiękowego, bo są w tej samej grupie.</p><h2>4. Podpięcie do sterownika pośredniczącego</h2><pre><code>echo "options vfio-pci ids=10de:xxxx,10de:yyyy" &gt; /etc/modprobe.d/vfio.conf
echo "vfio-pci" &gt; /etc/modules-load.d/vfio.conf
update-initramfs -u
reboot</code></pre><h2>5. Weryfikacja</h2><pre><code>lspci -nnk -d 10de:xxxx</code></pre><p>W wierszu używanego sterownika powinno widnieć <code>vfio-pci</code>.</p><h2>6. Dodanie do maszyny</h2><p>W menedżerze maszyn wirtualnych dodajemy urządzenie PCI. Kartę i jej układ dźwiękowy przekazujemy razem.</p><h2>Czego ten materiał nie rozwiązuje</h2><p>Przekazana karta znika z systemu gospodarza. Przy jednej karcie w komputerze potrzebna jest druga — zintegrowana albo osobna — do obsługi hosta. Nie obejmuje też przekazywania z przełączaniem między hostem a gościem, które wymaga znacznie więcej pracy.</p>`,
  },
  {
    kat: 'sprzet',
    title: 'Jak zbudować cichy serwer domowy',
    excerpt: 'Dobór podzespołów i ustawień pod kątem hałasu, bez rezygnacji z wydajności.',
    body: `<p>Serwer stojący w mieszkaniu pracuje dwadzieścia cztery godziny na dobę. Hałas jest tu ważniejszym parametrem niż kilka procent wydajności.</p><h2>1. Największe źródła hałasu</h2><ol><li>Małe wentylatory o wysokich obrotach — w zasilaczu i na chipsecie.</li><li>Dyski talerzowe, zwłaszcza serwerowe o wysokiej prędkości obrotowej.</li><li>Chłodzenie procesora dobrane bez zapasu.</li><li>Rezonans obudowy.</li></ol><h2>2. Dobór podzespołów</h2><ul><li>Procesor o niskim TDP — mniej ciepła to wolniejsze wentylatory.</li><li>Zasilacz z trybem bezwentylatorowym przy niskim obciążeniu.</li><li>Duże, wolnoobrotowe wentylatory zamiast małych i szybkich.</li><li>Dyski SSD do systemu, talerzowe tylko na dane rzadko używane.</li></ul><h2>3. Sterowanie obrotami</h2><pre><code>sensors-detect
sensors
pwmconfig
systemctl enable --now fancontrol</code></pre><p>Krzywa obrotów dobrana pod rzeczywiste temperatury bywa skuteczniejsza niż wymiana wentylatorów.</p><h2>4. Usypianie dysków</h2><pre><code>hdparm -B 127 -S 120 /dev/sda</code></pre><p>Ostrożnie: częste zatrzymywanie i rozkręcanie zużywa mechanikę szybciej niż ciągła praca. Ma sens przy dysku używanym raz dziennie, nie przy magazynie danych.</p><h2>5. Ograniczenie mocy procesora</h2><pre><code>cpupower frequency-set -u 2.5GHz</code></pre><p>Na serwerze plików obniżenie górnej granicy taktowania bywa niezauważalne w działaniu, a wyraźnie obniża temperaturę.</p><h2>6. Ustawienie w pomieszczeniu</h2><p>Obudowa na miękkiej podkładce, z dala od ścian tworzących pudło rezonansowe. To zwykle najtańsza i najskuteczniejsza pojedyncza zmiana.</p><h2>Czego ten materiał nie rozwiązuje</h2><p>Cisza kosztuje albo pieniądze, albo wydajność. Sprzęt serwerowy z drugiej ręki bywa tani i wydajny, ale projektowano go do serwerowni, gdzie hałas nikomu nie przeszkadza — w mieszkaniu jest nie do zniesienia.</p>`,
  },
  {
    kat: 'sprzet',
    title: 'Jak zdiagnozować niestabilny komputer',
    excerpt: 'Uporządkowane eliminowanie przyczyn: zasilanie, pamięć, temperatura, dysk.',
    body: `<p>Losowe zawieszenia i restarty mają kilka typowych przyczyn. Eliminujemy je w kolejności od najczęstszych i najłatwiejszych do sprawdzenia.</p><h2>1. Zbierz ślady</h2><pre><code>journalctl -k -b -1 -p err
dmesg -T | grep -iE "error|fail|thermal|mce"</code></pre><p>Nagłe wyłączenie bez żadnego wpisu wskazuje na zasilanie albo temperaturę — przy nich system nie zdąży nic zapisać.</p><h2>2. Cofnij podkręcanie</h2><p>Profil pamięci, ustawienia napięć, tryby zwiększonej wydajności. To najczęstsza przyczyna niestabilności i najtańsza do wykluczenia.</p><h2>3. Temperatury pod obciążeniem</h2><pre><code>sensors
stress-ng --cpu 0 --timeout 10m
watch -n1 sensors</code></pre><h2>4. Pamięć</h2><p>Pełny przebieg testu pamięci, najlepiej przez noc.</p><h2>5. Zasilanie</h2><p>Objawy typowe: restart przy obciążeniu karty graficznej, wyłączenie bez ostrzeżenia, problemy nasilające się z wiekiem zestawu. Zasilacz jest podzespołem, który degraduje się niezauważalnie. Sprawdzenie polega zwykle na podmianie na sprawny.</p><h2>6. Dysk</h2><pre><code>smartctl -a /dev/sda | grep -iE "reallocated|pending|error"</code></pre><h2>7. Metoda eliminacji</h2><p>Odłączamy wszystko, co niepotrzebne: dodatkowe dyski, karty rozszerzeń, urządzenia USB. Uruchamiamy z jednym modułem pamięci. Dokładamy po jednym elemencie.</p><h2>8. System czy sprzęt</h2><p>Uruchomienie z nośnika live i obciążenie go rozstrzyga: awarie także tam oznaczają sprzęt.</p><h2>Czego ten materiał nie rozwiązuje</h2><p>Przy awariach rzadkich, raz na kilka dni, każdy test bywa niekonkluzywny. Wtedy jedyną metodą jest podmiana pojedynczych podzespołów na sprawne i cierpliwość — dlatego warto zacząć od zasilacza i pamięci, które psują się najczęściej.</p>`,
  },
  {
    kat: 'sprzet',
    title: 'Jak bezpiecznie wymienić pastę termoprzewodzącą',
    excerpt: 'Czyszczenie, nałożenie i weryfikacja efektu pomiarem.',
    body: `<p>Zaschnięta pasta to po kilku latach najczęstsza pojedyncza przyczyna dławienia termicznego. Wymiana zajmuje kilkanaście minut.</p><h2>1. Pomiar przed</h2><pre><code>sensors
stress-ng --cpu 0 --timeout 5m &amp; watch -n1 sensors</code></pre><p>Bez pomiaru wyjściowego nie da się stwierdzić, czy zabieg pomógł.</p><h2>2. Przygotowanie</h2><p>Odłączamy zasilanie i przytrzymujemy przycisk zasilania, żeby rozładować kondensatory. Dotykamy metalowej części obudowy przed dotknięciem podzespołów.</p><h2>3. Zdjęcie chłodzenia</h2><p>Śruby odkręcamy na krzyż, po trochu. Przy zaschniętej paście radiator bywa przyklejony — delikatny ruch obrotowy pomaga; nie odrywamy siłą, bo przy niektórych podstawkach procesor wychodzi razem z chłodzeniem.</p><h2>4. Czyszczenie</h2><p>Alkohol izopropylowy i niestrzępiąca ściereczka, obie powierzchnie do czysta. Uważamy, żeby płyn nie spłynął na płytę.</p><h2>5. Nałożenie</h2><p>Kropla wielkości ziarna grochu na środku pokrywy procesora. Docisk radiatora rozprowadzi ją równomiernie. Nadmiar nie poprawia przewodzenia, a wypływa na płytę.</p><h2>6. Montaż</h2><p>Śruby dokręcamy na krzyż, stopniowo, do wyczuwalnego oporu. Podłączamy wtyczkę wentylatora — pominięcie tego kroku kończy się natychmiastowym przegrzaniem.</p><h2>7. Pomiar po</h2><p>Ten sam test co w kroku pierwszym. Spadek o kilkanaście stopni pod obciążeniem jest typowy przy naprawdę zaschniętej paście.</p><h2>Czego ten materiał nie rozwiązuje</h2><p>Jeśli temperatury się nie zmieniły, przyczyna leży gdzie indziej: niedomontowany radiator, zapchane żeberka, zły obieg powietrza albo chłodzenie za słabe do tego procesora. W laptopach dochodzi wysychanie rurek cieplnych, którego pasta nie naprawi.</p>`,
  },
  {
    kat: 'sprzet',
    title: 'Jak zbudować macierz dyskową w Linuksie',
    excerpt: 'mdadm od utworzenia po monitorowanie i próbę odbudowy.',
    body: `<p>Programowa macierz w Linuksie jest niezależna od kontrolera, więc dyski da się przenieść do dowolnej maszyny.</p><h2>1. Przygotowanie dysków</h2><pre><code>lsblk
wipefs -a /dev/sdb /dev/sdc</code></pre><p>Sprawdzamy nazwy dwa razy — pomyłka kasuje niewłaściwy dysk.</p><h2>2. Utworzenie</h2><pre><code>mdadm --create /dev/md0 --level=1 --raid-devices=2 /dev/sdb /dev/sdc</code></pre><p>Poziom 1 to lustro, 5 to parzystość na trzech lub więcej dyskach, 6 to podwójna parzystość na czterech lub więcej.</p><h2>3. Postęp budowania</h2><pre><code>cat /proc/mdstat
watch -n5 cat /proc/mdstat</code></pre><p>Macierz jest już używalna, choć synchronizacja trwa.</p><h2>4. Zapis konfiguracji</h2><pre><code>mdadm --detail --scan &gt;&gt; /etc/mdadm/mdadm.conf
update-initramfs -u</code></pre><p>Pominięcie tego kroku sprawia, że macierz nie zostanie złożona przy rozruchu — a przy macierzy z systemem oznacza maszynę, która nie wstaje.</p><h2>5. System plików</h2><pre><code>mkfs.ext4 /dev/md0
blkid /dev/md0</code></pre><p>W <code>fstab</code> używamy UUID, nie nazwy urządzenia.</p><h2>6. Powiadomienia</h2><pre><code>MAILADDR admin@example.com</code></pre><pre><code>systemctl enable --now mdmonitor
mdadm --monitor --scan --test --oneshot</code></pre><p>Ostatnie polecenie wysyła wiadomość próbną. Macierz z uszkodzonym dyskiem, o którym nikt nie wie, to macierz czekająca na drugą awarię.</p><h2>7. Ćwiczenie wymiany</h2><pre><code>mdadm --manage /dev/md0 --fail /dev/sdb --remove /dev/sdb
mdadm --manage /dev/md0 --add /dev/sdb</code></pre><p>Warto to przećwiczyć na świeżej macierzy, zanim zajdzie potrzeba.</p><h2>Czego ten materiał nie rozwiązuje</h2><p>Macierz nie jest kopią zapasową. Chroni przed awarią dysku, a nie przed skasowaniem pliku, oprogramowaniem szyfrującym dla okupu ani błędem administratora — te powielają się na wszystkie dyski natychmiast.</p>`,
  },
  {
    kat: 'sprzet',
    title: 'Jak sprawdzić, czy zasilacz nie jest przyczyną problemów',
    excerpt: 'Objawy słabnącego zasilacza i sposoby zawężenia podejrzeń bez miernika.',
    body: `<p>Zasilacz degraduje się cicho i daje objawy, które łatwo przypisać czemu innemu.</p><h2>1. Objawy typowe</h2><ul><li>Restart lub wyłączenie przy obciążeniu karty graficznej, nie przy samym procesorze.</li><li>Wyłączenie bez żadnego wpisu w dziennikach.</li><li>Problemy narastające z wiekiem zestawu, częstsze latem.</li><li>Komputer nie startuje po dłuższym odłączeniu od prądu.</li><li>Cykanie albo piszczenie przy zmianie obciążenia.</li></ul><h2>2. Odczyt napięć</h2><pre><code>sensors</code></pre><p>Odczyty z czujników płyty bywają niedokładne i nie zastępują pomiaru. Traktujemy je jako wskazówkę, nie dowód — ale wyraźne odchylenie od wartości nominalnych coś znaczy.</p><h2>3. Obciążenie w sposób kontrolowany</h2><pre><code>stress-ng --cpu 0 --timeout 15m       # sam procesor
glmark2                                # karta graficzna</code></pre><p>Awaria wyłącznie przy obciążeniu karty przemawia za zasilaczem albo za samą kartą.</p><h2>4. Odłączenie zbędnego</h2><p>Wypinamy dodatkowe dyski, napędy i urządzenia USB. Przy słabnącym zasilaczu zmniejszenie obciążenia często stabilizuje maszynę i to samo w sobie jest wskazówką.</p><h2>5. Sprawdzenie kabli</h2><p>Wtyczki zasilania karty muszą być wpięte do końca i najlepiej osobnymi przewodami, nie jednym rozgałęzionym. Nadtopione styki są wyraźnym sygnałem.</p><h2>6. Rozstrzygnięcie</h2><p>Pewna metoda to podmiana na sprawny zasilacz o odpowiedniej mocy. Elektronicznych testerów zasilaczy nie warto traktować poważnie — sprawdzają obecność napięć bez obciążenia, a problem ujawnia się właśnie pod obciążeniem.</p><h2>Czego ten materiał nie rozwiązuje</h2><p>Otwieranie zasilacza jest niebezpieczne — kondensatory trzymają ładunek długo po odłączeniu od gniazdka. Zasilacza się nie naprawia, tylko wymienia.</p>`,
  },
  {
    kat: 'sprzet',
    title: 'Jak przygotować pendrive z systemem do instalacji',
    excerpt: 'Zapis obrazu, weryfikacja i najczęstsze przyczyny nośnika, z którego nic nie startuje.',
    body: `<p>Zapis obrazu instalacyjnego jest prosty, ale kilka pomyłek powtarza się regularnie.</p><h2>1. Weryfikacja obrazu przed zapisem</h2><pre><code>sha256sum -c SHA256SUMS
gpg --verify SHA256SUMS.gpg SHA256SUMS</code></pre><p>Uszkodzony obraz daje objawy przypominające wadliwy sprzęt — lepiej wykluczyć to na początku.</p><h2>2. Identyfikacja nośnika</h2><pre><code>lsblk
dmesg -T | tail -20</code></pre><p>Podłączamy pendrive i patrzymy, jakie urządzenie się pojawiło. Pomyłka na tym etapie kasuje dysk systemowy.</p><h2>3. Zapis</h2><pre><code>umount /dev/sdX*
dd if=obraz.iso of=/dev/sdX bs=4M status=progress conv=fsync</code></pre><p>Zapisujemy na <strong>całe urządzenie</strong>, nie na partycję — <code>/dev/sdX</code>, nie <code>/dev/sdX1</code>.</p><h2>4. Alternatywa</h2><pre><code>cp obraz.iso /dev/sdX &amp;&amp; sync</code></pre><p>Działa dla obrazów hybrydowych i jest odporniejsza na pomyłki w parametrach.</p><h2>5. Weryfikacja zapisu</h2><pre><code>cmp -n $(stat -c%s obraz.iso) obraz.iso /dev/sdX</code></pre><p>Brak komunikatu oznacza zgodność.</p><h2>6. Gdy nośnik nie startuje</h2><ul><li>Włączony bezpieczny rozruch przy obrazie bez podpisu.</li><li>Tryb zgodności z BIOS przy obrazie tylko dla UEFI.</li><li>Zapis na partycję zamiast na urządzenie.</li><li>Port USB 3 przy starszym oprogramowaniu układowym — warto spróbować portu USB 2.</li><li>Wadliwy pendrive; te tanie psują się często i po cichu.</li></ul><h2>Czego ten materiał nie rozwiązuje</h2><p>Zapis obrazu kasuje całą zawartość nośnika. Utworzenie nośnika z kilkoma systemami wymaga innego podejścia — narzędzia, które instaluje program rozruchowy i trzyma obrazy jako pliki.</p>`,
  },
  {
    kat: 'sprzet',
    title: 'Jak ograniczyć zużycie prądu przez serwer domowy',
    excerpt: 'Pomiar, ustawienia oszczędzania i decyzje sprzętowe, które faktycznie coś dają.',
    body: `<p>Maszyna pracująca bez przerwy to koszt liczony rocznie. Zaczynamy od pomiaru, bo bez niego optymalizuje się na wyczucie.</p><h2>1. Pomiar</h2><p>Prosty watomierz na gniazdko daje wartość, do której można się odnieść. Bez niego nie da się ocenić, czy zmiany pomagają.</p><h2>2. Największe pozycje</h2><ol><li>Dyski talerzowe — kilka watów każdy, bez przerwy.</li><li>Procesor trzymany w wysokich stanach wydajności.</li><li>Zasilacz o zbyt dużej mocy, pracujący daleko od optymalnego punktu.</li><li>Karty rozszerzeń, które nie usypiają.</li></ol><h2>3. Regulator wydajności</h2><pre><code>cpupower frequency-info
cpupower frequency-set -g powersave</code></pre><h2>4. Stany uśpienia</h2><pre><code>powertop --auto-tune</code></pre><p>Narzędzie wskazuje ustawienia zwiększające zużycie i potrafi je poprawić. Zmiany nie są trwałe — warto je zapisać w usłudze startowej po sprawdzeniu, że nic nie psują.</p><h2>5. Dyski</h2><p>Konsolidacja danych na mniejszej liczbie większych dysków daje więcej niż jakiekolwiek ustawienia. Usypianie ma sens tylko przy dyskach naprawdę rzadko używanych.</p><h2>6. Uwaga o ASPM</h2><p>Włączenie oszczędzania na magistrali PCIe potrafi zauważalnie obniżyć pobór, ale bywa przyczyną zrywania łączności kart sieciowych. Zmieniamy świadomie i obserwujemy.</p><h2>7. Decyzja o sprzęcie</h2><p>Procesor o niskim TDP z wydajną częścią graficzną zwykle zużywa wielokrotnie mniej niż stary sprzęt serwerowy z drugiej ręki. Przy pracy ciągłej różnica zwraca się w rachunkach.</p><h2>Czego ten materiał nie rozwiązuje</h2><p>Agresywne oszczędzanie zwiększa opóźnienia przy wybudzaniu. Na maszynie obsługującej ruch sieciowy albo strumieniowanie objawia się to przycięciami — trzeba wyważyć, ile ta oszczędność naprawdę kosztuje.</p>`,
  },
  {
    kat: 'sprzet',
    title: 'Jak podłączyć dysk z uszkodzonego komputera i odzyskać dane',
    excerpt: 'Bezpieczna kolejność: obraz najpierw, odzyskiwanie potem.',
    body: `<p>Najważniejsza zasada: przy podejrzeniu awarii dysku najpierw robimy jego obraz, a dopiero na kopii próbujemy odzyskiwać. Każde kolejne uruchomienie podejrzanego dysku może być ostatnim.</p><h2>1. Podłączenie</h2><p>Adapter USB, stacja dokująca albo drugi komputer. Dysku <strong>nie montujemy</strong> automatycznie — środowisko graficzne potrafi zapisać na nim metadane.</p><pre><code>lsblk
dmesg -T | tail</code></pre><h2>2. Obraz w pierwszej kolejności</h2><pre><code>ddrescue -d -r3 /dev/sdb obraz.img mapa.log</code></pre><p>Narzędzie pomija uszkodzone obszary i wraca do nich później, zamiast zacinać się na pierwszym błędzie. Plik mapy pozwala wznowić przerwaną pracę — nie kasujemy go.</p><h2>3. Montowanie tylko do odczytu</h2><pre><code>mount -o ro,noload /dev/sdb1 /mnt/dane
mount -o ro,loop obraz.img /mnt/dane</code></pre><h2>4. Gdy system plików jest uszkodzony</h2><pre><code>fsck -n /dev/sdb1</code></pre><p>Przełącznik <code>-n</code> tylko sprawdza. Naprawę wykonujemy <strong>na obrazie</strong>, nigdy na oryginale — nieudana potrafi dokończyć dzieła zniszczenia.</p><h2>5. Odzyskiwanie plików</h2><pre><code>photorec obraz.img
testdisk obraz.img</code></pre><p>Pierwsze szuka plików po sygnaturach i ignoruje strukturę katalogów; drugie próbuje odtworzyć tablicę partycji.</p><h2>6. Kiedy przestać</h2><p>Stukanie, mielenie, cykliczne rozkręcanie — to oznaki awarii mechanicznej. Każda kolejna minuta pracy pogarsza sytuację. Przy naprawdę ważnych danych właściwym krokiem jest odłączenie dysku i firma specjalistyczna.</p><h2>Czego ten materiał nie rozwiązuje</h2><p>Odzyskiwanie z dysku zaszyfrowanego bez klucza jest niemożliwe. Nie obejmuje też dysków SSD, gdzie po odłączeniu zasilania kontroler potrafi utracić odwzorowanie bloków — tam szanse spadają znacznie szybciej niż przy dyskach talerzowych.</p>`,
  },
  {
    kat: 'sprzet',
    title: 'Jak skonfigurować monitorowanie temperatur i wentylatorów',
    excerpt: 'Wykrycie czujników, sterowanie obrotami i powiadomienie przy przegrzaniu.',
    body: `<p>Bez pomiaru nie wiadomo, czy chłodzenie wystarcza, a wentylatory sterowane domyślną krzywą bywają albo za głośne, albo za wolne.</p><h2>1. Wykrycie czujników</h2><pre><code>apt install lm-sensors
sensors-detect
sensors</code></pre><p>Na pytania odpowiadamy domyślnie; kilka ostatnich testów bywa oznaczonych jako ryzykowne i można je pominąć.</p><h2>2. Dyski</h2><pre><code>smartctl -A /dev/sda | grep -i temp
nvme smart-log /dev/nvme0 | grep -i temp</code></pre><h2>3. Sterowanie wentylatorami</h2><pre><code>pwmconfig
systemctl enable --now fancontrol</code></pre><p>Narzędzie po kolei zatrzymuje wentylatory i sprawdza, który obrót odpowiada któremu czujnikowi. Na czas konfiguracji nie obciążamy maszyny.</p><h2>4. Krzywa</h2><p>W <code>/etc/fancontrol</code> ustawiamy próg startu, temperaturę docelową i maksymalną. Sensowny punkt wyjścia to cisza do sześćdziesięciu stopni i wyraźne przyspieszenie powyżej siedemdziesięciu.</p><h2>5. Powiadomienie o przegrzaniu</h2><p>Prosty skrypt uruchamiany zegarem systemd, wysyłający wiadomość po przekroczeniu progu, wystarcza w domu. W większej instalacji wpina się to w system monitorowania.</p><h2>6. Weryfikacja pod obciążeniem</h2><pre><code>stress-ng --cpu 0 --timeout 20m &amp;
watch -n2 sensors</code></pre><p>Sprawdzamy, czy temperatura stabilizuje się poniżej progu dławienia, a nie tylko czy nie osiąga wartości krytycznej.</p><h2>Czego ten materiał nie rozwiązuje</h2><p>W wielu laptopach sterowanie wentylatorami jest zamknięte w oprogramowaniu układowym i niedostępne dla systemu. Tam pozostaje czyszczenie, wymiana pasty i podstawka chłodząca.</p>`,
  },
  {
    kat: 'sprzet',
    title: 'Jak dobrać dyski do serwera plików',
    excerpt: 'Pojemność, liczba sztuk i cechy, które mają znaczenie przy pracy ciągłej.',
    body: `<p>Dysk do serwera pracuje bez przerwy, obok innych, w obudowie o ograniczonym przepływie powietrza. To inne warunki niż w komputerze biurowym.</p><h2>1. Ile pojemności</h2><p>Realna dostępna pojemność zależy od poziomu macierzy: lustro to połowa, pojedyncza parzystość to suma minus jeden dysk. Do tego rezerwa — system plików zapełniony powyżej mniej więcej osiemdziesięciu procent zwalnia, a przy systemach z kopiowaniem przy zapisie fragmentuje się nieodwracalnie.</p><h2>2. Liczba dysków</h2><p>Więcej mniejszych dysków to krótsza odbudowa i lepsze rozłożenie obciążenia. Mniej dużych to niższy pobór prądu i mniej hałasu. Przy dużych pojemnościach odbudowa trwa dobę lub dłużej i to argument za podwójną parzystością.</p><h2>3. Cechy, które mają znaczenie</h2><ul><li>Przeznaczenie do pracy ciągłej — inne oprogramowanie układowe w obsłudze błędów.</li><li>Ograniczony czas prób odczytu przy błędzie; bez tego kontroler macierzy potrafi wyrzucić sprawny dysk.</li><li>Odporność na drgania przy kilku dyskach w jednej klatce.</li></ul><h2>4. Czego unikać</h2><p>Dysków z zapisem gontowym w macierzach. Przy zapisie losowym i odbudowie ich wydajność załamuje się dramatycznie, a producenci nie zawsze oznaczają to wyraźnie. Warto sprawdzić konkretny model przed zakupem.</p><h2>5. Różne serie i partie</h2><p>Dyski z jednej partii mają zbliżoną charakterystykę zużycia — i potrafią paść w podobnym czasie, czyli w trakcie odbudowy. Kupowanie w różnych terminach lub od różnych sprzedawców ogranicza to ryzyko.</p><h2>6. Test przed wdrożeniem</h2><pre><code>badblocks -wsv /dev/sdb
smartctl -t long /dev/sdb</code></pre><p>Pierwsze polecenie kasuje zawartość dysku i trwa wiele godzin. Wady fabryczne ujawniają się najczęściej na początku życia — lepiej znaleźć je przed wgraniem danych.</p><h2>Czego ten materiał nie rozwiązuje</h2><p>Żaden dobór dysków nie zastąpi kopii zapasowej poza tą maszyną. Macierz chroni przed awarią sprzętu, a nie przed pozostałymi sposobami utraty danych.</p>`,
  },
  {
    kat: 'sprzet',
    title: 'Jak uruchomić stary komputer jako coś użytecznego',
    excerpt: 'Realna ocena możliwości, dobór zastosowania i zabezpieczenie sprzętu bez wsparcia.',
    body: `<p>Stary komputer bywa użyteczny, ale nie do wszystkiego. Warto zacząć od uczciwej oceny.</p><h2>1. Co masz</h2><pre><code>lscpu
free -h
lsblk
lspci</code></pre><p>Kluczowe pytania: ile pamięci, czy jest gniazdo SATA lub M.2 i ile pobiera prądu przy pracy ciągłej.</p><h2>2. Realistyczne zastosowania</h2><ul><li>Serwer plików w sieci lokalnej.</li><li>Blokowanie reklam na poziomie DNS.</li><li>Serwer kopii zapasowych.</li><li>Zbieranie danych z czujników, automatyka domowa.</li><li>Maszyna do nauki i testów, gdzie awaria niczego nie kosztuje.</li></ul><h2>3. Czego nie warto</h2><p>Odtwarzania wideo z przekodowaniem, kompilacji, czegokolwiek wymagającego pamięci. Prąd zużyty przez starą maszynę przez rok potrafi przewyższyć cenę nowego komputera jednopłytkowego.</p><h2>4. Pierwsza inwestycja</h2><p>Dysk SSD zamiast talerzowego zmienia odczucie z pracy bardziej niż cokolwiek innego i obniża pobór prądu. Drugie w kolejności jest dołożenie pamięci, jeśli płyta pozwala.</p><h2>5. Lekki system</h2><p>Serwerowy wariant dystrybucji bez środowiska graficznego. Zarządzanie przez SSH i przeglądarkę z innej maszyny.</p><h2>6. Sprzęt bez wsparcia</h2><p>Stara płyta nie dostanie już poprawek oprogramowania układowego. Taka maszyna nie powinna być wystawiana do internetu ani obsługiwać niczego wrażliwego — sieć lokalna i zadania, których utrata nie boli.</p><h2>7. Sprawdzenie kondycji</h2><p>Przed powierzeniem czegokolwiek: test pamięci przez noc, odczyt stanu dysku, obserwacja temperatur pod obciążeniem. Kondensatory na starych płytach potrafią puchnąć — warto zajrzeć do środka.</p><h2>Czego ten materiał nie rozwiązuje</h2><p>Sprzęt sprzed kilkunastu lat pada. Nie warto stawiać na nim niczego, czego utrata byłaby dotkliwa, ani niczego bez kopii zapasowej gdzie indziej.</p>`,
  },
  {
    kat: 'sprzet',
    title: 'Jak sprawdzić, czy pendrive lub karta pamięci nie jest podrobiona',
    excerpt: 'Weryfikacja rzeczywistej pojemności zapisem i odczytem całego nośnika.',
    body: `<p>Podrobione nośniki mają zmienione oprogramowanie układowe, które zgłasza pojemność większą niż faktyczna. Zapis powyżej rzeczywistej pojemności przepada albo nadpisuje wcześniejsze dane — a wychodzi to dopiero przy próbie odczytu.</p><h2>1. Test zapisem i odczytem</h2><pre><code>f3write /media/pendrive
f3read /media/pendrive</code></pre><p>Pierwsze zapełnia nośnik plikami o znanej zawartości, drugie sprawdza, ile z nich udało się odczytać poprawnie. Test trwa tyle, ile zapis i odczyt całego nośnika.</p><h2>2. Wariant na urządzeniu blokowym</h2><pre><code>badblocks -wsv /dev/sdX</code></pre><p>Kasuje całą zawartość. Zapisuje wzorce i sprawdza je przy odczycie — wykryje zarówno fałszywą pojemność, jak i uszkodzone obszary.</p><h2>3. Co znaczy wynik</h2><ul><li>Wszystko odczytane poprawnie — pojemność jest prawdziwa.</li><li>Poprawne tylko pierwsze gigabajty — klasyczna podróbka.</li><li>Losowe błędy w różnych miejscach — nośnik wadliwy albo zużyty.</li></ul><h2>4. Szybkość jako wskazówka</h2><pre><code>dd if=/dev/zero of=/media/pendrive/proba bs=1M count=1000 oflag=direct</code></pre><p>Podróbki bywają wyraźnie wolniejsze, niż deklaruje opakowanie — ale sama niska prędkość nie dowodzi jeszcze fałszerstwa.</p><h2>5. Kiedy to sprawdzać</h2><p>Zawsze przy nośniku z niepewnego źródła i zawsze przed powierzeniem mu kopii zapasowej albo danych z aparatu. Karta, która „zgubiła zdjęcia z wakacji", to zwykle właśnie ten przypadek.</p><h2>Czego ten materiał nie rozwiązuje</h2><p>Test kasuje dane i zużywa jeden pełny cykl zapisu całego nośnika. Nie wykryje też problemów, które ujawnią się dopiero po miesiącach — pamięć flash traci dane z czasem, zwłaszcza w tanich nośnikach trzymanych w szufladzie.</p>`,
  },
  {
    kat: 'sprzet',
    title: 'Jak podłączyć dysk sieciowy tak, żeby działał szybko i pewnie',
    excerpt: 'Wybór między NFS a SMB, opcje montowania i najczęstsze przyczyny wolnych transferów.',
    body: `<p>Ten sam sprzęt potrafi dawać bardzo różne prędkości zależnie od protokołu i opcji montowania.</p><h2>1. Który protokół</h2><ul><li><strong>NFS</strong> — między maszynami z Linuksem; szybszy przy dużych plikach, dobrze zachowuje uprawnienia uniksowe.</li><li><strong>SMB</strong> — gdy w grze są Windows lub macOS; nowsze wersje protokołu są znacznie wydajniejsze od pierwszej.</li></ul><h2>2. Montowanie NFS</h2><pre><code>mount -t nfs4 -o rw,hard,noatime serwer:/eksport /mnt/dane</code></pre><p>Twarde montowanie oznacza czekanie przy niedostępnym serwerze zamiast błędu — bezpieczniejsze przy zapisie, uciążliwe przy awarii.</p><h2>3. Montowanie SMB</h2><pre><code>mount -t cifs //serwer/udzial /mnt/udzial \\
  -o credentials=/etc/samba/creds,vers=3.1.1,uid=1000,gid=1000,iocharset=utf8</code></pre><p>Jawne wskazanie wersji protokołu bywa konieczne — automatyczne uzgadnianie czasem cofa się do wolniejszej.</p><h2>4. Gdy transfer jest wolny</h2><ul><li>Zmierz samą sieć przez iperf3 — jeśli tam też jest wolno, protokół nie jest winny.</li><li>Sprawdź wynegocjowaną prędkość karty.</li><li>Przy wielu małych plikach narzut na plik dominuje; spakuj przed przesłaniem.</li><li>Sprawdź prędkość dysku po drugiej stronie.</li></ul><h2>5. Trwałe montowanie</h2><p>Wpis w <code>fstab</code> z opcjami <code>_netdev</code>, <code>nofail</code> i automatycznym montowaniem — bez nich rozruch potrafi się zawiesić przy niedostępnym serwerze.</p><h2>6. Uprawnienia</h2><p>Przy NFS liczą się numery użytkowników po obu stronach. Rozjazd numeracji objawia się plikami należącymi do nieznanego użytkownika i odmową zapisu.</p><h2>Czego ten materiał nie rozwiązuje</h2><p>Na dysku sieciowym nie umieszcza się plików bazy danych ani obrazów maszyn wirtualnych, chyba że protokół i konfiguracja są pod to przygotowane. Zerwanie połączenia w trakcie zapisu potrafi uszkodzić dane nieodwracalnie.</p>`,
  },
  {
    kat: 'sprzet',
    title: 'Jak zaktualizować oprogramowanie układowe płyty i dysków',
    excerpt: 'Bezpieczna procedura, weryfikacja i sytuacje, w których lepiej nie aktualizować.',
    body: `<p>Aktualizacja oprogramowania układowego naprawia realne problemy, ale przerwana w trakcie potrafi unieruchomić sprzęt.</p><h2>1. Czy w ogóle warto</h2><p>Aktualizujemy, gdy: rozwiązuje konkretny problem, który mamy; łata podatność; jest wymagana przez nowy podzespół. Nie aktualizujemy „na wszelki wypadek" na maszynie, która działa stabilnie.</p><h2>2. Co masz teraz</h2><pre><code>dmidecode -s bios-version
dmidecode -s bios-release-date
smartctl -i /dev/sda | grep -i firmware
nvme id-ctrl /dev/nvme0 | grep -i fr</code></pre><h2>3. Mechanizm w Linuksie</h2><pre><code>fwupdmgr refresh
fwupdmgr get-updates
fwupdmgr update</code></pre><p>Obsługuje rosnącą liczbę urządzeń. Gdy sprzęt jest wspierany, to najbezpieczniejsza droga.</p><h2>4. Przygotowanie do aktualizacji ręcznej</h2><ul><li>Zasilanie awaryjne albo naładowana bateria — zanik prądu w trakcie zwykle kończy sprawę.</li><li>Zapis obecnych ustawień, bo aktualizacja je czyści.</li><li>Kopia danych, jeśli aktualizujemy dysk.</li><li>Sprawdzenie, że plik pasuje do dokładnego modelu i wersji płyty.</li></ul><h2>5. Dyski</h2><p>Aktualizacja oprogramowania dysku bywa konieczna — zdarzały się serie z błędami powodującymi utratę danych po określonej liczbie godzin pracy. Warto sprawdzić, czy nasz model jest objęty ostrzeżeniem producenta.</p><h2>6. Po aktualizacji</h2><p>Sprawdzamy ustawienia, bo zostały zresetowane: kolejność rozruchu, tryb pracy kontrolera dysków, profil pamięci, wirtualizacja. Zmiana trybu kontrolera potrafi sprawić, że system nie wstanie.</p><h2>Czego ten materiał nie rozwiązuje</h2><p>Odwrócenie aktualizacji bywa niemożliwe — część producentów blokuje wgranie starszej wersji. Przy sprzęcie krytycznym warto poczekać, aż nowa wersja będzie chwilę na rynku.</p>`,
  },
  {
    kat: 'sprzet',
    title: 'Jak zdiagnozować komputer, który się nie uruchamia',
    excerpt: 'Kolejność sprawdzania od zasilania po podzespoły — bez wymiany na oślep.',
    body: `<p>„Nie startuje" obejmuje kilka różnych sytuacji. Najpierw ustalamy, jak daleko dochodzi.</p><h2>1. Co się dzieje po naciśnięciu przycisku</h2><ul><li><strong>Zupełny brak reakcji</strong> — zasilanie, przycisk, kabel.</li><li><strong>Wentylatory ruszają, brak obrazu</strong> — pamięć, karta graficzna, procesor.</li><li><strong>Obraz jest, system nie wstaje</strong> — dysk, program rozruchowy, system.</li></ul><h2>2. Brak reakcji</h2><p>Sprawdzamy przełącznik na zasilaczu i kabel. Zwieramy na moment styki przycisku zasilania na płycie — jeśli maszyna ruszy, winny jest przycisk w obudowie. Test zasilacza polega na podmianie na sprawny.</p><h2>3. Brak obrazu</h2><ol><li>Wyjmujemy wszystkie moduły pamięci i próbujemy z jednym, w gnieździe zalecanym w instrukcji.</li><li>Wyjmujemy kartę graficzną i podłączamy monitor do wyjścia na płycie, jeśli procesor ma układ graficzny.</li><li>Odłączamy wszystkie dyski i urządzenia USB.</li><li>Resetujemy ustawienia zworką lub wyjęciem baterii na kilka minut.</li></ol><h2>4. Sygnały diagnostyczne</h2><p>Wiele płyt sygnalizuje etap rozruchu diodami albo kodem na wyświetlaczu, część brzęczykiem. Znaczenie sygnałów jest w instrukcji płyty — to najszybsza droga do przyczyny.</p><h2>5. Praca poza obudową</h2><p>Płyta na pudełku kartonowym, z procesorem, chłodzeniem, jednym modułem pamięci i zasilaczem. Eliminuje to zwarcie do obudowy — częstą przyczynę po nieudanym montażu.</p><h2>6. Obraz jest, system nie wstaje</h2><p>Sprawdzamy, czy dysk jest widoczny w ustawieniach płyty. Widoczny dysk i brak systemu to sprawa dla nośnika ratunkowego i naprawy programu rozruchowego.</p><h2>Czego ten materiał nie rozwiązuje</h2><p>Bez zapasowych podzespołów do podmiany diagnostyka bywa niekonkluzywna. Objawy procesora, płyty i zasilacza potrafią być identyczne — to główny argument, żeby nie kupować części na podstawie samego domysłu.</p>`,
  },
  {
    kat: 'sprzet',
    title: 'Jak skonfigurować UPS, żeby faktycznie chronił dane',
    excerpt: 'Podłączenie, usługa nadzorująca i test, bez którego to tylko przedłużacz.',
    body: `<p>Sam UPS nie chroni danych. Chroni je dopiero automatyczne, kontrolowane wyłączenie systemu przed wyczerpaniem baterii.</p><h2>1. Podłączenie</h2><p>Kabel danych — zwykle USB — między UPS a maszyną. Bez niego system nie wie, że zabrakło prądu.</p><pre><code>lsusb</code></pre><h2>2. Instalacja usługi</h2><pre><code>apt install nut nut-client nut-server</code></pre><h2>3. Wykrycie urządzenia</h2><pre><code>nut-scanner -U</code></pre><p>Wynik przepisujemy do <code>/etc/nut/ups.conf</code>.</p><h2>4. Konfiguracja</h2><p>Po ustawieniu użytkownika i uprawnień w plikach konfiguracyjnych uruchamiamy usługi i sprawdzamy odczyt:</p><pre><code>systemctl enable --now nut-server nut-monitor
upsc nazwa@localhost</code></pre><p>Widzimy stan naładowania, obciążenie i szacowany czas podtrzymania.</p><h2>5. Kiedy wyłączać</h2><p>Próg ustawiamy tak, żeby zostało zapasu na pełne wyłączenie — zwykle kilka minut albo określony procent naładowania. Wyłączenie natychmiast po zaniku prądu jest niepotrzebne przy krótkich przerwach; czekanie do końca baterii mija się z celem.</p><h2>6. Test — krok obowiązkowy</h2><p>Wyciągamy wtyczkę UPS z gniazdka i obserwujemy, czy system rzeczywiście się wyłącza. Konfiguracja nieprzetestowana to konfiguracja nieznana.</p><h2>7. Wiele maszyn</h2><p>Jedna maszyna pełni rolę nadzorcy, pozostałe łączą się z nią przez sieć i wyłączają na jej sygnał.</p><h2>Czego ten materiał nie rozwiązuje</h2><p>Baterie zużywają się w kilka lat i degradują cicho. UPS nietestowany od zakupu w chwili awarii często podtrzymuje zasilanie kilkanaście sekund. Test obciążeniowy raz na jakiś czas jest częścią utrzymania, nie dodatkiem.</p>`,
  },
  {
    kat: 'sprzet',
    title: 'Jak sprawdzić wydajność dysku i porównać ją z deklaracjami',
    excerpt: 'Pomiar sekwencyjny i losowy, z omijaniem pamięci podręcznej.',
    body: `<p>Większość szybkich pomiarów mierzy pamięć podręczną systemu, nie dysk. Wyniki bywają przez to bezużyteczne.</p><h2>1. Szybki pomiar sekwencyjny</h2><pre><code>dd if=/dev/zero of=proba bs=1M count=4000 oflag=direct
dd if=proba of=/dev/null bs=1M iflag=direct
rm proba</code></pre><p>Flaga <code>direct</code> omija pamięć podręczną. Bez niej wynik pokazuje przepustowość RAM.</p><h2>2. Pomiar rzetelny</h2><pre><code>fio --name=zapis --rw=write --bs=1M --size=4G --direct=1 --ioengine=libaio
fio --name=losowy --rw=randread --bs=4k --size=1G --direct=1 --iodepth=32 --ioengine=libaio</code></pre><p>Odczyt losowy blokami po cztery kilobajty to miara najbliższa realnej pracy systemu i bazy danych — i tam różnica między SSD a dyskiem talerzowym jest stukrotna, a nie kilkukrotna.</p><h2>3. Rozmiar próbki ma znaczenie</h2><p>Plik mniejszy niż bufor dysku albo niż pamięć podręczna mierzy bufor. Przy dyskach SSD z buforem jednobitowym pomiar musi przekroczyć jego rozmiar, żeby pokazać prędkość podtrzymaną — inaczej zobaczymy wartość, której dysk nie utrzyma przy większym transferze.</p><h2>4. Opóźnienie</h2><pre><code>ioping -c 20 /sciezka</code></pre><p>Przy bazach danych opóźnienie bywa ważniejsze od przepustowości.</p><h2>5. Kontekst</h2><pre><code>iostat -x 1
smartctl -a /dev/sda | grep -i temp</code></pre><p>Dysk pod obciążeniem potrafi się grzać i ograniczyć prędkość — warto obserwować temperaturę w trakcie pomiaru.</p><h2>Czego ten materiał nie rozwiązuje</h2><p>Testy zapisu zużywają nośnik i kasują dane w miejscu zapisu. Wykonujemy je na pustym dysku albo w pliku, nigdy bezpośrednio na urządzeniu z danymi. Wyniki są też nieporównywalne między systemami plików i konfiguracjami — mają sens jako punkt odniesienia dla tej jednej maszyny.</p>`,
  },
  {
    kat: 'sprzet',
    title: 'Jak przygotować sprzęt do sprzedaży lub utylizacji',
    excerpt: 'Skuteczne usunięcie danych z dysków talerzowych, SSD i urządzeń wbudowanych.',
    body: `<p>Formatowanie nie usuwa danych — kasuje tablicę i zostawia zawartość. Odzyskanie plików z „sformatowanego" dysku to kwestia kilku minut.</p><h2>1. Dysk talerzowy</h2><pre><code>shred -vn1 /dev/sdX
# albo
dd if=/dev/urandom of=/dev/sdX bs=1M status=progress</code></pre><p>Jedno przejście wystarcza przy współczesnych dyskach. Wielokrotne nadpisywanie jest pozostałością po technologiach sprzed dekad.</p><h2>2. Dysk SSD — inaczej</h2><p>Nadpisywanie nie działa: kontroler zapisuje gdzie indziej, a stare komórki zostają. Właściwa metoda to firmowe polecenie kasowania:</p><pre><code>hdparm --user-master u --security-set-pass haslo /dev/sdX
hdparm --user-master u --security-erase haslo /dev/sdX</code></pre><p>Dla NVMe:</p><pre><code>nvme format /dev/nvme0 --ses=1</code></pre><h2>3. Metoda najpewniejsza</h2><p>Szyfrowanie całego nośnika od pierwszego dnia i zniszczenie klucza przy pozbywaniu się sprzętu. Dane bez klucza są nieczytelne niezależnie od tego, co zostało w komórkach.</p><h2>4. Weryfikacja</h2><pre><code>hexdump -C -n 1048576 /dev/sdX
photorec /dev/sdX</code></pre><p>Drugie polecenie próbuje odzyskać pliki — brak wyników jest potwierdzeniem.</p><h2>5. Nie tylko dyski</h2><p>Dane zostają też w telefonach, routerach, drukarkach z dyskiem, kamerach i konsolach. Router trzyma hasła do Wi-Fi i konfigurację; przywrócenie ustawień fabrycznych to minimum.</p><h2>6. Konta i powiązania</h2><p>Wylogowanie z kont, usunięcie urządzenia z listy zaufanych, wyłączenie blokad powiązanych z kontem producenta. Sprzęt z aktywną blokadą jest dla kupującego bezużyteczny.</p><h2>Czego ten materiał nie rozwiązuje</h2><p>Uszkodzonego dysku, który się nie zgłasza, nie da się wyczyścić programowo. Przy danych wrażliwych jedyną pewną metodą pozostaje fizyczne zniszczenie nośnika.</p>`,
  },
];
