/**
 * Słownik pojęć do linkowania wewnętrznego.
 *
 * Klucz to adres hasła wiki, wartość to formy, w jakich pojęcie występuje
 * w tekstach. Formy wypisujemy JAWNIE zamiast odmieniać automatycznie:
 * polska fleksja z regułami dałaby trafienia w rodzaju „karta" w zdaniu
 * o karcie płatniczej, a fałszywy odnośnik jest gorszy niż jego brak.
 *
 * Kolejność ma znaczenie — formy dłuższe muszą stać przed krótszymi,
 * żeby „wykrywanie MTU ścieżki" nie zostało zjedzone przez samo „MTU".
 */
export const SLOWNIK = [
  // ── Sieć ────────────────────────────────────────────────────────
  ['wykrywanie-mtu-sciezki', ['wykrywanie MTU ścieżki', 'wykrywania MTU ścieżki']],
  ['mtu-i-fragmentacja', ['MTU']],
  ['cgnat', ['CGNAT']],
  ['nat', ['NAT']],
  ['conntrack', ['conntrack']],
  ['quic', ['QUIC']],
  ['sni', ['SNI']],
  ['anycast', ['anycast', 'Anycast']],
  ['bgp', ['BGP']],
  ['odwrotne-proxy', ['odwrotne proxy', 'odwrotnego proxy', 'odwrotnym proxy']],
  ['slaac', ['SLAAC']],
  ['arp', ['ARP']],
  ['vlan', ['VLAN']],
  ['ramki-jumbo', ['ramki jumbo', 'ramek jumbo']],
  ['keepalive', ['keepalive']],
  ['rekordy-dns', ['rekord TXT', 'rekordy DNS']],
  ['dns-over-https-i-dns-over-tls', ['DoH', 'szyfrowany DNS', 'szyfrowanego DNS']],
  ['uzgadnianie-trojfazowe-tcp', ['uzgadnianie trójfazowe']],
  ['algorytmy-kontroli-przeciazenia', ['kontrola przeciążenia', 'kontroli przeciążenia']],
  ['odciazanie-karty-sieciowej-offloading', ['odciążanie', 'odciążania']],
  ['rozdzielony-tunel-split-tunneling', ['rozdzielony tunel', 'rozdzielonego tunelu']],

  // ── System ──────────────────────────────────────────────────────
  ['przestrzenie-nazw-namespaces', ['przestrzenie nazw', 'przestrzeni nazw', 'przestrzeniami nazw']],
  ['cgroups', ['cgroups', 'cgroup']],
  ['oom-killer', ['OOM killer', 'OOM killera']],
  ['swappiness', ['swappiness']],
  ['tmpfs', ['tmpfs']],
  ['jednostka-systemd', ['jednostce systemd', 'jednostka systemd', 'jednostki systemd']],
  ['initramfs', ['initramfs']],
  ['lvm', ['LVM']],
  ['poziomy-raid', ['RAID 6', 'RAID 5', 'poziom RAID']],
  ['journald', ['journald']],
  ['udev', ['udev']],
  ['bit-setuid', ['setuid']],
  ['umask', ['umask']],
  ['dowiazanie-twarde-a-symboliczne', ['dowiązania twarde', 'dowiązaniom twardym', 'dowiązanie symboliczne']],
  ['overlayfs', ['overlayfs', 'Overlayfs']],
  ['kopiowanie-przy-zapisie-copy-on-write', ['kopiowanie przy zapisie', 'kopiowaniem przy zapisie', 'kopiowania przy zapisie']],
  ['noatime', ['noatime']],
  ['chroot', ['chroot']],
  ['zram', ['zram']],
  ['i-wezel-inode', ['i-węzeł', 'i-węzła', 'i-węzłów', 'i-węźle']],

  // ── Kod ─────────────────────────────────────────────────────────
  ['rebase-a-merge', ['rebase']],
  ['wersjonowanie-semantyczne', ['wersjonowanie semantyczne', 'wersjonowania semantycznego']],
  ['warstwy-obrazu-dockera', ['warstwy obrazu', 'warstw obrazu', 'warstwach obrazu']],
  ['wolumen-a-montowanie-katalogu', ['montowanie katalogu', 'montowania katalogu', 'montowaniu katalogu']],
  ['jwt', ['JWT']],
  ['cors', ['CORS']],
  ['wyscig-race-condition', ['wyścig', 'wyścigu', 'wyścigi']],
  ['indeks-w-bazie-danych', ['indeks na wyrażeniu', 'indeksu w bazie']],
  ['problem-n-1-zapytan', ['problem N+1', 'N+1']],
  ['idempotentnosc', ['idempotentna', 'idempotentne', 'idempotentność', 'idempotentności']],
  ['wykladnicze-wycofywanie-exponential-backoff', ['wykładnicze wycofywanie', 'wykładniczego wycofywania']],
  ['utf-8', ['UTF-8']],
  ['liczby-zmiennoprzecinkowe', ['liczby zmiennoprzecinkowe', 'zmiennoprzecinkowym']],
  ['argon2-i-bcrypt', ['Argon2', 'bcrypt']],
  ['zapytanie-przygotowane', ['zapytanie przygotowane', 'zapytania przygotowanego', 'zapytaniu przygotowanym']],
  ['poziomy-izolacji-transakcji', ['poziom izolacji', 'poziomie izolacji', 'poziomu izolacji']],
  ['pula-polaczen', ['pula połączeń', 'puli połączeń']],
  ['ograniczanie-tempa-zadan-rate-limiting', ['ograniczanie tempa', 'ograniczania tempa', 'ograniczaniem tempa']],
  ['uniewaznianie-pamieci-podrecznej', ['unieważnianie pamięci podręcznej', 'unieważniania pamięci podręcznej']],
  ['kolejnosc-wczytywania-zmiennych-srodowiskowych', ['kolejność wczytywania']],

  // ── Sprzęt ──────────────────────────────────────────────────────
  ['tdp', ['TDP']],
  ['linie-pci-express', ['linie PCIe', 'linii PCIe', 'linią PCIe']],
  ['m-2-a-nvme', ['M.2']],
  ['trim', ['TRIM']],
  ['s-m-a-r-t', ['S.M.A.R.T.']],
  ['pamiec-ecc', ['pamięć ECC', 'pamięci ECC', 'ECC']],
  ['xmp-i-expo', ['XMP', 'EXPO']],
  ['stany-c-i-stany-p', ['stany C', 'stanów C', 'stanach C']],
  ['iommu', ['IOMMU']],
  ['certyfikaty-80-plus', ['80 PLUS']],
  ['hba-a-kontroler-raid', ['HBA']],
  ['ipmi-i-bmc', ['IPMI', 'BMC']],
  ['tpm', ['TPM']],
  ['standardy-usb', ['standardy USB', 'standardów USB']],
  ['poe', ['PoE']],
  ['ups', ['UPS']],
  ['dlawienie-termiczne', ['dławienie termiczne', 'dławienia termicznego', 'dławieniem termicznym']],
  ['wyrownywanie-zuzycia-wear-leveling', ['wyrównywanie zużycia', 'wyrównywaniu zużycia']],
  ['hdmi-a-displayport', ['DisplayPort']],
  ['bufor-slc-w-dyskach-ssd', ['buforem jednobitowym', 'bufor jednobitowy']],
  ['aspm', ['ASPM']],

  // ── Bezpieczeństwo ──────────────────────────────────────────────
  ['totp', ['TOTP']],
  ['fido2-i-klucze-sprzetowe', ['klucze sprzętowe', 'kluczy sprzętowych', 'kluczami sprzętowymi', 'FIDO2']],
  ['cve-i-cvss', ['CVSS', 'CVE']],
  ['xss', ['XSS']],
  ['csrf', ['CSRF']],
  ['ssrf', ['SSRF']],
  ['content-security-policy', ['polityki bezpieczeństwa treści', 'CSP']],
  ['hsts', ['HSTS']],
  ['acme-i-let-s-encrypt', ['ACME']],
  ['fail2ban', ['fail2ban']],
  ['zasada-najmniejszych-uprawnien', ['zasada najmniejszych uprawnień', 'zasady najmniejszych uprawnień', 'najmniejszych uprawnień']],
  ['zasada-3-2-1-dla-kopii-zapasowych', ['3-2-1']],
  ['wypelnianie-skradzionymi-poswiadczeniami', ['credential stuffing']],
  ['atak-na-lancuch-dostaw', ['atak na łańcuch dostaw', 'ataku na łańcuch dostaw', 'łańcuch dostaw']],
  ['model-zagrozen', ['model zagrożeń', 'modelu zagrożeń']],
  ['symetryczne-a-asymetryczne-szyfrowanie', ['szyfrowanie asymetryczne', 'szyfrowaniem asymetrycznym']],
  ['urzad-certyfikacji', ['urząd certyfikacji', 'urzędu certyfikacji', 'urzędem certyfikacji']],
  ['klucze-ssh', ['klucze SSH', 'kluczy SSH', 'kluczem SSH']],
  ['spf-dkim-i-dmarc', ['DMARC', 'DKIM', 'SPF']],
  ['szyfrowanie-w-spoczynku-a-w-tranzycie', ['szyfrowanie w spoczynku', 'szyfrowania w spoczynku']],
];
