/** Hasła wiki — Sprzęt. */
export default [
  {
    kat: 'sprzet',
    title: 'TDP',
    excerpt: 'Projektowa moc cieplna procesora — liczba mówiąca o chłodzeniu, nie o poborze prądu.',
    body: `<p><strong>TDP</strong> (Thermal Design Power) to wartość podawana przez producenta jako wskazówka dla projektanta chłodzenia: ile ciepła układ oddaje przy typowym obciążeniu w warunkach nominalnych.</p><h2>Czym TDP nie jest</h2><p>To nie jest maksymalny pobór mocy. Współczesne procesory w krótkich zrywach pobierają wyraźnie więcej, korzystając z bezwładności cieplnej. Producenci mają na to osobne parametry określające moc krótkotrwałą i długotrwałą.</p><h2>Dlaczego liczby bywają nieporównywalne</h2><p>Producenci mierzą TDP w różnych warunkach i przy różnych częstotliwościach bazowych. Porównywanie samych liczb między markami niewiele mówi — dwa układy o tej samej wartości potrafią zachowywać się zupełnie inaczej pod obciążeniem.</p><h2>Praktyczne znaczenie</h2><p>Przy doborze chłodzenia TDP to punkt wyjścia, nie wynik. Chłodzenie dobrane dokładnie na tę wartość utrzyma układ przy życiu, ale będzie go ograniczać w dłuższym obciążeniu. Zapas rzędu kilkudziesięciu procent to normalna praktyka.</p><h2>Zasilacz</h2><p>Do doboru zasilacza TDP procesora jest daleko niewystarczające — liczy się szczytowy pobór całego układu, w tym karty graficznej, która potrafi mieć skoki znacznie przekraczające jej wartość nominalną.</p>`,
  },
  {
    kat: 'sprzet',
    title: 'Linie PCI Express',
    excerpt: 'Waluta, w której rozlicza się przepustowość do procesora — i powód, dla którego drugi dysk spowalnia kartę.',
    body: `<p><strong>Linia PCIe</strong> to para różnicowa służąca do komunikacji między urządzeniem a procesorem lub chipsetem. Urządzenia opisuje się liczbą linii: x1, x4, x8, x16.</p><h2>Skończona pula</h2><p>Procesor udostępnia ograniczoną liczbę linii — w komputerach domowych zwykle rzędu dwudziestu kilku. Reszta gniazd wisi na chipsecie, który sam łączy się z procesorem wąskim gardłem współdzielonym przez wszystko, co jest do niego podpięte.</p><h2>Konsekwencja praktyczna</h2><p>Zamontowanie dysku NVMe w drugim gnieździe M.2 często przełącza gniazdo karty graficznej z x16 na x8 albo odbiera linie portom SATA. Producenci opisują to drobnym drukiem w instrukcji płyty — i jest to jedyne wiarygodne źródło.</p><h2>Wersje</h2><p>Każda kolejna wersja PCIe podwaja przepustowość na linię. Dlatego karta na x8 w nowszej wersji może mieć tyle samo przepustowości co x16 w starszej. Urządzenia działają wstecz i w przód, negocjując najniższy wspólny standard.</p><h2>Kiedy to naprawdę boli</h2><p>Karta graficzna na x8 w nowoczesnym standardzie traci pomijalnie mało. Problem pojawia się przy kartach fabrycznie okrojonych do x4 wstawionych do starszej płyty — tam ograniczenie bywa dotkliwe.</p>`,
  },
  {
    kat: 'sprzet',
    title: 'M.2 a NVMe',
    excerpt: 'Format fizyczny to nie to samo co protokół — stąd dyski M.2, które są wolne jak SATA.',
    body: `<p><strong>M.2</strong> to format fizyczny — kształt płytki i złącza. <strong>NVMe</strong> to protokół komunikacji z pamięcią masową przez PCIe. To dwie różne rzeczy i mylenie ich bywa kosztowne.</p><h2>Dysk M.2 na SATA</h2><p>Istnieją dyski w formacie M.2 komunikujące się przez SATA. Wyglądają identycznie, mieszczą się w tym samym gnieździe, a osiągają wydajność zwykłego dysku SATA — kilkakrotnie niższą od NVMe.</p><h2>Nacięcia w złączu</h2><p>Rozróżnia je układ wycięć: klucz B, klucz M albo oba. Dysk z dwoma nacięciami to zwykle wariant SATA, z jednym w pozycji M — NVMe. Nie każde gniazdo na płycie obsługuje oba tryby.</p><h2>Długość</h2><p>Oznaczenia typu 2280 to szerokość i długość w milimetrach: 22 na 80. Krótsze warianty spotyka się w laptopach i konsolach przenośnych — przed zakupem warto sprawdzić, co mieści się w obudowie.</p><h2>Chłodzenie</h2><p>Szybkie dyski NVMe pod długim obciążeniem osiągają temperatury wymuszające ograniczenie prędkości. Objaw to transfer zaczynający się świetnie i spadający po kilkudziesięciu sekundach — nie awaria, tylko zabezpieczenie termiczne.</p>`,
  },
  {
    kat: 'sprzet',
    title: 'TRIM',
    excerpt: 'Polecenie informujące dysk SSD, które bloki są nieużywane — warunek utrzymania wydajności zapisu.',
    body: `<p><strong>TRIM</strong> to polecenie, którym system plików mówi dyskowi SSD, że dane bloki nie zawierają już potrzebnych danych.</p><h2>Skąd potrzeba</h2><p>Pamięć NAND kasuje się większymi jednostkami niż zapisuje. Bez TRIM kontroler nie wie, że blok jest wolny, i przed zapisem musi go najpierw przenieść i skasować. Objawia się to stopniowym spadkiem prędkości zapisu z czasem użytkowania.</p><h2>Dwa tryby</h2><ul><li><strong>Odrzucanie ciągłe</strong> — opcja montowania <code>discard</code>, wysyła polecenie przy każdym skasowaniu pliku. Bywa źródłem przycięć, bo obciąża kontroler w losowych momentach.</li><li><strong>Okresowe</strong> — zadanie uruchamiane co jakiś czas. To zalecane podejście w większości dystrybucji.</li></ul><pre><code>systemctl enable --now fstrim.timer
fstrim -av</code></pre><h2>Warstwy pośrednie</h2><p>Polecenie musi przejść przez cały stos: system plików, ewentualne szyfrowanie, LVM, macierz RAID. Każda z tych warstw może je zatrzymać — LUKS wymaga jawnego włączenia obsługi, część kontrolerów RAID nie przekazuje TRIM w ogóle.</p><h2>Uwaga o szyfrowaniu</h2><p>Włączenie TRIM na wolumenie szyfrowanym ujawnia, które obszary dysku są puste. Dla większości zastosowań to akceptowalne, ale w modelu zagrożeń wymagającym ukrycia samego faktu istnienia danych — nie.</p>`,
  },
  {
    kat: 'sprzet',
    title: 'S.M.A.R.T.',
    excerpt: 'Samodiagnostyka dysku — które atrybuty naprawdę zapowiadają awarię, a które nie znaczą nic.',
    body: `<p><strong>S.M.A.R.T.</strong> to zestaw liczników i testów prowadzonych przez sam dysk, udostępniających informacje o jego stanie.</p><h2>Atrybuty warte uwagi w dyskach talerzowych</h2><ul><li><strong>Reallocated Sector Count</strong> — sektory przeniesione po wykryciu błędu. Wartość rosnąca to poważny sygnał.</li><li><strong>Current Pending Sector</strong> — sektory podejrzane, czekające na rozstrzygnięcie. Najsilniejszy pojedynczy zwiastun kłopotów.</li><li><strong>Offline Uncorrectable</strong> — błędy, których nie dało się naprawić.</li></ul><h2>W dyskach SSD</h2><p>Kluczowe są <strong>Percentage Used</strong> lub odpowiednik oraz <strong>Media Wear Indicator</strong> — mówią o zużyciu komórek. Liczba zapisanych bajtów pozwala porównać je z wytrzymałością deklarowaną przez producenta.</p><h2>Czego nie brać za awarię</h2><p>Wysokie surowe wartości niektórych atrybutów wynikają ze sposobu kodowania przez producenta i nie znaczą nic. Dotyczy to zwłaszcza liczników błędów odczytu w dyskach niektórych marek, gdzie duża liczba jest normą.</p><h2>Test na żądanie</h2><pre><code>smartctl -a /dev/sda
smartctl -t long /dev/sda</code></pre><h2>Ograniczenie</h2><p>Znaczna część dysków pada bez żadnego wcześniejszego ostrzeżenia w S.M.A.R.T. Czyste odczyty nie są powodem do rezygnacji z kopii zapasowych.</p>`,
  },
  {
    kat: 'sprzet',
    title: 'Pamięć ECC',
    excerpt: 'Pamięć z korekcją błędów — co realnie wykrywa i kiedy ma sens poza serwerownią.',
    body: `<p><strong>ECC</strong> (Error-Correcting Code) to pamięć z dodatkowymi bitami pozwalającymi wykryć i naprawić przekłamania.</p><h2>Możliwości</h2><p>Standardowa odmiana naprawia błąd pojedynczego bitu i wykrywa błąd dwóch bitów w słowie. Błąd naprawiony jest odnotowywany, więc administrator widzi degradujący się moduł, zanim ten zacznie psuć dane.</p><h2>Skąd biorą się błędy</h2><p>Promieniowanie kosmiczne, zakłócenia elektryczne, starzenie się modułów. Zdarzenia są rzadkie, ale rosną z ilością pamięci i czasem pracy — maszyna z dużą ilością RAM działająca bez przerwy zobaczy je prędzej czy później.</p><h2>Gdzie to naprawdę ma znaczenie</h2><p>Tam, gdzie przekłamanie zostaje utrwalone: serwery plików, bazy danych, systemy z sumami kontrolnymi w rodzaju ZFS. Przekłamany bit w pamięci zostanie zapisany razem z poprawną sumą kontrolną i nikt nie zauważy, że dane są uszkodzone.</p><h2>Wymagania</h2><p>ECC musi być obsługiwane przez procesor, chipset i płytę. Moduły ECC w niewspierającej płycie albo nie wystartują, albo zadziałają bez korekcji — o czym system nie poinformuje.</p><h2>Koszt</h2><p>Moduły są droższe i zwykle wolniejsze. W stacji roboczej do gier zysk jest bliski zeru; w serwerze plików trzymającym rodzinne archiwum przez dekadę — realny.</p>`,
  },
  {
    kat: 'sprzet',
    title: 'XMP i EXPO',
    excerpt: 'Profile podkręcania pamięci zapisane w module — działające dopiero po włączeniu w BIOS-ie.',
    body: `<p><strong>XMP</strong> i <strong>EXPO</strong> to zapisane w module pamięci profile z docelowymi częstotliwościami, opóźnieniami i napięciem.</p><h2>Dlaczego pamięć chodzi wolniej niż na pudełku</h2><p>Bez włączonego profilu moduł startuje z częstotliwością bazową ze standardowej tablicy — wyraźnie niższą od reklamowanej. To najczęstsza przyczyna pytania „kupiłem szybkie kości, a system pokazuje mniej". Profil trzeba włączyć ręcznie w ustawieniach płyty.</p><h2>To jest podkręcanie</h2><p>Formalnie praca z profilem wykracza poza specyfikację standardu i nie jest objęta gwarancją stabilności procesora. W praktyce działa u ogromnej większości, ale niestabilność po włączeniu profilu nie jest usterką pamięci.</p><h2>Skąd biorą się problemy</h2><p>Kontroler pamięci jest w procesorze i każdy egzemplarz ma inne możliwości. Cztery moduły obciążają go bardziej niż dwa, więc zestaw działający w dwóch kościach potrafi nie wystartować w czterech.</p><h2>Weryfikacja stabilności</h2><p>Po włączeniu profilu warto uruchomić dłuższy test pamięci. Błędy pamięci objawiają się losowymi zawieszeniami i uszkodzeniami plików, których nikt nie wiąże z pamięcią, dopóki ich nie zmierzy.</p><h2>EXPO a XMP</h2><p>To dwa oznaczenia tego samego pomysłu, promowane przez różnych producentów. Moduł z jednym profilem zwykle działa na obu platformach, choć nie zawsze z pełnymi ustawieniami.</p>`,
  },
  {
    kat: 'sprzet',
    title: 'Stany C i stany P',
    excerpt: 'Dwa niezależne mechanizmy oszczędzania energii w procesorze — uśpienie rdzenia i zmiana taktowania.',
    body: `<p><strong>Stany C</strong> opisują głębokość uśpienia rdzenia, gdy nie ma nic do roboty. <strong>Stany P</strong> opisują kombinację częstotliwości i napięcia przy pracy.</p><h2>Stany C</h2><p>Od C0 (rdzeń pracuje) przez kolejne poziomy wyłączania zegara, pamięci podręcznej i zasilania. Głębszy stan oszczędza więcej, ale wybudzenie trwa dłużej.</p><h2>Stany P</h2><p>Wyższy stan to niższa częstotliwość i napięcie. Zużycie mocy rośnie z kwadratem napięcia, więc niewielkie obniżenie taktowania daje nieproporcjonalnie duże oszczędności.</p><h2>Kiedy to przeszkadza</h2><p>Wybudzanie z głębokich stanów C kosztuje mikrosekundy. Przy obciążeniach wrażliwych na opóźnienia — przetwarzanie dźwięku, obsługa dużego ruchu sieciowego, systemy czasu rzeczywistego — sumuje się to w zauważalne przycięcia. Stąd zalecenia ograniczania stanów C na routerach programowych i stacjach do produkcji dźwięku.</p><h2>Sprawdzenie w Linuksie</h2><pre><code>cpupower frequency-info
cpupower idle-info</code></pre><h2>Regulator</h2><p>Zachowaniem steruje regulator: <code>powersave</code> oszczędza, <code>performance</code> trzyma wysokie taktowanie. Na serwerze obsługującym ruch sieciowy przełączenie na <code>performance</code> potrafi zauważalnie obniżyć opóźnienia — kosztem prądu.</p>`,
  },
  {
    kat: 'sprzet',
    title: 'IOMMU',
    excerpt: 'Jednostka tłumacząca adresy dla urządzeń — warunek bezpiecznego przekazania sprzętu do maszyny wirtualnej.',
    body: `<p><strong>IOMMU</strong> to układ tłumaczący adresy pamięci używane przez urządzenia peryferyjne, analogicznie do jednostki zarządzania pamięcią dla procesora. U producentów występuje pod nazwami VT-d i AMD-Vi.</p><h2>Po co</h2><p>Urządzenie z bezpośrednim dostępem do pamięci potrafi czytać i pisać w dowolnym jej miejscu. IOMMU ogranicza je do przydzielonego obszaru — to zabezpieczenie przed uszkodzeniem pamięci przez wadliwe urządzenie i przed atakami przez porty zewnętrzne.</p><h2>Przekazywanie urządzeń</h2><p>Główne zastosowanie w praktyce domowej to oddanie karty graficznej lub kontrolera maszynie wirtualnej. Bez IOMMU byłoby to niemożliwe: maszyna wirtualna ma inny widok pamięci niż urządzenie.</p><h2>Grupy</h2><p>Urządzenia dzielą się na grupy wyznaczone przez topologię magistrali. Przekazać można wyłącznie całą grupę — jeśli karta dzieli grupę z kontrolerem USB, oba muszą trafić do maszyny wirtualnej. To najczęstsza przeszkoda i zależy od układu płyty głównej, nie od konfiguracji.</p><h2>Włączenie</h2><p>Wymaga wsparcia procesora i płyty, włączenia w ustawieniach oraz parametru jądra:</p><pre><code>intel_iommu=on   # albo amd_iommu=on</code></pre><h2>Sprawdzenie grup</h2><pre><code>for d in /sys/kernel/iommu_groups/*/devices/*; do echo "$d"; done</code></pre>`,
  },
  {
    kat: 'sprzet',
    title: 'Certyfikaty 80 PLUS',
    excerpt: 'Klasyfikacja sprawności zasilaczy — co mierzy i czego nie mówi o jakości.',
    body: `<p><strong>80 PLUS</strong> to program certyfikacji mierzący sprawność zasilacza, czyli jaka część mocy pobranej z gniazdka trafia do podzespołów, a jaka zamienia się w ciepło.</p><h2>Poziomy</h2><p>Od podstawowego, przez Bronze, Silver, Gold, Platinum, po Titanium. Wyższy poziom oznacza wyższą sprawność mierzoną przy obciążeniu 20%, 50% i 100%.</p><h2>Co to daje</h2><p>Mniej ciepła w obudowie, cichszą pracę i nieco niższy rachunek. Różnica między Bronze a Gold przy typowym domowym użyciu to kwota rzędu kilkudziesięciu złotych rocznie — argument istotniejszy dla maszyny pracującej bez przerwy niż dla komputera włączanego wieczorami.</p><h2>Czego certyfikat nie mierzy</h2><p>Nie mówi nic o jakości napięć, zabezpieczeniach, tętnieniach ani o tym, co się stanie przy awarii. Zasilacz certyfikowany może mieć kiepskie zabezpieczenia i przy uszkodzeniu pociągnąć za sobą resztę podzespołów. Sprawność i jakość to dwie różne rzeczy.</p><h2>Dobór mocy</h2><p>Sprawność jest najwyższa w okolicach połowy obciążenia. Zasilacz o mocy około dwukrotnie większej niż typowy pobór pracuje w optymalnym punkcie i ma zapas na skoki karty graficznej, które potrafią kilkakrotnie przekraczać wartość średnią w bardzo krótkim czasie.</p>`,
  },
  {
    kat: 'sprzet',
    title: 'HBA a kontroler RAID',
    excerpt: 'Dwa rodzaje kontrolerów pamięci masowej — i dlaczego ZFS wymaga tego pierwszego.',
    body: `<p><strong>HBA</strong> (Host Bus Adapter) przekazuje dyski systemowi bez ingerencji. <strong>Kontroler RAID</strong> sam buduje macierz i pokazuje systemowi wolumen logiczny.</p><h2>Dlaczego to ważne dla ZFS i Btrfs</h2><p>Te systemy plików zakładają bezpośredni dostęp do dysków: własne sumy kontrolne, własne rozłożenie danych, własne decyzje o kolejności zapisu. Kontroler RAID z pamięcią podręczną zapisu potwierdza operacje, zanim trafią na talerze — a to łamie założenia, na których opiera się odporność tych systemów.</p><h2>Tryb przelotowy</h2><p>Wiele kontrolerów RAID oferuje tryb przelotowy albo pojedyncze macierze z jednego dysku. To rozwiązanie połowiczne: dyski są widoczne, ale nadal przez warstwę kontrolera, często bez przekazywania danych S.M.A.R.T. i bez TRIM. Część kontrolerów da się przeprogramować do trybu HBA i to jest właściwa droga.</p><h2>Kiedy sprzętowy RAID ma sens</h2><p>Przy klasycznych systemach plików, z podtrzymaniem bateryjnym pamięci podręcznej i gotowością na to, że odtworzenie macierzy po awarii kontrolera wymaga zgodnego modelu. Macierz jest zapisana w formacie producenta.</p><h2>Praktyczna zasada</h2><p>Do serwera plików na ZFS kupuje się HBA. Kontroler RAID w tej roli jest ryzykiem, a nie wartością dodaną.</p>`,
  },
  {
    kat: 'sprzet',
    title: 'IPMI i BMC',
    excerpt: 'Niezależny komputer w serwerze pozwalający zarządzać maszyną, która nie działa.',
    body: `<p><strong>BMC</strong> (Baseboard Management Controller) to osobny procesor na płycie serwera, działający niezależnie od systemu operacyjnego i włączony, dopóki płyta ma zasilanie. <strong>IPMI</strong> to standard protokołu, którym się z nim rozmawia.</p><h2>Co daje</h2><ul><li>Włączenie, wyłączenie i twardy reset maszyny bez fizycznego dostępu.</li><li>Zdalna konsola — obraz i klawiatura, także w BIOS-ie i przy rozruchu.</li><li>Podmontowanie obrazu instalacyjnego przez sieć.</li><li>Odczyt czujników temperatury, napięć i stanu zasilaczy.</li></ul><h2>Dlaczego to zmienia pracę</h2><p>Maszyna, która nie wstaje, przestaje wymagać wyjazdu. Instalacja systemu od zera na serwerze w innym mieście staje się rutyną.</p><h2>Poważne ryzyko</h2><p>BMC to komputer z pełną władzą nad serwerem, z własnym oprogramowaniem układowym, aktualizowanym rzadko i historycznie pełnym poważnych luk. Wystawienie go do internetu jest jednym z najgorszych możliwych błędów konfiguracyjnych.</p><h2>Zasady</h2><ul><li>Osobna sieć zarządzania, niedostępna z internetu.</li><li>Zmiana domyślnych haseł — fabryczne są publicznie znane.</li><li>Dostęp wyłącznie przez VPN.</li><li>Aktualizacje oprogramowania układowego mimo że nikt o nich nie pamięta.</li></ul>`,
  },
  {
    kat: 'sprzet',
    title: 'TPM',
    excerpt: 'Układ przechowujący klucze i mierzący stan rozruchu — podstawa szyfrowania dysku bez podawania hasła.',
    body: `<p><strong>TPM</strong> (Trusted Platform Module) to układ kryptograficzny przechowujący klucze w sposób uniemożliwiający ich odczytanie i prowadzący rejestry pomiarów kolejnych etapów rozruchu.</p><h2>Rejestry pomiarów</h2><p>Każdy etap rozruchu — oprogramowanie układowe, program rozruchowy, jądro — jest haszowany, a wynik dopisywany do rejestru. Wartości nie da się ustawić dowolnie, tylko dołożyć kolejny pomiar. Końcowy stan rejestrów jest odciskiem całej ścieżki rozruchu.</p><h2>Odpieczętowanie klucza</h2><p>Klucz szyfrowania dysku można zapieczętować tak, by TPM wydał go wyłącznie przy określonych wartościach rejestrów. Zmiana programu rozruchowego, uruchomienie z innego nośnika albo przełożenie dysku do innej maszyny sprawia, że klucz nie zostanie wydany.</p><h2>Co to daje w praktyce</h2><p>Dysk szyfrowany, który uruchamia się bez pytania o hasło, a jednocześnie jest bezużyteczny po wyjęciu z komputera. Tak działa BitLocker i tak da się skonfigurować LUKS w Linuksie.</p><h2>Ograniczenia</h2><p>Ochrona dotyczy sytuacji „ktoś ukradł dysk lub komputer wyłączony". Nie chroni przed atakiem na działający system — po uruchomieniu klucz jest w pamięci. Aktualizacja oprogramowania układowego zmienia pomiary i zwykle wymaga ponownego zapieczętowania; bez zapasowego hasła odzyskiwania kończy się to utratą dostępu do danych.</p>`,
  },
  {
    kat: 'sprzet',
    title: 'Standardy USB',
    excerpt: 'Bałagan nazewniczy kolejnych wersji — i co naprawdę oznaczają liczby na opakowaniu.',
    body: `<p>Nazewnictwo standardów USB było kilkukrotnie zmieniane wstecz, przez co ta sama prędkość występuje pod kilkoma nazwami jednocześnie.</p><h2>Prędkości</h2><ul><li><strong>480 Mb/s</strong> — USB 2.0, dawniej „High Speed".</li><li><strong>5 Gb/s</strong> — pierwotnie USB 3.0, potem 3.1 Gen 1, potem 3.2 Gen 1.</li><li><strong>10 Gb/s</strong> — pierwotnie 3.1 Gen 2, potem 3.2 Gen 2.</li><li><strong>20 Gb/s</strong> — 3.2 Gen 2x2, wymaga złącza typu C.</li></ul><p>Praktyczny wniosek: nazwa wersji nic nie mówi, znaczenie ma podana prędkość w gigabitach.</p><h2>Kształt złącza to osobna sprawa</h2><p>Złącze typu C to tylko kształt. Ten sam wtyk obsługuje wszystko od USB 2.0 po Thunderbolt, przesyłanie obrazu i zasilanie — albo nic z tego. Dwa identycznie wyglądające porty w jednym laptopie potrafią mieć zupełnie różne możliwości.</p><h2>Kable</h2><p>Kabel jest częścią układu. Kabel do ładowania często ma tylko żyły zasilania i nie prześle danych z pełną prędkością. Przy zasilaniu dużą mocą wymagany jest kabel z odpowiednim oznaczeniem — na tym polega większość problemów z „nieładującym się" sprzętem.</p><h2>Diagnostyka w Linuksie</h2><pre><code>lsusb -t</code></pre><p>Pokazuje drzewo urządzeń wraz z wynegocjowaną prędkością — szybciej rozstrzyga niż specyfikacje producenta.</p>`,
  },
  {
    kat: 'sprzet',
    title: 'PoE',
    excerpt: 'Zasilanie urządzeń przez kabel sieciowy — standardy, budżet mocy i sprzęt, którego lepiej unikać.',
    body: `<p><strong>PoE</strong> (Power over Ethernet) pozwala przesłać zasilanie tym samym kablem, którym płyną dane. Kamera, punkt dostępowy czy telefon nie potrzebują wtedy gniazdka.</p><h2>Standardy</h2><ul><li><strong>802.3af</strong> — do około 15 W na porcie.</li><li><strong>802.3at</strong> (PoE+) — do około 30 W.</li><li><strong>802.3bt</strong> (PoE++) — do około 60 lub 90 W, zależnie od typu.</li></ul><p>Moc podana to moc na porcie przełącznika; do urządzenia dociera mniej ze względu na straty w kablu, tym większe im dłuższy odcinek.</p><h2>Budżet mocy</h2><p>Przełącznik ma łączny budżet, zwykle mniejszy niż suma maksymalnych mocy wszystkich portów. Osiem portów po 30 W nie znaczy 240 W do dyspozycji. Przekroczenie budżetu kończy się wyłączaniem portów według priorytetu — objawem bywają kamery gasnące o różnych porach bez wyraźnej przyczyny.</p><h2>Sprzęt pasywny</h2><p>Tanie zasilacze „PoE" podają napięcie na stałe, bez negocjacji przewidzianej w standardzie. Podłączenie do nich urządzenia zgodnego ze standardem, albo zwykłego sprzętu sieciowego, potrafi je uszkodzić. Warto sprawdzać, czy urządzenie mówi o zgodności ze standardem, czy tylko o „PoE".</p><h2>Odległość</h2><p>Obowiązuje ten sam limit co dla danych — sto metrów. Przy większych mocach i cienkich żyłach warto liczyć spadek napięcia.</p>`,
  },
  {
    kat: 'sprzet',
    title: 'UPS',
    excerpt: 'Zasilanie awaryjne — rodzaje, dobór i najczęściej pomijana część, czyli bezpieczne wyłączenie.',
    body: `<p><strong>UPS</strong> to urządzenie podtrzymujące zasilanie przy zaniku prądu, zwykle na czas wystarczający do bezpiecznego wyłączenia sprzętu.</p><h2>Rodzaje</h2><ul><li><strong>Offline</strong> — przełącza na baterię po zaniku, z krótką przerwą. Najtańszy, wystarczający dla komputera domowego.</li><li><strong>Line-interactive</strong> — dodatkowo koryguje wahania napięcia bez sięgania po baterię. Rozsądny wybór dla serwera domowego.</li><li><strong>Online</strong> — stale zasila z falownika, brak przerwy przy przełączeniu. Najdroższy, stosowany przy sprzęcie wrażliwym.</li></ul><h2>Dobór</h2><p>Moc podawana w woltoamperach nie równa się mocy w watach — przelicznik zależy od współczynnika mocy. Warto patrzeć na wartość w watach i zakładać zapas; UPS pracujący na granicy skraca żywotność baterii.</p><h2>Część, o której się zapomina</h2><p>Sam UPS nie chroni danych. Bez połączenia z komputerem i usługi nadzorującej maszyna po prostu padnie w chwili wyczerpania baterii — czyli dokładnie tak, jakby UPS-a nie było, tylko później. Trzeba podpiąć kabel danych i skonfigurować usługę wyłączającą system przy określonym poziomie naładowania.</p><h2>Baterie</h2><p>Akumulatory zużywają się w kilka lat i degradują cicho. UPS, którego nikt nie testował od zakupu, w chwili awarii często podtrzymuje zasilanie przez kilkanaście sekund. Test obciążeniowy raz na jakiś czas jest częścią utrzymania.</p>`,
  },
  {
    kat: 'sprzet',
    title: 'Dławienie termiczne',
    excerpt: 'Automatyczne obniżanie taktowania przy przegrzaniu — mechanizm ochronny brany za awarię.',
    body: `<p><strong>Dławienie termiczne</strong> to obniżenie częstotliwości i napięcia przez procesor lub kartę graficzną po przekroczeniu progu temperatury. Nie jest awarią — jest zabezpieczeniem.</p><h2>Objawy</h2><p>Wydajność wysoka przez pierwsze kilkadziesiąt sekund obciążenia, potem wyraźny spadek utrzymujący się do końca. Gry z płynnym startem i przycięciami po kwadransie, kompilacje zwalniające w połowie, dyski NVMe tracące transfer przy dużym pliku.</p><h2>Najczęstsze przyczyny</h2><ul><li>Zaschnięta pasta termoprzewodząca — po kilku latach to najczęstsza pojedyncza przyczyna.</li><li>Zapchane radiatory i wentylatory.</li><li>Chłodzenie dobrane dokładnie na wartość TDP bez zapasu.</li><li>Zły obieg powietrza w obudowie — sam mocny wentylator na procesorze nie pomoże, jeśli gorące powietrze nie ma którędy wyjść.</li></ul><h2>Pomiar zamiast zgadywania</h2><pre><code>sensors
watch -n1 "grep MHz /proc/cpuinfo"</code></pre><p>Spadek taktowania zbiegający się w czasie ze wzrostem temperatury jest rozpoznaniem samym w sobie.</p><h2>Uwaga o laptopach</h2><p>W wielu konstrukcjach dławienie jest przewidziane w projekcie: chłodzenie nie jest w stanie odprowadzić ciepła przy pełnym obciążeniu wszystkich rdzeni i producent to zakłada. Czyszczenie i wymiana pasty pomogą, ale nie zmienią granicy wyznaczonej przez konstrukcję.</p>`,
  },
  {
    kat: 'sprzet',
    title: 'Wyrównywanie zużycia (wear leveling)',
    excerpt: 'Rozkładanie zapisów po całej pamięci SSD — powód, dla którego nadpisanie pliku go nie kasuje.',
    body: `<p><strong>Wyrównywanie zużycia</strong> to strategia kontrolera SSD polegająca na rozkładaniu zapisów równomiernie po wszystkich komórkach, tak by żadna nie zużyła się przedwcześnie.</p><h2>Skąd potrzeba</h2><p>Komórka pamięci NAND wytrzymuje ograniczoną liczbę cykli kasowania. Bez wyrównywania obszar z często zmienianym plikiem — na przykład tablicą systemu plików — zużyłby się wielokrotnie szybciej niż reszta dysku.</p><h2>Warstwa tłumacząca</h2><p>Kontroler utrzymuje własne odwzorowanie adresów logicznych na fizyczne. To, co system widzi jako „ten sam sektor", fizycznie wędruje po całym układzie.</p><h2>Konsekwencja dla kasowania danych</h2><p>Nadpisanie pliku nie nadpisuje komórek, w których leżał — kontroler zapisuje nową wersję gdzie indziej, a stara zostaje, dopóki nie zostanie skasowana przy okazji. Klasyczne wielokrotne nadpisywanie, sensowne przy dyskach talerzowych, na SSD nie daje gwarancji.</p><h2>Właściwe metody</h2><p>Szyfrowanie całego nośnika od pierwszego dnia i zniszczenie klucza, albo firmowe polecenie bezpiecznego kasowania (<em>secure erase</em>), które kontroler wykonuje na całej pamięci.</p><h2>Nadmiarowa pojemność</h2><p>Dyski mają więcej pamięci, niż deklarują — zapas służy wyrównywaniu i zastępowaniu zużytych bloków. Dlatego dysk zapełniony do ostatniego bajta zapisuje wyraźnie wolniej i zużywa się szybciej.</p>`,
  },
  {
    kat: 'sprzet',
    title: 'HDMI a DisplayPort',
    excerpt: 'Dwa standardy obrazu — różnice, które ujawniają się przy wysokich odświeżaniach i wielu monitorach.',
    body: `<p><strong>HDMI</strong> i <strong>DisplayPort</strong> to dwa niezależne standardy przesyłania obrazu, rozwijane przez różne organizacje i mające różne mocne strony.</p><h2>Przepustowość</h2><p>Obie rodziny mają wiele wersji o bardzo różnych możliwościach. Praktyczna zasada: przy wysokich rozdzielczościach i odświeżaniach powyżej sześćdziesięciu klatek wersja standardu decyduje o tym, czy tryb w ogóle będzie dostępny — a wersji nie widać po złączu.</p><h2>Łańcuchowanie</h2><p>DisplayPort obsługuje transport wielostrumieniowy, pozwalający podłączyć kilka monitorów szeregowo albo przez rozgałęziacz z jednego portu. HDMI takiej możliwości nie ma.</p><h2>Adaptery</h2><p>Przejściówki bywają jednokierunkowe. Przejście z DisplayPort na HDMI zwykle działa; w drugą stronę wymaga aktywnego układu i często zawodzi. Tanie adaptery ograniczają też odświeżanie w sposób nieudokumentowany.</p><h2>Zmienne odświeżanie</h2><p>Obie rodziny mają dziś swoje mechanizmy synchronizacji z kartą, ale zgodność zależy od konkretnej pary karta–monitor, a nie od samego złącza.</p><h2>Kable</h2><p>Kabel bez odpowiedniej klasy przepuści niższe tryby, a przy wyższych da migotanie, czarne przebłyski albo brak obrazu. To najczęstsza przyczyna problemów przy wysokich rozdzielczościach — i najtańsza do sprawdzenia.</p>`,
  },
  {
    kat: 'sprzet',
    title: 'Bufor SLC w dyskach SSD',
    excerpt: 'Szybki obszar zapisu w tanich dyskach — powód gwałtownego spadku transferu przy dużych plikach.',
    body: `<p>Współczesne dyski SSD zapisują kilka bitów w jednej komórce. Im więcej bitów, tym większa pojemność i niższa cena, ale też wolniejszy zapis i mniejsza wytrzymałość.</p><h2>Bufor</h2><p>Kontroler przeznacza część pamięci na pracę w trybie jednobitowym, który jest znacznie szybszy. Zapis trafia najpierw tam, a w czasie bezczynności jest przenoszony do właściwego obszaru.</p><h2>Objaw po wyczerpaniu</h2><p>Kopiowanie dużego pliku zaczyna się z pełną deklarowaną prędkością, a po kilku lub kilkudziesięciu gigabajtach gwałtownie zwalnia — czasem do wartości poniżej dysku talerzowego. To nie usterka: bufor się zapełnił i zapis idzie bezpośrednio do wolniejszej pamięci.</p><h2>Rozmiar bufora jest zmienny</h2><p>W wielu dyskach zależy od ilości wolnego miejsca — im pełniejszy dysk, tym mniejszy bufor i tym wcześniej następuje spadek. Dysk zapełniony w dziewięćdziesięciu procentach zachowuje się zupełnie inaczej niż świeżo sformatowany.</p><h2>Co z tego wynika przy zakupie</h2><p>Testy odczytu i krótkiego zapisu nie mówią nic o zachowaniu przy przenoszeniu dużych archiwów czy montażu wideo. Przy takich zastosowaniach istotny jest zapis podtrzymany po wyczerpaniu bufora — parametr rzadko podawany, ale mierzony w rzetelnych testach.</p>`,
  },
];
