/** Hasła wiki — Sieć, część 1. */
export default [
  {
    kat: 'siec',
    title: 'NAT',
    excerpt: 'Tłumaczenie adresów pozwalające wielu urządzeniom wyjść do internetu przez jeden adres publiczny.',
    body: `<p><strong>NAT</strong> (Network Address Translation) to podmiana adresów w nagłówkach pakietów przechodzących przez router. Najczęstsza odmiana, <em>masquerade</em>, zamienia adresy prywatne sieci lokalnej na jeden adres publiczny.</p><h2>Jak router pamięta, do kogo odesłać</h2><p>Wychodzący pakiet dostaje adres publiczny i wolny port źródłowy. Router zapisuje w tablicy powiązanie „adres i port publiczny ↔ adres i port lokalny". Odpowiedź trafia do właściwego urządzenia po tym wpisie.</p><h2>Konsekwencja: połączenia tylko z jednej strony</h2><p>Bez wpisu w tablicy router nie wie, komu doręczyć pakiet przychodzący — więc go odrzuca. Dlatego usługi w sieci domowej nie są widoczne z zewnątrz bez przekierowania portu, a połączenia bezpośrednie między dwiema sieciami za NAT wymagają sztuczek.</p><h2>Wpisy wygasają</h2><p>Powiązania mają czas życia. Połączenie bez ruchu przez kilka minut potrafi zniknąć z tablicy — stąd rozłączane sesje SSH i konieczność pakietów podtrzymujących w tunelach VPN.</p><h2>Czego NAT nie robi</h2><p>Nie jest zaporą sieciową, choć bywa za nią brany. To, że z zewnątrz nie da się nawiązać połączenia, jest skutkiem ubocznym braku wpisu, a nie decyzją o bezpieczeństwie. Reguły filtrowania to osobna warstwa.</p>`,
    sources: [{ url: 'https://datatracker.ietf.org/doc/html/rfc3022', title: 'RFC 3022 — Traditional IP Network Address Translator' }],
  },
  {
    kat: 'siec',
    title: 'CGNAT',
    excerpt: 'NAT po stronie operatora — powód, dla którego przekierowanie portu w routerze bywa bezskuteczne.',
    body: `<p><strong>CGNAT</strong> (Carrier-Grade NAT) to NAT zastosowany przez operatora: setki abonentów dzieli jeden publiczny adres IPv4, a każdy dostaje adres z puli współdzielonej.</p><h2>Jak rozpoznać</h2><p>Adres WAN na routerze mieści się w zakresie <code>100.64.0.0/10</code> — puli zarezerwowanej właśnie na ten cel. Drugi objaw: adres pokazywany przez serwisy „jaki mam IP" różni się od adresu WAN routera.</p><h2>Co przestaje działać</h2><ul><li>Przekierowanie portu w routerze — pakiet z internetu nie dociera nawet do niego.</li><li>Serwer gry, kamera, dysk sieciowy wystawiony na zewnątrz.</li><li>Część połączeń bezpośrednich w grach i komunikatorach.</li></ul><h2>Obejścia</h2><ul><li>Wykupienie publicznego adresu IPv4 u operatora — najprostsze, zwykle płatne.</li><li><strong>IPv6</strong>, jeśli operator go daje: tam CGNAT nie występuje i adres jest publiczny.</li><li>Tunel do maszyny z publicznym adresem — VPS z WireGuardem i przekierowaniem portów.</li><li>Usługi tunelujące, wystawiające ruch przez połączenie inicjowane od środka.</li></ul><h2>Dlaczego to istnieje</h2><p>Wolnych adresów IPv4 nie ma. CGNAT jest sposobem na obsłużenie nowych abonentów bez nich — i jednym z mocniejszych argumentów za wdrażaniem IPv6.</p>`,
    sources: [{ url: 'https://datatracker.ietf.org/doc/html/rfc6598', title: 'RFC 6598 — Shared Address Space' }],
  },
  {
    kat: 'siec',
    title: 'Rekordy DNS',
    excerpt: 'Podstawowe typy wpisów w strefie: A, AAAA, CNAME, MX, TXT, NS — i co każdy z nich naprawdę robi.',
    body: `<p>Strefa DNS to zbiór <strong>rekordów</strong>, z których każdy odpowiada na inne pytanie o domenę.</p><h2>Najczęstsze typy</h2><ul><li><strong>A</strong> — adres IPv4.</li><li><strong>AAAA</strong> — adres IPv6.</li><li><strong>CNAME</strong> — alias wskazujący na inną nazwę. Nie może współistnieć z innymi rekordami dla tej samej nazwy, dlatego nie da się go założyć na domenie głównej.</li><li><strong>MX</strong> — serwer poczty przyjmujący listy dla domeny, z priorytetem.</li><li><strong>TXT</strong> — dowolny tekst; w praktyce SPF, DKIM, DMARC i potwierdzenia własności domeny.</li><li><strong>NS</strong> — serwery nazw autorytatywne dla strefy.</li><li><strong>PTR</strong> — nazwa dla adresu, czyli zapytanie odwrotne; ustawia się je u właściciela adresacji, nie w swojej strefie.</li></ul><h2>TTL</h2><p>Każdy rekord ma czas życia mówiący, jak długo wolno go trzymać w pamięci podręcznej. Przed planowaną zmianą adresu obniża się TTL z wyprzedzeniem — inaczej część świata będzie widziała stary adres przez cały pierwotny okres.</p><h2>Sprawdzanie</h2><pre><code>dig +short example.com A
dig example.com MX
dig @1.1.1.1 example.com TXT</code></pre><p>Pytanie do konkretnego serwera (<code>@</code>) omija pamięć podręczną systemu i pokazuje, co widzi świat.</p>`,
    sources: [{ url: 'https://datatracker.ietf.org/doc/html/rfc1035', title: 'RFC 1035 — Domain Names' }],
  },
  {
    kat: 'siec',
    title: 'DNS over HTTPS i DNS over TLS',
    excerpt: 'Szyfrowane zapytania DNS — co ukrywają, a czego nie.',
    body: `<p><strong>DoH</strong> i <strong>DoT</strong> to sposoby przesyłania zapytań DNS w szyfrowanym połączeniu zamiast otwartym tekstem po porcie 53.</p><h2>Różnica</h2><ul><li><strong>DoT</strong> — DNS opakowany w TLS, port 853. Ruch jest szyfrowany, ale rozpoznawalny jako DNS.</li><li><strong>DoH</strong> — zapytania jako żądania HTTPS na porcie 443. Nie odróżnia się od zwykłego ruchu WWW, więc trudniej go zablokować.</li></ul><h2>Co to daje</h2><p>Operator ani osoba w tej samej sieci nie zobaczy, o jakie nazwy pytasz, i nie podmieni odpowiedzi po drodze.</p><h2>Czego nie ukrywa</h2><p>Po rozwiązaniu nazwy nawiązywane jest połączenie z adresem docelowym, a ten jest widoczny. Do tego pole SNI w powitaniu TLS zwykle niesie nazwę domeny otwartym tekstem. Szyfrowany DNS utrudnia obserwację, ale nie czyni ruchu anonimowym.</p><h2>Skutek uboczny w sieci lokalnej</h2><p>Przeglądarka z własnym DoH omija serwer DNS podany przez router. Przestają wtedy działać nazwy lokalne, blokowanie reklam na poziomie sieci i polityki firmowe — a przyczyna bywa trudna do znalezienia, bo system operacyjny rozwiązuje nazwy poprawnie.</p>`,
    sources: [{ url: 'https://datatracker.ietf.org/doc/html/rfc8484', title: 'RFC 8484 — DNS Queries over HTTPS' }],
  },
  {
    kat: 'siec',
    title: 'Uzgadnianie trójfazowe TCP',
    excerpt: 'Wymiana SYN, SYN-ACK, ACK otwierająca połączenie — i co mówi jej brak.',
    body: `<p>Połączenie TCP zaczyna się od <strong>uzgadniania trójfazowego</strong>: klient wysyła <code>SYN</code>, serwer odpowiada <code>SYN-ACK</code>, klient potwierdza <code>ACK</code>. Dopiero potem płyną dane.</p><h2>Diagnostyka po objawie</h2><ul><li><strong>Natychmiastowe „connection refused"</strong> — pakiet dotarł, ale nikt nie słucha na tym porcie. Host żyje, usługa nie działa albo słucha na innym adresie.</li><li><strong>Zawieszenie do przekroczenia czasu</strong> — pakiety giną po drodze. Zwykle zapora odrzucająca w ciszy albo błędna trasa.</li><li><strong>Połączenie wstaje, ale zrywa się przy większych danych</strong> — to nie jest problem TCP, tylko MTU. Patrz osobne hasło.</li></ul><p>Ta różnica jest najszybszym rozgałęzieniem przy diagnozie i warto ją mieć w głowie przed sięgnięciem po narzędzia.</p><h2>Zamykanie</h2><p>Zamknięcie wymaga czterech pakietów i zostawia stronę inicjującą w stanie <code>TIME_WAIT</code> na około dwie minuty. Przy serwerze otwierającym wiele krótkich połączeń tysiące takich wpisów to stan normalny, a nie awaria.</p><h2>Podgląd</h2><pre><code>ss -tan state time-wait | wc -l
ss -tanp</code></pre>`,
    sources: [{ url: 'https://datatracker.ietf.org/doc/html/rfc9293', title: 'RFC 9293 — Transmission Control Protocol' }],
  },
  {
    kat: 'siec',
    title: 'Algorytmy kontroli przeciążenia',
    excerpt: 'CUBIC, BBR i reszta — zasady, wedle których TCP zgaduje, ile może wysłać.',
    body: `<p><strong>Kontrola przeciążenia</strong> to logika po stronie nadawcy decydująca, jak szybko wysyłać dane, żeby nie zapchać łącza. TCP nie zna przepustowości trasy — musi ją oszacować.</p><h2>CUBIC</h2><p>Domyślny w Linuksie od lat. Zwiększa okno, dopóki nie zauważy zgubionego pakietu, po czym cofa się i próbuje ponownie. Zakłada, że strata oznacza przeciążenie.</p><h2>BBR</h2><p>Zamiast czekać na straty, mierzy przepustowość i najmniejsze obserwowane opóźnienie, po czym wysyła tyle, ile trasa naprawdę uniesie. Radzi sobie wyraźnie lepiej na łączach z niewielkim losowym gubieniem pakietów — typowo mobilnych i międzykontynentalnych — gdzie CUBIC bierze każdą stratę za przeciążenie i niepotrzebnie zwalnia.</p><h2>Bufferbloat</h2><p>Algorytmy oparte na stracie zapełniają bufory w routerach po drodze, bo dopiero przepełniony bufor gubi pakiet. Skutkiem są sekundowe opóźnienia przy pełnym wykorzystaniu łącza — pobieranie pliku psuje rozmowę głosową. To problem kolejkowania, leczony po stronie kolejek (<code>fq_codel</code>, <code>cake</code>).</p><h2>Sprawdzenie i zmiana</h2><pre><code>sysctl net.ipv4.tcp_congestion_control
sysctl net.ipv4.tcp_available_congestion_control</code></pre><p>Zmiana działa po stronie nadawcy — czyli na serwerze wysyłającym dane, nie u pobierającego.</p>`,
  },
  {
    kat: 'siec',
    title: 'QUIC',
    excerpt: 'Protokół transportowy na UDP z wbudowanym szyfrowaniem, podstawa HTTP/3.',
    body: `<p><strong>QUIC</strong> to protokół transportowy zbudowany na UDP, łączący w sobie zadania TCP i TLS. Jest fundamentem HTTP/3.</p><h2>Co rozwiązuje</h2><ul><li><strong>Blokowanie czoła kolejki</strong> — w HTTP/2 na TCP zgubiony pakiet wstrzymywał wszystkie strumienie w połączeniu. QUIC prowadzi strumienie niezależnie, więc strata dotyka tylko jednego.</li><li><strong>Czas nawiązania</strong> — uzgodnienie transportu i szyfrowania odbywa się razem, zamiast kolejno TCP i TLS.</li><li><strong>Zmiana sieci</strong> — połączenie ma własny identyfikator, więc przejście z Wi-Fi na sieć komórkową nie zrywa sesji.</li></ul><h2>Dlaczego na UDP</h2><p>Nowego protokołu obok TCP i UDP nie da się dziś wdrożyć — pośrednicy po drodze odrzucają nieznane numery protokołów. UDP było jedyną drogą, którą przepuści istniejący internet.</p><h2>Konsekwencje praktyczne</h2><p>Cały QUIC działa w przestrzeni użytkownika, więc zmiany nie wymagają aktualizacji jądra. Z drugiej strony ruch jest zaszyfrowany aż po nagłówki, co utrudnia diagnostykę: <code>tcpdump</code> pokaże, że coś leci, ale nie co. Sieci blokujące UDP na porcie 443 wymuszają cofnięcie się do HTTP/2 — zwykle niezauważalne, czasem będące przyczyną dziwnych spowolnień.</p>`,
    sources: [{ url: 'https://datatracker.ietf.org/doc/html/rfc9000', title: 'RFC 9000 — QUIC' }],
  },
  {
    kat: 'siec',
    title: 'SNI',
    excerpt: 'Pole w powitaniu TLS niosące nazwę domeny — powód, dla którego jeden adres obsługuje setki certyfikatów.',
    body: `<p><strong>SNI</strong> (Server Name Indication) to rozszerzenie TLS, w którym klient podaje nazwę domeny, z którą chce się połączyć — zanim jeszcze zestawi szyfrowanie.</p><h2>Po co</h2><p>Serwer musi wybrać certyfikat przed rozpoczęciem szyfrowanej rozmowy. Bez SNI, mając jeden adres IP, mógłby obsłużyć tylko jedną domenę. Z SNI ten sam adres obsługuje dowolnie wiele witryn, każdą z własnym certyfikatem.</p><h2>Wyciek prywatności</h2><p>Klasyczne SNI jedzie otwartym tekstem. Obserwator widzi więc nazwę odwiedzanej domeny nawet przy pełnym HTTPS i szyfrowanym DNS. Na tym opiera się większość filtrowania stron na poziomie sieci.</p><h2>Encrypted Client Hello</h2><p>ECH szyfruje powitanie klienta wraz z SNI, używając klucza publikowanego w DNS. Wymaga wsparcia po obu stronach i zwykle DNS-a odpornego na podsłuch — inaczej wyciek przenosi się po prostu do zapytania o nazwę.</p><h2>Diagnostyka</h2><pre><code>openssl s_client -connect 1.2.3.4:443 -servername example.com</code></pre><p>Bez <code>-servername</code> serwer odda certyfikat domyślny i łatwo o mylny wniosek, że certyfikat jest nie ten.</p>`,
    sources: [{ url: 'https://datatracker.ietf.org/doc/html/rfc6066', title: 'RFC 6066 — TLS Extensions' }],
  },
  {
    kat: 'siec',
    title: 'Anycast',
    excerpt: 'Jeden adres ogłaszany z wielu miejsc świata — pakiet trafia do najbliższego węzła.',
    body: `<p><strong>Anycast</strong> to sposób adresowania, w którym ten sam adres IP jest ogłaszany w BGP z wielu lokalizacji. Routing kieruje pakiet do topologicznie najbliższego węzła.</p><h2>Gdzie się to stosuje</h2><ul><li>Publiczne serwery DNS — jeden adres, dziesiątki lokalizacji na świecie.</li><li>Sieci dostarczania treści — użytkownik trafia do najbliższego punktu obecności.</li><li>Ochrona przed atakami wolumetrycznymi — ruch ataku rozkłada się między lokalizacje zamiast uderzać w jeden punkt.</li></ul><h2>Ograniczenie</h2><p>„Najbliższy" znaczy najbliższy w sensie tras BGP, a nie odległości w kilometrach. Zdarza się, że użytkownik z Polski trafia do węzła we Frankfurcie, choć fizycznie bliżej jest inny — decyduje polityka operatorów, nie geografia.</p><h2>Dlaczego to działa z TCP</h2><p>Anycast bywał uważany za nadający się tylko do bezstanowego UDP, bo zmiana trasy w trakcie połączenia trafiłaby do innego węzła. W praktyce trasy są na tyle stabilne, że przypadki takie są rzadkie, i dziś anycast obsługuje bez problemu ruch HTTPS na dużą skalę.</p><h2>Rozpoznanie</h2><p>Ten sam adres odpowiadający z bardzo różnymi czasami z różnych stron świata, a w <code>traceroute</code> kończący się w innym mieście zależnie od punktu startu, to niemal na pewno anycast.</p>`,
  },
  {
    kat: 'siec',
    title: 'BGP',
    excerpt: 'Protokół, którym operatorzy ogłaszają sobie trasy — i którym potrafią wyłączyć fragment internetu.',
    body: `<p><strong>BGP</strong> (Border Gateway Protocol) to protokół wymiany informacji o trasach między systemami autonomicznymi, czyli sieciami niezależnych operatorów. To on decyduje, którędy pakiet pojedzie przez internet.</p><h2>System autonomiczny</h2><p>Sieć zarządzana przez jeden podmiot, identyfikowana numerem <strong>ASN</strong>. Każdy operator, duży dostawca hostingu i większa firma z własną adresacją go posiada.</p><h2>Jak wybierana jest trasa</h2><p>Nie po szybkości ani opóźnieniu. BGP kieruje się polityką: preferencjami lokalnymi, długością ścieżki przez kolejne systemy autonomiczne i umowami handlowymi. Dlatego ruch potrafi jechać okrężnie — bo tak jest taniej dla operatora, a nie szybciej dla użytkownika.</p><h2>Zaufanie jako słaby punkt</h2><p>Historycznie BGP przyjmował ogłoszenia bez weryfikacji. Ogłoszenie cudzej adresacji — przez pomyłkę albo celowo — przekierowywało ruch całych serwisów. Zdarzało się to wielokrotnie i bywało przyczyną wielogodzinnych awarii o zasięgu krajowym.</p><h2>Zabezpieczenia</h2><p><strong>RPKI</strong> pozwala właścicielowi adresacji podpisać oświadczenie, który system autonomiczny może ją ogłaszać, a operatorom odrzucać ogłoszenia niezgodne. Wdrożenie rośnie, ale nie jest powszechne.</p>`,
    sources: [{ url: 'https://datatracker.ietf.org/doc/html/rfc4271', title: 'RFC 4271 — A Border Gateway Protocol 4' }],
  },
  {
    kat: 'siec',
    title: 'Odwrotne proxy',
    excerpt: 'Pośrednik stojący przed serwerami aplikacji — terminacja TLS, rozdział ruchu i pojedynczy punkt wejścia.',
    body: `<p><strong>Odwrotne proxy</strong> to serwer przyjmujący połączenia od klientów i przekazujący je dalej, do właściwych aplikacji. Z zewnątrz widać tylko jego.</p><h2>Co się na nim robi</h2><ul><li><strong>Terminacja TLS</strong> — certyfikaty w jednym miejscu, aplikacje mówią czystym HTTP wewnątrz sieci.</li><li><strong>Rozdział po nazwie</strong> — kilka domen na jednym adresie i porcie.</li><li><strong>Równoważenie obciążenia</strong> między wieloma kopiami aplikacji.</li><li><strong>Pamięć podręczna</strong> dla treści statycznych.</li><li><strong>Ograniczanie tempa żądań</strong> i podstawowe filtrowanie.</li></ul><h2>Adres klienta znika</h2><p>Aplikacja za proxy widzi jako źródło adres proxy. Prawdziwy adres przekazuje się nagłówkiem <code>X-Forwarded-For</code> — którego <strong>nie wolno ufać bezwarunkowo</strong>: klient może go podać sam. Aplikacja musi znać listę zaufanych pośredników, inaczej blokowanie po adresie IP i limity żądań da się obejść jednym nagłówkiem.</p><h2>Typowe pułapki</h2><ul><li>Brak przekazania schematu (<code>X-Forwarded-Proto</code>) — aplikacja generuje odnośniki z <code>http://</code> i wpada w pętlę przekierowań.</li><li>Domyślny limit rozmiaru żądania — przesyłanie plików kończy się błędem 413.</li><li>Brak obsługi nagłówków przełączenia protokołu — WebSocket nie wstaje.</li></ul>`,
  },
  {
    kat: 'siec',
    title: 'SLAAC',
    excerpt: 'Samodzielna konfiguracja adresu IPv6 na podstawie ogłoszeń routera, bez serwera DHCP.',
    body: `<p><strong>SLAAC</strong> (Stateless Address Autoconfiguration) to sposób, w jaki urządzenie samo nadaje sobie adres IPv6. Router ogłasza prefiks sieci, a host dokłada własną część identyfikującą.</p><h2>Przebieg</h2><ol><li>Host tworzy adres link-local z prefiksem <code>fe80::/64</code>.</li><li>Sprawdza, czy adres nie jest zajęty (wykrywanie duplikatów).</li><li>Pyta o ogłoszenia routera albo czeka na kolejne.</li><li>Z ogłoszonego prefiksu i własnego identyfikatora składa adres globalny.</li></ol><h2>Brak stanu</h2><p>Router nie prowadzi listy przydzielonych adresów — stąd „stateless". To upraszcza sieć, ale odbiera możliwość powiedzenia „to urządzenie ma zawsze ten adres" bez dodatkowych mechanizmów.</p><h2>Adresy tymczasowe</h2><p>Adres wyliczony z adresu MAC pozwalałby śledzić urządzenie między sieciami. Dlatego systemy generują dodatkowo adresy tymczasowe, zmieniane co pewien czas i używane do połączeń wychodzących. Jedno urządzenie ma więc zwykle kilka adresów IPv6 naraz i jest to stan normalny.</p><h2>Skąd DNS</h2><p>Serwery nazw przychodzą albo w ogłoszeniu routera, albo z DHCPv6. Brak jednego i drugiego to częsta przyczyna sytuacji, w której IPv6 działa po adresie, a nazwy się nie rozwiązują.</p>`,
    sources: [{ url: 'https://datatracker.ietf.org/doc/html/rfc4862', title: 'RFC 4862 — IPv6 Stateless Address Autoconfiguration' }],
  },
  {
    kat: 'siec',
    title: 'ARP',
    excerpt: 'Odwzorowanie adresu IP na adres sprzętowy w sieci lokalnej — i sposób na podsłuch w tej samej sieci.',
    body: `<p><strong>ARP</strong> (Address Resolution Protocol) odpowiada na pytanie „kto w tej sieci ma adres 192.168.1.1 i jaki ma adres MAC". Bez tego karta sieciowa nie wie, do kogo zaadresować ramkę.</p><h2>Działanie</h2><p>Host rozgłasza pytanie do całego segmentu. Właściciel adresu odpowiada swoim adresem MAC. Odpowiedź trafia do tablicy ARP na kilka minut.</p><pre><code>ip neigh show</code></pre><h2>Zatruwanie tablicy</h2><p>Protokół nie ma uwierzytelniania — odpowiedź przyjmuje się na słowo. Urządzenie w tej samej sieci może twierdzić, że jest bramą, i przechwytywać cały ruch. To jeden z najstarszych i wciąż działających ataków w sieciach lokalnych, w tym w otwartych sieciach Wi-Fi.</p><h2>Co realnie chroni</h2><p>Nie da się tego naprawić w samym ARP. Ochroną jest szyfrowanie warstwy wyższej — HTTPS z weryfikacją certyfikatu sprawia, że przechwycony ruch pozostaje nieczytelny, a próba podstawienia się kończy ostrzeżeniem. W sieciach zarządzanych stosuje się dodatkowo mechanizmy przełącznika ograniczające, kto może ogłaszać jakie adresy.</p><h2>IPv6</h2><p>Tam odpowiednikiem jest wykrywanie sąsiadów (NDP), oparte na ICMPv6 — z analogicznym problemem zaufania i analogicznym rozwiązaniem.</p>`,
    sources: [{ url: 'https://datatracker.ietf.org/doc/html/rfc826', title: 'RFC 826 — An Ethernet Address Resolution Protocol' }],
  },
  {
    kat: 'siec',
    title: 'VLAN',
    excerpt: 'Podział jednego przełącznika na kilka niezależnych sieci przez znakowanie ramek.',
    body: `<p><strong>VLAN</strong> to logiczny podział sieci na oddzielne domeny rozgłoszeniowe. Fizycznie urządzenia wpięte są w ten sam przełącznik, ale nie widzą się nawzajem.</p><h2>Znakowanie</h2><p>Standard 802.1Q dokłada do ramki czterobajtowy znacznik z numerem VLAN (1–4094). Port przełącznika bywa:</p><ul><li><strong>dostępowy</strong> — ruch bez znacznika, przypisany do jednej sieci; tak podłącza się komputery i drukarki,</li><li><strong>trunk</strong> — przenosi ruch wielu sieci ze znacznikami; tak łączy się przełączniki i routery.</li></ul><h2>Typowe zastosowanie w domu</h2><p>Oddzielenie kamer i sprzętu inteligentnego domu od komputerów i telefonów. Urządzenia, którym się nie ufa, dostają własną sieć bez dostępu do reszty, ale z wyjściem do internetu.</p><h2>Rzecz, o którą najczęściej się potyka</h2><p>VLAN sam z siebie nie daje adresacji ani routingu. Do każdej sieci potrzebny jest osobny zakres adresów, serwer DHCP i decyzja, co wolno kierować dalej. Bez tego urządzenia trafiają do izolowanej sieci i tracą internet.</p><h2>Bezpieczeństwo</h2><p>Rozdzielenie VLAN-em jest skuteczne przy poprawnej konfiguracji, ale to podział logiczny, nie fizyczny. Błąd w ustawieniu portu trunk potrafi zdjąć całą separację.</p>`,
  },
  {
    kat: 'siec',
    title: 'conntrack',
    excerpt: 'Tablica śledzenia połączeń w jądrze Linux — podstawa NAT i reguł stanowych.',
    body: `<p><strong>conntrack</strong> to podsystem jądra Linux zapamiętujący stan przechodzących połączeń. Dzięki niemu zapora potrafi powiedzieć „przepuść odpowiedź na to, co sami wysłaliśmy", a NAT wie, do kogo odesłać pakiet.</p><h2>Stany</h2><ul><li><strong>NEW</strong> — pierwszy pakiet nowego połączenia.</li><li><strong>ESTABLISHED</strong> — należący do znanego połączenia.</li><li><strong>RELATED</strong> — powiązany, na przykład błąd ICMP albo kanał danych FTP.</li><li><strong>INVALID</strong> — niepasujący do żadnego wpisu.</li></ul><h2>Reguła, która to wykorzystuje</h2><p>Klasyczny szkielet zapory zaczyna się od przepuszczenia ruchu należącego do znanych połączeń, dzięki czemu reszta reguł zajmuje się wyłącznie nowymi.</p><h2>Wyczerpanie tablicy</h2><p>Tablica ma skończony rozmiar. Po zapełnieniu jądro zaczyna odrzucać pakiety i wpisuje do dziennika <code>nf_conntrack: table full, dropping packet</code>. Objawem jest sieć, która „działa i nie działa" pod obciążeniem.</p><pre><code>sysctl net.netfilter.nf_conntrack_count
sysctl net.netfilter.nf_conntrack_max
conntrack -L</code></pre><h2>Kiedy warto wyłączyć</h2><p>Na routerze przepuszczającym bardzo duży ruch, który nie wymaga NAT, śledzenie bywa najdroższą częścią przetwarzania. Da się je pominąć dla wybranego ruchu — kosztem rezygnacji z reguł stanowych dla niego.</p>`,
  },
  {
    kat: 'siec',
    title: 'Ramki jumbo',
    excerpt: 'Ramki ethernetowe większe niż standardowe 1500 bajtów — zysk realny, ale tylko przy zgodzie całej ścieżki.',
    body: `<p><strong>Ramki jumbo</strong> to ramki ethernetowe o ładunku większym niż standardowe 1500 bajtów, zwykle 9000. Mniej ramek na ten sam transfer oznacza mniej przerwań i mniejsze obciążenie procesora.</p><h2>Gdzie ma to sens</h2><p>W sieciach pamięci masowej, przy kopiach zapasowych i ruchu między serwerami wewnątrz jednej szafy. Przy zwykłym ruchu internetowym zysk jest żaden, bo i tak wszystko sprowadzi się do 1500 bajtów na wyjściu.</p><h2>Warunek, którego nie da się obejść</h2><p>Wszystkie urządzenia w ścieżce — obie karty, każdy przełącznik po drodze — muszą być ustawione tak samo. Jedno urządzenie z domyślnym MTU wystarczy, żeby duże ramki znikały bez śladu.</p><h2>Objaw błędnej konfiguracji</h2><p>Ping działa, SSH się loguje, a przesłanie pliku zawiesza się w miejscu. Małe pakiety przechodzą, duże giną — dokładnie ten sam obraz co przy problemie z MTU w tunelu.</p><h2>Sprawdzenie</h2><pre><code>ping -M do -s 8972 192.168.1.10</code></pre><p>Rozmiar 8972 to 9000 minus 28 bajtów nagłówków. Flaga <code>-M do</code> zabrania fragmentacji, więc brak odpowiedzi oznacza, że ścieżka nie przenosi takich ramek.</p>`,
  },
  {
    kat: 'siec',
    title: 'Odciążanie karty sieciowej (offloading)',
    excerpt: 'Przerzucanie części pracy sieciowej na kartę — i powód dziwnych wyników w tcpdump.',
    body: `<p><strong>Odciążanie</strong> to przeniesienie zadań z procesora na układ karty sieciowej: liczenia sum kontrolnych, dzielenia dużych bloków na segmenty czy scalania odebranych pakietów.</p><h2>Najczęstsze mechanizmy</h2><ul><li><strong>TSO/GSO</strong> — system oddaje karcie duży blok, karta sama tnie go na segmenty.</li><li><strong>GRO/LRO</strong> — karta scala odebrane pakiety w większe bloki przed przekazaniem do jądra.</li><li><strong>Sumy kontrolne</strong> — liczone i sprawdzane sprzętowo.</li></ul><h2>Dlaczego psuje diagnostykę</h2><p>Przechwytywanie pakietów odbywa się przed segmentacją i po scaleniu. W <code>tcpdump</code> widać wtedy pakiety o rozmiarach niemożliwych dla danego MTU i błędne sumy kontrolne dla ruchu wychodzącego. To nie jest awaria — to skutek tego, że praca została oddana karcie.</p><h2>Kiedy warto wyłączyć</h2><p>Przy podejrzeniu błędu sterownika, na routerach programowych i przy diagnozowaniu dziwnych zerwań połączeń. Część kart ma tu wadliwe implementacje.</p><pre><code>ethtool -k enp3s0
ethtool -K enp3s0 gro off tso off</code></pre><h2>Koszt</h2><p>Wyłączenie podnosi zużycie procesora, przy ruchu rzędu gigabitów zauważalnie. To narzędzie diagnostyczne, nie domyślne ustawienie.</p>`,
  },
  {
    kat: 'siec',
    title: 'Rozdzielony tunel (split tunneling)',
    excerpt: 'Kierowanie przez VPN tylko części ruchu — wygodne i regularnie mylone z brakiem wycieku.',
    body: `<p><strong>Rozdzielony tunel</strong> to konfiguracja, w której przez VPN idzie tylko wybrany ruch, a reszta wychodzi zwykłym łączem.</p><h2>Jak się to ustawia</h2><p>W WireGuardzie decyduje pole <code>AllowedIPs</code> po stronie klienta. Wpis <code>0.0.0.0/0</code> zabiera cały ruch, a węższy zakres tylko sieć zdalną. Wbrew nazwie to pole pełni podwójną rolę: określa zarówno, co wolno przyjąć, jak i co skierować w tunel.</p><h2>Zalety</h2><ul><li>Dostęp do sieci firmowej bez przepuszczania przez nią całego ruchu prywatnego.</li><li>Brak obciążenia łącza serwera VPN przez pobieranie i strumieniowanie.</li><li>Działające urządzenia w sieci lokalnej — drukarka i dysk sieciowy pozostają osiągalne.</li></ul><h2>Czego nie daje</h2><p>Ruch poza tunelem jest widoczny dla operatora i sieci lokalnej. Jeśli celem VPN była prywatność, rozdzielony tunel ją znosi dla wszystkiego, co nie zostało wskazane.</p><h2>Wyciek DNS</h2><p>Najczęstszy błąd: ruch idzie tunelem, ale zapytania DNS lecą do serwera operatora. Wtedy adresy docelowe są widoczne mimo szyfrowanego połączenia. Rozwiązaniem jest ustawienie <code>DNS =</code> po stronie klienta na serwer dostępny wyłącznie przez tunel.</p>`,
  },
  {
    kat: 'siec',
    title: 'Keepalive',
    excerpt: 'Pakiety podtrzymujące połączenie — lekarstwo na wpisy NAT wygasające w ciszy.',
    body: `<p><strong>Keepalive</strong> to okresowy pakiet wysyłany po bezczynnym połączeniu, żeby potwierdzić, że druga strona żyje, i żeby urządzenia po drodze nie usunęły wpisu ze swoich tablic.</p><h2>Skąd problem</h2><p>Routery z NAT trzymają powiązania przez ograniczony czas. Połączenie bez ruchu przez kilka minut znika z tablicy — i wtedy pakiet wysłany po godzinie ciszy nie ma dokąd wrócić. Objaw: zawieszona sesja SSH, którą trzeba przerwać ręcznie.</p><h2>Warstwy, na których to działa</h2><ul><li><strong>TCP keepalive</strong> — mechanizm systemu, domyślnie z pierwszą próbą dopiero po dwóch godzinach, więc w praktyce zwykle za późno.</li><li><strong>Poziom aplikacji</strong> — SSH ma <code>ServerAliveInterval</code>, WireGuard <code>PersistentKeepalive</code>, wiele protokołów własne pakiety podtrzymujące.</li></ul><h2>WireGuard</h2><p>Tunel jest bezstanowy i nie wysyła nic, gdy nie ma ruchu. Klient za NAT musi więc odzywać się sam, inaczej serwer nie ma jak go zainicjować:</p><pre><code>PersistentKeepalive = 25</code></pre><p>Dwadzieścia pięć sekund to wartość mieszcząca się poniżej typowych czasów wygasania.</p><h2>Kiedy nie ustawiać</h2><p>Po stronie serwera przyjmującego wielu klientów keepalive jest zbędny i tylko generuje ruch — potrzebuje go ta strona, która siedzi za NAT.</p>`,
  },
  {
    kat: 'siec',
    title: 'Wykrywanie MTU ścieżki',
    excerpt: 'Mechanizm ustalania największego pakietu przechodzącego przez trasę — i dlaczego często zawodzi.',
    body: `<p><strong>Wykrywanie MTU ścieżki</strong> (Path MTU Discovery) to sposób, w jaki nadawca ustala, jak duży pakiet przejdzie przez całą trasę bez dzielenia.</p><h2>Zasada</h2><p>Nadawca wysyła pakiety z ustawioną flagą zakazu fragmentacji. Router, przez który pakiet się nie mieści, odrzuca go i odsyła komunikat ICMP z informacją o dopuszczalnym rozmiarze. Nadawca zmniejsza pakiety i próbuje dalej.</p><h2>Czarna dziura</h2><p>Mechanizm w całości opiera się na ICMP. Administratorzy nagminnie blokują ICMP „dla bezpieczeństwa" — i wtedy nadawca nie dostaje żadnej informacji. Pakiety po prostu giną, a nadawca uparcie wysyła je ponownie w tym samym rozmiarze.</p><h2>Rozpoznanie</h2><p>Klasyczny obraz: połączenie wstaje, małe żądania działają, a większa odpowiedź zawiesza się na zawsze. Strona logowania się wyświetla, a lista rekordów już nie. To niemal zawsze MTU, nie aplikacja.</p><h2>Obejście</h2><p>Na routerze lub bramie tunelu wymusza się mniejszy MSS, żeby druga strona sama nie prosiła o za duże segmenty:</p><pre><code>iptables -t mangle -A FORWARD -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu</code></pre><h2>Wniosek praktyczny</h2><p>Blokowanie całego ICMP psuje internet w sposób trudny do zdiagnozowania. Odrzucać warto wybrane typy, nigdy wszystkie.</p>`,
    sources: [{ url: 'https://datatracker.ietf.org/doc/html/rfc1191', title: 'RFC 1191 — Path MTU Discovery' }],
  },
];
